### ISSUE TITLE
Compare generated code to a fixed 1.1 baseline

### ISSUE THREAD

**Issue by sjaakd** [mapstruct/mapstruct#1007]
To avoid problems in generated code java files we should compare a selective set to a set of generated 1.1. generated source code java files. See #996 for more details.

**Comment by filiphr** [comment]
Add tests for:

- [ ] org.mapstruct.ap.test.bugs._913.Issue913SetterMapperForCollectionsTest
- [x] org.mapstruct.ap.test.array
- [ ] org.mapstruct.ap.test.collection.adder
- [ ] org.mapstruct.ap.test.updatemethods
- [ ] org.mapstruct.ap.test.conversion.string

Are there any other tests that we need to add?

**Comment by agudian** [comment]
I'd say create the merge commit locally, add the test fixes to  the test files and push to master 🙂.

**Comment by agudian** [comment]
@filiphr I started merging those commits, as I would need to merge some other stuff soon as well... :)

**Comment by agudian** [comment]
While merging, I found only improvements (yay!), with the exception to this change for an update-method (`ExternalSelectionTest`, in the `DepartmentMapperImpl`):

with 1.1, we generated the following:
```java
        if ( entity.getEmployees() == null ) {
            entity.setEmployees( new ArrayList<EmployeeEntity>() );
        }
        externalHandWrittenMapper.toEmployeeEntityList( dto.getEmployees(), entity.getEmployees() );
```

With the current master, we generate:
```java
        if ( dto.getEmployees() != null ) {
            if ( entity.getEmployees() == null ) {
                entity.setEmployees( new ArrayList<EmployeeEntity>() );
            }
            externalHandWrittenMapper.toEmployeeEntityList( dto.getEmployees(), entity.getEmployees() );
        }
        else {
            entity.setEmployees( null );
        }
```

That seems to be a good idea, but it definetly changes the outcome. There might be users who currently rely on the old behavior, so that should definitely be part of the migration notes. @sjaakd, did you make that change? Would you add something to the migration-notes wiki?

**Comment by agudian** [comment]
Merged to master. Thanks, @filiphr!

**Comment by sjaakd** [comment]
Sure ! I'll add that as soon as I've got the opportunity! Thanks 

Verstuurd vanaf mijn iPhone
