### ISSUE TITLE
RuntimeException when use no package (default)

### ISSUE THREAD

**Issue by diegobmd** [mapstruct/mapstruct#1061]
NullPointerException when use no package (default), on eclipseor build command line

**Comment by gunnarmorling** [comment]
What is it you are using the default package for, the mapper interface or
any mapped type?

**Comment by diegobmd** [comment]
For testar only

**Comment by gunnarmorling** [comment]
Hum, what is "testar"?

**Comment by diegobmd** [comment]
Kkkk, i m a brazilian is a corret by Phineas
I mean
Only for tests

**Comment by diegobmd** [comment]
Kkkk, i m a brazilian is a corret by Phone
I mean
Only for tests

**Comment by gunnarmorling** [comment]
Ok, maybe you can provide a small example exposing this issue? It's still not clear to me where you are using the default package. Are you saying that your JUnit test is located the default package? That should not make any difference to MapStruct really. Can you share the stack trace, too?

**Comment by diegobmd** [comment]
I'm create on github
https://github.com/diegobmd/mapstructapt
RUN gradlew build

:compileJava
mapstructapt\src\main\java\SourceTargetMapper.java:26: error: Internal error in the mapping processor: java.lang.RuntimeException: javax.annotation.processing.FilerException: Illegal name .SourceTargetMapperImpl    at org.mapstruct.ap.internal.processor.MapperRenderingProcessor.createSourceFile(MapperRenderingProcessor.java:67)      at org.mapstruct.ap.internal.processor.MapperRenderingProcessor.writeToSourceFile(MapperRenderingProcessor.java:52)     at org.mapstruct.ap.internal.processor.MapperRenderingProcessor.process(MapperRenderingProcessor.java:42)       at org.mapstruct.ap.internal.processor.MapperRenderingProcessor.process(MapperRenderingProcessor.java:37)       at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:223)         at org.mapstruct.ap.MappingProcessor.processMapperTypeElement(MappingProcessor.java:203)        at org.mapstruct.ap.MappingProcessor.proc
...

**Comment by filiphr** [comment]
It actually it is not a `NullPointerException`. It is an exception because of the name. The Mapper does not have a package.

@gunnarmorling if someone wants to have a mapper in the default package we would have a problem. This are the reasons:
* The [`MapperRenderingProcessor`](https://github.com/mapstruct/mapstruct/blob/master/processor/src/main/java/org/mapstruct/ap/internal/processor/MapperRenderingProcessor.java#L60) - because there is no package we try to create a java file `with the name .SourceTargetMapperImpl`. The `Filler` throws the exception with the message `Illegal name .SourceTargetMapperImpl`
* In [`GeneratedType.ftl`](https://github.com/mapstruct/mapstruct/blob/master/processor/src/main/resources/org/mapstruct/ap/internal/model/GeneratedType.ftl#L21) we explicitly start with `package`. This code will not compile after we generated it.

@gunnarmorling Do we want to create a fix for this use case? 

@diegobmd As a workaround you can use `@Mapper(implementationPackage="com.example")`. The name of the package is not important, just make sure that the generated Mapper is in some package.

**Comment by gunnarmorling** [comment]
Thanks for the analyis, @filiphr. Yes, let's fix it, seems not too hard to do. Using the default package is discouraged, but we shouldn't stop people from using it if they really want.

**Comment by filiphr** [comment]
@gunnarmorling see PR #1062 for the fix.

@diegobmd Can you test out the PR to see if it will work for you?

**Comment by filiphr** [comment]
@diegobmd The fix has been merged into master. You can try using that branch or the already provided workaround. I will continue and close this issue.

**Comment by Hizmarck** [comment]
@filiphr Your solutions not work for me, but it was clarify the way. Thats not work because when I use @Mapper (implementationPackage = "com.example"), all my classes do not have the com.example package, mapstruct generates the implemented class but it is generated with errors:


```
package com.example;

import SimpleDestination; // (Error but this class doesn`t have package example.com)
import SimpleSource; //(Error but this class doesn`t have package example.com);
import SimpleSourceDestinationMapper;// (Error but this class doesn`t have package example.com);
import javax.annotation.Generated;

@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2018-03-16T17:06:46-0600",
    comments = "version: 1.1.0.Final, compiler: javac, environment: Java 1.8.0_162 (Oracle Corporation)"
)
public class SimpleSourceDestinationMapperImpl implements SimpleSourceDestinationMapper {
// .... generated code
}
```

I insist, your comment helped me to clarify the way, only that the solution is not, the easy thing is to assign a package of tests, and that was doing, following the following tutorial, http://bit.ly/2tR2glk.

Thank you very much, greetings.
