### ISSUE TITLE
Extract annotation processor testing infrastructure into separate module

### ISSUE THREAD

**Issue by gunnarmorling** [mapstruct/mapstruct#111]

**Comment by filiphr** [comment]
The testing infrastructure is awesome 😄. It can also be used for testing SPIs (via `@WithServiceImplementation`), I would say that a lot more projects can benefit from it.

I would really be interested in working on this as well, I have also been thinking in porting it to JUnit5, but I don't have that good understanding of the JUnit4 runners 😄

**Comment by gunnarmorling** [comment]
Given the availability of Google's Compile Testing it seems not worth pursuing this any longer. WDYT?

**Comment by filiphr** [comment]
I haven't investigated Google's Compile Testing. However, just by looking at their examples I think that we can't replace our testing infrastructure with it. 

Given the fact that this issue is really old I would say that we can close it. If in case something comes out in the future and we extract our infrastructure into another project we can discuss it then.

**Comment by gunnarmorling** [comment]
>  However, just by looking at their examples I think that we can't replace our testing infrastructure with it.

That's interesting; which usage in our current testing wouldn't be supported from your POV? In any case there seems not much point in extracting our infra any more.

**Comment by filiphr** [comment]
>That's interesting; which usage in our current testing wouldn't be supported from your POV?

I think that they don't have out of the box support for the eclipse compiler and I am not sure if you can get an instance of the generated class. We are not testing only how the code looks like, but we are testing the functionality of the generated mapper as well
