### ISSUE TITLE
MapStruct should ignore @Deprecated marked getters / setters

### ISSUE THREAD

**Issue by sjaakd** [mapstruct/mapstruct#1151]

**Comment by agudian** [comment]
We should talk about this one. Because I really don't think that we should ignore deprecated getters/setters. `@Deprecated` is there to document / mark parts of an API as not to be used in the future, as it will then be either replaced or removed. Especially is it there to _not break the API_ and give users time to migrate.
Ignoring deprecated getters or setters in Mappers would pretty much do the opposite: change behaviour.

But I guess I'm missing something here, right? 😁

**Comment by filiphr** [comment]
I am closing this in favor of #1152. If we implement #1152 in a way that a user can define the annotations via an SPI that MapStruct should use to ignore methods, then the user can add the `@Deprecated` annotation there as well.
