### ISSUE TITLE
java.lang.StackOverflowError if Mappers have circular dependencies

### ISSUE THREAD

**Issue by Muselgrusel** [mapstruct/mapstruct#1163]
Consider the following simplified scenario:

``` java
@Mapper(uses = { BarMapper.class })
public interface FooMapper {

	FooMapper INSTANCE = Mappers.getMapper(FooMapper.class);

	FooDTO fooToFooDTO(Foo source);

	Foo fooDTOToFooA(FooDTO source);
}
```
``` java
@Mapper(uses = { FooMapper.class })
public interface BarMapper {

	BarMapper INSTANCE = Mappers.getMapper(BarMapper.class);

	BarDTO barToBarBDTO(Bar source);

	Bar barDTOTobar(BarDTO source);
}
```
If you use
`ClassAMapper mapper = ClassAMapper.INSTANCE;`
or
`ClassBMapper mapper = ClassBMapper.INSTANCE;`
you will get a StackOverflowError.

I guess there have to be greater modifications of the mapper factory to fix this issue and i have to rewrite my mapper classes ;)?

**Comment by filiphr** [comment]
I don't think that the modifications are that big, there should be some way to hold the instances and return those one when they are requested the second time instead of always creating a new instance.

The reason for the StackOverflowError is that the implementations are also calling `Mappers#getMapper(Class)` as well.

In my opinion I don't think that we should be keeping instances in order to avoid cycles. I would suggest for you to break the cycle somehow in your mappers :)

**Comment by Muselgrusel** [comment]
I think the problem is that you can't even get to the point holding and returning an instance of one of the classes if the way the classes are generated doesn't change:
> The reason for the StackOverflowError is that the implementations are also calling Mappers#getMapper(Class) as well.

...and triggering an infinity loop...
Without changing the way the classes are generated i don't see any way to break the loop but if you see a possibility i would like to know (just out of curiosity).

Hmm i aggree that you shouldn't be keeping instances in the factory just to avoid cycles. But the possibility to handle a use case more (with a good solution) wouldn't be bad would it ;)?

**Comment by agudian** [comment]
I think what Filip means is that you could try to refactor your mappers to not have cycles in `@Mapper#uses`.
Another alternative is using Spring or something else (see `@Mapper#componentModel`) - that would take care of such cycles.

**Comment by filiphr** [comment]
Thanks @agudian. @Muselgrusel this is exactly what I meant, you should try to break the cycle dependency in your own mappers.

>Hmm i aggree that you shouldn't be keeping instances in the factory just to avoid cycles. But the possibility to handle a use case more (with a good solution) wouldn't be bad would it ;)?

I think that this will make the `Mappers` quite complex. The `Mappers` factory is really simple, it gets a `Mapper` class and instantiates the `MapperImpl` there is nothing special going on in there. In order to support a use case like this we would have to make it much more complex, and make sure that the generated code also uses some flags when it asks for an instance of a `Mapper`.

I would suggest you not the use the `default` component model, but switch to some DI like Spring that can handle cyclic dependency much more elegantly that we could ever do.

**Comment by Muselgrusel** [comment]
Thanks for your suggestions, but using a DI framework is no option at the moment and would possibly be over the top.

I will refactor my mapper classes but would like to have the possibility to use mappers with circular dependencies and without a DI framework with MapStruct anyway.
If i would provide a way (and the code) to handle such use cases as an option in MapStruct will you be open minded adding that to the master?

**Comment by filiphr** [comment]
>If i would provide a way (and the code) to handle such use cases as an option in MapStruct will you be open minded adding that to the master?

Speaking only from my name, I don't see a problem accepting a PR for a use cases like this. I think that this should be an opt in functionality though.

@gunnarmorling, @agudian, @sjaakd WDYT?

**Comment by agudian** [comment]
I thought about it a bit and I wasn't able to come up with an idea of how a Mappers-factory based solution could work (short of byte-code enhancement). So I'm very curious about what @Muselgrusel has in mind :-).

An alternative would be a custom componentModel, added via SPI, that changes the way the mapper refereced are constructed.

Btw, that reminds me of that other issue where mapper reference injection is proposed to be changed to (optional??) constructor-injection / setter injection.

**Comment by filiphr** [comment]
>I thought about it a bit and I wasn't able to come up with an idea of how a Mappers-factory based solution could work (short of byte-code enhancement). So I'm very curious about what @Muselgrusel has in mind :-).

A way that I am seeing to solve this is to use memoization (i.e. make the Mappers singleton and if the same mapper is requested then just return the instance).

**Comment by sjaakd** [comment]
@filiphr . Is this fixed with the `@Context` now?

**Comment by filiphr** [comment]
Nope, this is about our `Mappers` factory and circular dependencies between mappers.

Like `FooMapper` needs `BarMapper` and vice cerse

**Comment by amazel** [comment]
Hi guys, I have fixed this using @Mapping(ignore = true) please take a look at my blog https://springjourneydotblog.wordpress.com/2018/04/25/bidirectional-relation-between-entity-objects-with-mapstruct/

**Comment by ldolbir** [comment]
This issue is related to the code generation style. If the mapper attribute is lazy initialized and accessed through the getter, then the problem would go away

**Comment by ldolbir** [comment]
The other way to avoid conflict is to resolve the Mapper using static INSTANCE variable instead of generating it as an instance variable.

**Comment by nagzso** [comment]
Any update on this?

**Comment by sjaakd** [comment]
@nagzso : reading the discussion above I don't think that we should do anything here. Its up to the user not to create cyclic references in the default component model. @ldolbir, you are right that you could create  a true singleton pattern. However, that would lead to problems if you use another component model type.

@filiphr : close this issue?

**Comment by filiphr** [comment]
I agree @sjaakd.

Although possible I would like to avoid making the `Mappers` complex and stateful. If someone needs to have cyclic mappers with the default model they can easily create their own static factory. Since 1.3.0 it would even be easier, as the `Mappers` have a new method `getMapperClass(Class)` that would allow writing such stateful mapper much easier.

**Comment by AkshayMathur92** [comment]
A general approach (worked for me ) is to set one direction linking in the default manner and using "@AfterMapping" to set the other direction references.

**Comment by akiaoueted** [comment]
> Hi guys, I have fixed this using @mapping(ignore = true) please take a look at my blog https://springjourneydotblog.wordpress.com/2018/04/25/bidirectional-relation-between-entity-objects-with-mapstruct/

@hugolezama 
I had the same issue and this has worked for me. thanks!!
