### ISSUE TITLE
Loosing element value on conversion from JAXBElement<T> 

### ISSUE THREAD

**Issue by dmitry87** [mapstruct/mapstruct#1182]
The issue is in generated code:
```java
 private <T> T jaxbElemToValue( JAXBElement<T> element ) {
        if ( element == null ) {
            return null;
        }

        return element.isNil() ? null : element.getValue();
    }
```
When converting to DTO object following part of xml `<sexCode>F</sexCode>` that have JAXB representation as `JAXBElement<String> sexCode` returns `true` on `element.isNil()` check. As the result of this operation we loose our F value when storing to DTO. Generations rule can be fixed here. 
However the workaround is following:
```java
@Mapper(uses = MapperUtil.class)
```
And here is the method in MapperUtil.class
```java
public static String nilElementToString(JAXBElement<String> element) {
        if (element == null) {
            return null;
        }
        return element.getValue();
    }
```
Generated code:
```java
dto.setSexCode( MapperUtils.nilElementToString( info.getSexCode() ) );
```

Hope this will help someone

**Comment by filiphr** [comment]
Is this an issue for MapStruct or you just posted it so people can find it? If it is the second, I propose that we write this in the MapStruct [Google group](https://groups.google.com/forum/?fromgroups#!forum/mapstruct-users). I don't have a lot of experience with JAXB, but to me this looks like a problem with that. Why is `nil` in the `JAXBElement` set to `true` in the first place?

**Comment by dmitry87** [comment]
@filiphr I believe it is a bug. I hit this during development. I am not sure why `element.isNil() == true` in my case. I think we just do not need this check. It is redundant because we will return value or null when we have `element != null` itself. I've posted workaround in case someone hit that too before bug is fixed.

**Comment by filiphr** [comment]
@dmitry87 I don't know much about the specification. If you look at the definition of [`JAXBElement#isNil`](http://docs.oracle.com/javaee/7/api/javax/xml/bind/JAXBElement.html#isNil--) it says:

>Returns `true` iff this element instance content model is nil.
>
> This property always returns true when `getValue()` is null. Note that the converse is not true, when this property is true, getValue() can contain a non-null value for attribute(s). It is valid for a nil xml element to have attribute(s).

Also if you look at the definition at [w3.org](https://www.w3.org/TR/xmlschema-0/#Nils) it clearly says that an element should not have any content and just attributes. So in your case, I would say that something strange is happening with your XML. If it really looks like `<sexCode>F</sexCode>` then `nil` should be `false`, and not `true`

**Comment by dmitry87** [comment]
@filiphr I have no control over xsd or xml. JAXB generated value looks like 
```java
    @XmlElementRef(name = "sexCode", type = JAXBElement.class)
    protected JAXBElement<String> sexCode;
```
Now we return `element.getValue()` if and only if `!isNil()`. If `isNil() == true` we will return null. 
So I mean here that we can `return element.getValue()` from the very beginning without `isNil()` check. If `isNil() == true` we will get  `null` or `value` from the element(it may contain attributes). If `!isNil()` we will get value. I believe it will not brake anything here. 
However if it is by design, people can use this workaround.

**Comment by filiphr** [comment]
@dmitry87 by all means MapStruct is not there too impose how a user should map their objects. I just wrote more about that, because the example looked strange.

With the `@Mapper(uses)` you can take over any built-in conversion from MapStruct. User defined methods always have the highest precedence in MapStruct.

For example if you define a method that maps `String` to `String` and put it into `uses` MapStruct will use that to map between 2 `String`(s) and not directly set it.

If you think that this can be closed, can you please close it?

**Comment by sjaakd** [comment]
@dmitry87 : the `isNill` in JAXBElement comes from elements that have the attribute `nillable=true`. See [here](https://www.w3schools.com/xml/el_element.asp). XML being text base has no means to distinguish between an `empty` or  a `null` value. Especially strings are tricky. By adding the attribute `nil=true`  to your xml (when the element XSD definitions allows for that) tells your java binding solution that the value is null (and not empty). In java, it means that this is mapped to null. 

Now, the Xml to Java Compiler, XJC adds the `JAXBElement` if:
1. an element (e.g. in a sequence) is both: a) optional `minOccurs = 0` and b) `nillable=true` 
2. the binding file explicitly tells you to add it (I think its called generateElementProperties) or something along that lines.
Because: java can (of course) distinguish between `null` and `empty`. Conflicts do arise when an element value can both be absent due to `null` and due to `optional`. The latter one being the realization of `minOccurs=0`.

Initially this was not correctly implemented in the java to xml parsing (jaxb-impl) in java. I had problems in Jboss for example. When Jboss switched to CXF it became a bit more stable, but still I (as common practice) override the mapstruct default implementation because I need to distinguish in my resulting DTO model the difference between empty and null. 

Hope my answer helps.

Some JAXB implementations do not do this correctly

**Comment by dmitry87** [comment]
@sjaakd thanks for explanation. 

> By adding the attribute nil=true to your xml (when the element XSD definitions allows for that) tells your java binding solution that the value is null (and not empty). In java, it means that this is mapped to null.
In my particular case 
```xml
...
<sexCode>F</sexCode>
...
``` 
and nilable should be false here I believe, however it's not. Perhaps this is JAXB implementation issue as you said above. It can be fixed by using Custom mapper for this.
