### ISSUE TITLE
Bug: Lombock @Delegate property cannot be accessed as target-property

### ISSUE THREAD

**Issue by IrishkA13** [mapstruct/mapstruct#1191]
**Compilation failure: Unknown property "employeeId" in return type.**

```
@Data
public class AppointmentInfoDTO {

    @Delegate
    private BaseAppointmentDTO baseAppointment;
    ...
}
```

```
@Data
public class BaseAppointmentDTO {

    private Long employeeId;
    ...
}
```

```
    @Mappings({
            @Mapping(source = "employee.id", target = "employeeId"),
    })
    AppointmentInfoDTO appointmentToDto(Appointment appointment);
```
@Delegate create get-accessors in Appointment for inner fields so the all BaseAppointmentDTO fields are accessible within AppointmentInfoDTO but mapstruct doesn't consider this. 
There are 2 correct ways to access:
```
AppointmentInfoDTO dto = new AppointmentInfoDTO ();
appointmentInfoDTO.getEmployeeId();//mapstruct doesn't allow
appointmentInfoDTO.getBaseAppointment().getEmployeeId();
```

**Comment by filiphr** [comment]
You are using 1.2.0.Beta2 with Lombok at least at 1.16.14. 

I tried using lombok `@Delegate` and it looks like lombok is not adding the necessary information (the executables to the Type) to the `AppointmentInfoDTO`. Did you create an issue in the lombok repository? If yes can you link it with this one, if not can you create one and link it with this one? 

On the other side how will the `baseAppointment` be created in the `AppointmentInfoDTO`? Are you creating the `AppointmentInfoDTO` via an `@ObjectFactory`?

**Comment by IrishkA13** [comment]
Filiphr, thanks for quick reply!
Versions that are used:
mapstruct = 1.2.0.Beta2
lombok = 1.16.14

I didn't create the bug for lombok as it works as expected.
I don't use  @ObjectFactory. As I understand the problem here is that the search for @Mapping target is done by properties, not by get/set methods so the code that is generated by lombok looks like this

```
public class AppointmentInfoDTO {
    private BaseAppointmentDTO baseAppointment;

    public AppointmentInfoDTO() {
    }

    public BaseAppointmentDTO getBaseAppointment() {
        return this.baseAppointment;
    }

    public void setBaseAppointment(BaseAppointmentDTO baseAppointment) {
        this.baseAppointment = baseAppointment;
    }

 public Long getEmployeeId() {
        return this.getBaseAppointment().getEmployeeId();
    }

    public void setEmployeeId(Long employeeId) {
        this.getBaseAppointment().setEmployeeId(employeeId);
    }
...
}
```

It doesn't allow to use lombok @Delegate together with mapstruct.

**Comment by IrishkA13** [comment]
One more thing that the nested fields mapping also doesn't work correctly for me.
There is a mapping **employee.id -> baseAppointment.employeeId.** 
Instead I have mapping **employee -> baseAppoinment**.

```
//This mapper uses config = BaseAppointmentMapper.class for classes that extends super-class Appointment 
@DecoratedWith(AppointmentInfoDtoMapperDecorator.class)
@Mapper(componentModel = "spring",
        config = BaseAppointmentMapper.class,
        nullValueCheckStrategy = NullValueCheckStrategy.ON_IMPLICIT_CONVERSION
        )
public interface AppointmentInfoDtoMapper {
...
}

@MapperConfig(
        mappingInheritanceStrategy = MappingInheritanceStrategy.AUTO_INHERIT_FROM_CONFIG
)
interface BaseAppointmentMapper {
    @Mappings({
            @Mapping(source = "employee.id", target = "baseAppointment.employeeId"),
    })
    AppointmentInfoDTO appointmentToDto(Appointment appointment);
}
```

The generated code for this looks like:
```
appointmentInfoDTO.setBaseAppointment( employeeToBaseAppointmentDTO( appointment.getEmployee() ) );
...
    protected BaseAppointmentDTO employeeToBaseAppointmentDTO(Employee employee) {
        if ( employee == null ) {
            return null;
        }

        BaseAppointmentDTO baseAppointmentDTO = new BaseAppointmentDTO();

        baseAppointmentDTO.setEmployeeId( employee.getId() );
        baseAppointmentDTO.setId( employee.getId() );

        return baseAppointmentDTO;
    }      
```

 Here is the whole mapping class I use
```
@DecoratedWith(AppointmentInfoDtoMapperDecorator.class)
@Mapper(componentModel = "spring",
        config = BaseAppointmentMapper.class,
        nullValueCheckStrategy = NullValueCheckStrategy.ON_IMPLICIT_CONVERSION
        )
public interface AppointmentInfoDtoMapper {

    @Mappings({
            //this field will be mapped within AppointmentMapperDecorator
            @Mapping(target = "prescription", ignore = true),
    })
    AppointmentInfoDTO appointmentToDto(PatientAppointment appointment);

    @Mappings({
            @Mapping(target = "group", constant = "true")
    })
    AppointmentInfoDTO appointmentToDto(GroupAppointment appointment);

    @Mappings({
            @Mapping(target = "description", constant = "Privater Termin"),
            @Mapping(target = "privat", constant = "true")
    })
    AppointmentInfoDTO appointmentToDto(PrivateEmployeeAppointment appointment);
}

@MapperConfig(
        mappingInheritanceStrategy = MappingInheritanceStrategy.AUTO_INHERIT_FROM_CONFIG
)
interface BaseAppointmentMapper {
    @Mappings({
            @Mapping(source = "employee.id", target = "baseAppointment.employeeId"),
    })
    AppointmentInfoDTO appointmentToDto(Appointment appointment);
}
```

**Comment by filiphr** [comment]
This is answer for https://github.com/mapstruct/mapstruct/issues/1191#issuecomment-298848904
@IrishkA13 yes `@Mapping` works with properties. However, properties according to the [Javabeans specification](http://download.oracle.com/otn-pub/jcp/7224-javabeans-1.01-fr-spec-oth-JSpec/beans.101.pdf) chapter 2.2 are not fields of a class.

>Properties are described in more detail in Section 7. Basically properties are named attributes
associated with a bean that can be read or written by calling appropriate methods on the bean.
Thus for example, a bean might have a “foreground” property that represents its foreground
color. This property might be read by calling a “Color getForeground()” method and updated
by calling a “void setForeground(Color c)” method

MapStruct never looks at `private` fields. If a field is `public` MapStruct will consider it as an option for accessing it, as for methods we use the [`AccessorNamingStrategy`](http://mapstruct.org/documentation/stable/api/org/mapstruct/ap/spi/AccessorNamingStrategy.html) to get a name of a property and we match that with what you have given in `@Mapping#source` and `@Mapping#target`.

For example if you have:

```java
class MyClass {
    private String property;

    public String getName() {
        return property;
    }
    
    public void setName(String name) {
        this.property = name;
    }
}
```

Then you can only use `name` in the `@Mapping` and not `property`.

I am not sure how exactly Lombok works and whether they create the `@Delegate` in the first annotation processor round or the second. In any case Lombok is not your typical APT, it alters the type itself and does not create a new type. It does this by altering the bytecode of the type. In order for the methods created by Lombok to be recognized by other annotation processors (like MapStruct) that are running in the same cycle, the guys from Lombok had to do something extra. For this reason, I think that this should be a Lombok issue, because we see the other generated getters/setters from the `@Data` annotation. It would be a MapStruct issue if you do delombok on your class and try it out. If it doesn't work it really is some issue with MapStruct

**Comment by filiphr** [comment]
To answer your 2nd https://github.com/mapstruct/mapstruct/issues/1191#issuecomment-298852141.

What you are experiencing there is the new feature that allows automatic creation of sub-mapping methods and control of mappings from the root mapping.

You are controlling how `employee` needs to be mapped from the root object. MapStruct sees `@Mapping(source = "employee.id", target = "baseAppointment.employeeId")` is symmetrical and will create mapping like:

```java
@Mapping(source = "id", target = "employeeId")
protected abstract BaseAppointmentDTO map(Employee employee);
```
What exactly are you expecting MapStruct to create?

In order to ignore the mapping to the `id` from `BaseAppointmentDTO` you need to add:
`@Mapping(target = "baseAppointment.id", ignore = true)` to your `BaseAppointmentMapper`. 

You can also define a Mapper that will do the mapping between `Employee` and `BaseAppointmentDto` define how exactly it needs to be mapped there. You should then add this mapper to `@Mapper#uses` and just use ``@Mapping(source = "employee", target = "baseAppointment")` in your `BaseAppointmentMapper`. You can even add the custom mapper to the `BaseAppointmentMapper` config that you have.

**Comment by IrishkA13** [comment]
Thanks for reply. I have already done some chnages to make it applyable for my needs. 
But anyway it works incorrectly and it will be good not to find the single variant it normally works as I did but to use all common ways that are provided by mapstruct.
Especially mapping employee -> baseAppointment instead of employee.id -> baseAppointment.employeeId.
If I try additionally map someField -> baseAppointment.someField I recieve 2 generated methods:
employeeToBaseAppointment and sourceToBaseAppointment - both methods create new baseAppointmnent, so I will recieve only 1 field inside baseAppointment employeeId or someField. The second field will be lost during creation new base appointment in the second method-call.
It doesn't look @Delegate problem. 
It would be great if you could take care about it for further versions of mapstruct.

**Comment by filiphr** [comment]
@IrishkA13 the feature that allows to control sub-mappings from the root level is new and we really appreciate the feedback.

Regarding your points, I would like to sum them up so it is clearer to me:
* You are saying that in your case you want to only map `employee.id` to `baseAppointment.employeeId` and not the other fields? And that you want to have an ability that will only do mapping on defined fields?
* For create methods there is an issue when nested objects need to have their state updated from different object. Maybe you need to try and use [update-mappings](http://mapstruct.org/documentation/stable/reference/html/#updating-bean-instances), with those a new object will only be created if it is `null`, otherwise the existing object is reused.

I didn't understand what you mean with;
>It doesn't look @Delegate problem.

Do you think that the `@Delegate` is  a problem in MapStruct or not? If you still think that this is an issue, I would create an issue in the Lombok repository so we can learn more from their side.

I would propose that you open an issue for each separate problem that you have and we can address each and every one of them separately.

**Comment by filiphr** [comment]
If the Lombok `@Delegate` is still a problem than an issue needs to be raised with the Lombok team. If a getter for the delegated property is there then MapStruct will see it, exactly like the `@Getter` and `@Setter` from Lombok.

If there are some other problems, I would suggest opening a new issue.
