### ISSUE TITLE
Not able to use MapStruct generated Impl class in Unit Test

### ISSUE THREAD

**Issue by santoshkt** [mapstruct/mapstruct#1208]
I have a unit test class like below.

```

public class CountryMapperImplUnitTest {

    private Country country;
    private CountryDTO dto;

    @InjectMocks
    private CountryMapper countryMapper = new CountryMapperImpl();

    @BeforeMethod
    public void beforeMethod() {

        country = new Country();
        country.setCountryCode("US");
        country.setCountryId((long) 1);
        country.setCreatedBy((long) 1);
        country.setCreatedDt(new Date(System.currentTimeMillis()));
        country.setDescription("DESCRIPTION");
        country.setName("UNITED STATES");
        country.setUpdatedBy((long) 1);
        country.setUpdatedDt(new Date(System.currentTimeMillis()));

        dto = new CountryDTO();
        dto.setCountryCode("US");
        dto.setName("UNITED STATES");

    }

    @Test
    public void countryToCountryDTO() {

        CountryDTO converted = countryMapper.countryToCountryDTO(country);
        Assert.assertEquals(converted.getCountryCode(), dto.getCountryCode());
        Assert.assertEquals(converted.getName(), dto.getName());
    }
}

```

My collegues using Eclipse are able to run unit tests in their IDE but I am a IDEA user and I can't run the tests. I also tried the steps at http://mapstruct.org/development/ide-setup/ but no use.

IDE cannot detect `CountryMapperImpl` class as shown in above examples. What are my options with IDEA ?

**Comment by filiphr** [comment]
The steps in your link are for setting up a development for the MapStruct source code. For using MapStruct have a look at http://mapstruct.org/documentation/ide-support/. 

You should definitely have the annotation processing enabled and because of the way IDEA sets up the annotation processing, you have to have the `mapstruct-processor` as an optional or provided dependency. There is all this info in the link as well (also links to IntelliJ bugs so you can vote on them 😀)

**Comment by filiphr** [comment]
@santoshkt did my comment work for you? I'll close the issue, if you think that it needs to be reopened please do ao
