### ISSUE TITLE
Add Java 9 Automatic Module Name in Manifest

### ISSUE THREAD

**Issue by filiphr** [mapstruct/mapstruct#1224]
Is this something that we want for 1.2.0.Final or we should do it in the next release?

**Comment by gunnarmorling** [comment]
Let's do it if there's a Java 9 build supporting that header available at the time of the release.

**Comment by jodastephen** [comment]
No need to wait for a Java 9 build now, the spec looks pretty set in stone.

Where I do have concerns with a quick look is that the Java code in the core, core-jdk8 and core-common folders all have the same package name. If these are built into separate jar files, then they cannot be separate modules, because a package can only be allocated to one module.

**Comment by gunnarmorling** [comment]
Yes, not much risk to adding the header righ away, I guess.

> If these are built into separate jar files

Users will only either depend on _core_ or _core-jdk8_. _core-common_ is pulled into the other two at build time of MapStruct (we use it to share common code between these two flavors of the MapStruct API JAR). So people won't end up with multiple modules containing the {{org.mapstruct}} package unless there's something wrong with their module path setup.

**Comment by gunnarmorling** [comment]
Java 9 b175 is out by now which supports the `Automatic-Module-Name` header. We're already making use of it in Bean Validation and Hibernate Validator.

**Comment by agudian** [comment]
Gunnar fixed it, thanks! 👍
