### ISSUE TITLE
import is not generated for sub-packages of java.lang

### ISSUE THREAD

**Issue by brabenetz** [mapstruct/mapstruct#1227]
I tried to map java.lang.management.ThreadInfo:

`void map(final ThreadInfo threadInfoSrc, @MappingTarget final ThreadDto threadDto);`

even `@Mapper(imports = ThreadInfo.class` didn't work.

The generated class didn't include the import statement.
I use MapStruct 1.1.0.Final with java8

**Comment by filiphr** [comment]
There is an explicit ignore for all classes that start with `java.lang`.  It seems we need to ignore only classes that are in the `java.lang` package. The problem is [here](https://github.com/mapstruct/mapstruct/blob/master/processor/src/main/java/org/mapstruct/ap/internal/model/GeneratedType.java#L238) `GeneratedType`.
