### ISSUE TITLE
[Enhancement]Return original instance parameter, not new instance

### ISSUE THREAD

**Issue by jinyahuan** [mapstruct/mapstruct#1250]
Sometimes i just wanna save anything, but always create new something, and lose original.
This is demo i think: 

```
public class Demo {
  @lombok.ToString
  @lombok.Getter
  @lombok.Setter
  private class Computer {
    private String code;
    private String name;
    private Mainboard mainboard;
    // ... more fields

    // Assemble the new components on an existing computer.
    public Computer assemble(final Computer computer, final Mainboard mainboard) {
      computer.setMainboard(mainboard);

      return computer;
    }
  }

  @lombok.ToString
  @lombok.Getter
  @lombok.Setter
  private class Mainboard {
    private String code;
    private String name;
  }
}
```

**Comment by filiphr** [comment]
I am not sure if I understand correctly what you are trying to achieve. Do you want a mapper that returns the original parameter or you want to pass the original parameter somewhere?

If it is the first than this is already possible. Have a look at [Updating exiting bean instances](http://mapstruct.org/documentation/stable/reference/html/#updating-bean-instances) in the reference documentation.

For your use case you would have:

```java
@Mapper
public interface ComputerMapper {

    @Mapping(target = "mainboard", source = "mainboard") 
    Computer assemble(@MappingTarget Computer computer, Mainboard mainboard);
}
```

The generated method will look like the one in your `Demo`. Also the `@Mapping` is needed, because you need to map a property of the `Computer` with the source parameter.

**Comment by jinyahuan** [comment]
Thanks! That's what I want when i see generated code.

**Comment by filiphr** [comment]
Glad I could help. If you experience any issues or have other ideas feel free to open issues here 😄

**Comment by jinyahuan** [comment]
Why not?! Mapstruct is a very good project, once i wanna design.
