### ISSUE TITLE
Add static code analysis with SonarQube

### ISSUE THREAD

**Issue by kevcodez** [mapstruct/mapstruct#1311]
SonarCloud offers free static code analysis for open-source projects. 

I could help set it up aswell, if you are interested.

Would like to know your opinion on this.

**Comment by filiphr** [comment]
We were actually thinking of using it due to https://github.com/mapstruct/mapstruct/issues/1129 and a special rule that we needed in order to notice that bug in the future. However, for that particular case we went with [forbidden-apis](https://github.com/policeman-tools/forbidden-apis).

Having it will certainly not hurt us. Did you had in mind that it would be used as a PR check as well, or just informational?

**Comment by kevcodez** [comment]
It could also be used for PRs, sure. Or have a long term branch (i.e. master/releaseX).

Usually, you want to persist the analysis of long term branches (release branches and master) and only do a so called "preview" analysis for PRs, comparing the found issues with the long term branch but do not persist the issues, since the PR branch will be deleted quickly.
