### ISSUE TITLE
Unrelated mappings grouped into one method

### ISSUE THREAD

**Issue by MateuszPrzybyla** [mapstruct/mapstruct#1329]
I have following source-side models:

    class Source {
        SourceItems items;
    }

    class SourceItems {
        List<SourceItem> item;
    }

    class SourceItem {
        String order;
        ItemValues values;
    }

    class ItemValues {
        SourceValue total;
        SourceValue localized;
    }

and following target-side models:

    class Target {
        List<TargetItem> items;
    }

    class TargetWrappingItem {
        int position;
        TargetItem item;
    }

    class TargetItem {
        boolean selectable;
        TargetValue totalValue;
        TargetValue localizedValue;
    }

Now I have a mapper which should map Source model to a Target model:

    @Mapper(uses = ValueMapper.class, componentModel = "spring", unmappedTargetPolicy = ReportingPolicy.ERROR)
    abstract class SourceMapper {
        @Mapping(target = "items", source = "items.item")
        abstract Target mapSourceToTarget(Source source);

        @Mapping(target = "item.selectable", constant = "false")
        @Mapping(target = "position", source = "order")
        @Mapping(target = "item.totalValue", source = "values.total")
        @Mapping(target = "item.localizedValue", source = "values.localized")
        abstract TargetWrappingItem mapItemToItem(SourceItem source);
    }

I also have another mapper that is responsible for mapping SourceValue to TargetValue:

    @Mapper(componentModel = "spring", unmappedTargetPolicy = ReportingPolicy.ERROR)
    class ValueMapper {
        @Autowired
        private BusinessValueMapper valueMapper;

        TargetValue mapSourceValueToTargetValue(SourceValue source) {
            return valueMapper.toTarget(source.getAmount(), source.getCurrencyCode());
        }
    }

When MapStruct generates implementation of a SourceMapper, here is what I get and I'm totally not expecting:

	protected void valuesToTargetItem(ItemValues values, TargetItem mappingTarget) {
		if ( values == null ) {
			return;
		}

		mappingTarget.setTotalValue( valueMapper.mapSourceValueToTargetValue( values.getTotal() ) );
		mappingTarget.setLocalizedValue( valueMapper.mapSourceValueToTargetValue( values.getLocalized() ) );

		mappingTarget.setSelectable( Boolean.parseBoolean( "false" ) );
	}

I expect the `selectable` always to be set to `false`. But it's null in case of `values` in sourceItem is null. The code I attached above is responsible for such a behavior. It looks like the mappings are grouped in a way that is incorrect. I think that it's a bug, but maybe I'm just missing some configuration. Could you please advise?

**Comment by filiphr** [comment]
First tip, your if your `ValueMapper` has no other methods that MapStruct needs to implement you can just annotated it with `@Component`, in `@Mapping@uses` you can put whatever you want, not just `@Mapper`.

Apart from that, you might be right and that mapping might be wrong. You are using nested target mappings, which have been overhauled for 1.2. However, I think that the way it works, has been working always. In any case I think that your mapping is not correct in the first place. Either `Target` contains `List<TargetWrappingItem>` or you need to do some changes. I would assume that `Target` contains `TargetWrappingItem`. Do you have other mappings in `SourceMapper`, because the generated method should not look like that.

In any case it is debatable what should happen for the constant, especially if you look from the perspective when a non update mapping is performed

**Comment by sjaakd** [comment]
@MateuszPrzybyla : can you respond to @filiphr .. I'm browsing through our issues and going to close issues without response soon.
