### ISSUE TITLE
Allow package-private mapper

### ISSUE THREAD

**Issue by gervaisb** [mapstruct/mapstruct#1365]
To limit visibility, we have a package-private mapper interface. While the compilation pass without any problems, the tests reveals that the mapper impl cannot be created:
```
Caused by: java.lang.IllegalAccessException: Class org.mapstruct.factory.Mappers can not access a member of class com.acme.PackagePrivateMapperImpl with modifiers ""
  at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:102)
  at java.lang.Class.newInstance(Class.java:436)
  at org.mapstruct.factory.Mappers.doGetMapper(Mappers.java:99)
```

Having package-private classes (and mappers) help to expose clean interfaces outside a package without exposing the plumbing.

**Comment by filiphr** [comment]
If you are using the `Mappers` factory in your tests it means you are exposing the plumbing. How are you using the mappers in your production code? If you are not using the default `componentModel`, I would suggest that you instantiate the mappers in the same way in your tests, otherwise you are risking to have invalid mappers during your tests.

What you could do is to create your own `Mappers` factory that would allow you to instantiate package private mappers. One would need to get the constructor, make it accessible and then instantiate the class. In theory we can bring this into the Factory, but I am not sure if it is really needed...

I also have a similar setup, where the public interface has no knowledge of MapStruct, but then the mapping definition extends this interface and provides the mappings and some extra information for the MapStruct mapping. However, I am using the spring `componentModel`, for the tests I am using spring so I can get the mappers as well.

**Comment by gervaisb** [comment]
I'm testing the mappers but from a test within the same package. So I test the plumbing but keep it package-private.

Of course I can create my own mapper factory. But that's code that we have to duplicate while we use MapStruct to reduce the duplication and boilerplate. This was just a proposal.

**Comment by gunnarmorling** [comment]
@filiphr We could add something like this to the `Mappers` factory:

```
if ( !isAccessible( mapperImplTypeConstructor ) ) {
    mapperImplTypeConstructor.setAccessible( true );
}
```

The only caveat is that on Java 9 with named modules a module containing the mapper implementation must open (at least that package) towards the MapStruct module.

**Comment by filiphr** [comment]
@gunnarmorling there is already an open PR (#1366) from @gervaisb for this. Do you have time to review it?

Regarding Java 9, maybe we can first try to create a new instance, and catch the `IllegalAccessException` and try to set it to accessible. I think that otherwise even when the constructor is public one would need to open towards the MapStruct module (or that needs to be done for public new instance as well, unfortunately I don't know Java 9 that well 😄).

**Comment by filiphr** [comment]
We have merged the PR to master. Thanks for the contribution @gervaisb. Sorry that it took so long
