### ISSUE TITLE
Mapstruct: Cannot find implementation for 

### ISSUE THREAD

**Issue by MincaBuca** [mapstruct/mapstruct#1380]
Hi :).

I need your help. My project does not generate the implementation classes. 
IDE: Version: Oxygen. 1a Release (4.7.1a). 

Here's my pom. xlm.

Head:
![grafik](https://user-images.githubusercontent.com/33893702/36249363-b3f85dce-123a-11e8-9e01-5b99256f0340.png)

Build:
![grafik](https://user-images.githubusercontent.com/33893702/36249412-e9b386aa-123a-11e8-8413-fc22b9898de9.png)

My Interface:
![grafik](https://user-images.githubusercontent.com/33893702/36249562-62f1cc16-123b-11e8-978d-26924163e97f.png)

![grafik](https://user-images.githubusercontent.com/33893702/36249722-e023ba64-123b-11e8-9ae8-8534af0950f7.png)

![grafik](https://user-images.githubusercontent.com/33893702/36249662-aba32c2a-123b-11e8-8410-cba7309fc155.png)

What am I doing wrong, I'm new in this world

**Comment by filiphr** [comment]
The reason why it is not working is that the `maven-compiler-plugin` coming from your spring boot parent is `3.1`. However, the support for `annotationProcessorPaths` is there only since `3.5.1`.

You have 2 options to make everything work (as I see you have lombok and I presume spring-boot-autoconfigure-processor):

* Change the version of the compiler to the latest one, or at least `3.5.1` and put all the annotation processors in `annotationProcessorPaths` (`lombok` and `spring-boot-autoconfigure-processor`)
* Put the `mapstruct-processor` as a provided dependency (this is actually the way to go if you want the stuff to work within IntelliJ, due to [IDEA-150621](https://youtrack.jetbrains.com/issue/IDEA-150621))

I am going to close this ticket, we can reopen it if this does not work for you
