### ISSUE TITLE
Hook into the mapping process by calling @BeforeMapping / @AfterMapping methods

### ISSUE THREAD

**Issue by agudian** [mapstruct/mapstruct#14]
... e.g. to call a certain method that might flush the entity manager before starting to map ;).

Perhaps by:
* making the Freemarker template file name configurable in the AP
* or (perhaps better): allow to specify a super class for the mapping impl and call before / after methods. The super class might define methods for that, annotated with @BeforeMapping or something similar.

Cheers,
Andreas

**Comment by agudian** [comment]
So guys, time to find out what we can do with this one in order to make all of us as happy as we are with the mapping config inheritance... :)

This is comment going to be a bit lengthy, so let's start with summarizing what problem I personally wanted to solve with this.

# The Problem

We are mapping between DTOs and JPA Entities and use optimistic locking to detect concurrent modifications. That means: entities carry a ```version``` attribute, which needs to be unchanged compared to the current database value when a DTO comes back from the client with the modified data. Hibernate increases the version automatically during updates and verifies the expected value in the database.
However, Hibernate increases the version of an entity instance only during the *flush*. So when mapping an entity to a DTO, we need to ensure that any modifications to the entity have been flushed already.
To emphasise this: for us, MapStruct would bring in only half the value if we were not able to solve this problem within the generated code, but had to go back to AOP proxies again (loosing some of the performance gains and requiring a noticable amount of additional memory).

# The Requirements

Whenever any entity (for us, all of them are based on an abstract base class) is the source of a mapping and the target of that mapping is a DTO (again, we have an abstract base class mirroring the properties of the base entity), we want to call a specific method somewhere with the source entity as argument (for us: ```flushIfRequired( entity )```).
Similar to what I outlined in the config-inheritance issue, we have so many mapper classes and entity / DTO pairs, that we don't want to specifically need to add an annotation / configuration / decorator method for all those mapping methods. We need some automatic approach that works on matching the parameter types of the mapping methods. If someone forgot to configure that for one method, it could very well be that it is discovered only when using the application.

# Solution in the current PR

The problem is solved for us by the current PR, and it has been part of our production code at work for a long long time now. That's one of the reasons why I regularly rebased it... :wink:

This is, what it does:
It introduces two new annotations: ```@BeforeMapping``` and ```@AfterMapping```, to be applied to methods that are to be *called* from generated mapping methods. In the code, I used the term "lifecycle method" for such annotated methods.
Lifecycle methods are only picked up, if they are found within the scope of the mapper (i.e. implemented locally or in a super class, or declared (or implemented) in a *used* mapper. Their return-type must be ```void```.
In order for a call to such a lifecycle method to be added to the mapping method body, any parameter types of the lifecycle method must be assignable from parameters of the mapping method. By using ```@MappingTarget``` for a parameter of the lifecycle method, you require the instance to return to be passed in. ```@TargetType``` is also supported as an argument.
Currently, there is no restriction as to how many of such lifecycle methods may be found suitable for a mapping method. The current test demonstrates how all kinds of parameter combinations for ```@BeforeMapping``` and ```@AfterMapping``` methods are possible (including no-arg variants that would always be applied).
The idea is that you could add many kinds of cross-cutting aspects to your generated mappers, such as some kind of logging, or a generalized pre/post processing, a registration of created methods, automatic merging into a persistence-context, or whatever. All that without the need to use AOP proxies, which comes both with advantages and disadvantages of its own.

# Reasons why the PR wasn't merged, yet

My guess is that the main reason here is, again as with the config-inheritance, our different views on what should be expressed specifically at the mapping method, and what can be applied automatically using a defined set of rules (e.g. based on source/target type applicability). I think we all saw that both directions are valid and that a default behaviour should require a specific declaration at the mapping method (or at least the mapper type).
One other reason may be that I didn't put on that many restrictions, e.g. that I just put in *all* the matching lifecycle method calls and not just a single before- and a single after-mapping call - which could raise the question of the order in which the methods are called (which is deterministic, but needs a sentence to be explained). Maybe, I don't know. :wink:

# How do we continue?

The first thing would be that we agree if my recollection of why we havn't merged it yet is somehow right, or if I missed an important part. Then we can go on discussing how to either fix the current approach or how a new approach could look like.
What I could imagine is that we add an opt-in on the mapping method configuration that either says "apply any lifecycle methods that can be found automatically", or "apply that specific before-method" / "apply that specific after-method" (which might lead us back to the problem that referencing methods by their method name in strings might be cumbersome). Given the now available automatic and type-assignability-based mapping config inheritance, that would be something that can work for us. But that's for the later discussions.

@gunnarmorling, @sjaakd, I'd like to know what your positions are and if you have any suggestions on the direction we should proceed in.

Thanks!

**Comment by sjaakd** [comment]
@agudian Long story :smile:. I think your story is clear. I have reviewed it before. I think you have implemented my comments. 

Now, in the mean time we have additional selection means (such as qualifiers, jaxb selection). Factory methods and mapping methods have been aligned to these. Are you going to align your lifecycle methods as well? 
 
> Reasons why the PR wasn't merged, yet

I have the feeling we have in essence 2 more or less competing mechanisms. You could do stuff (although, in this case, requiring much more coding) with decorators. Next, decorators have (IMHO) shortcomings, one is pointed out in #183.  @gunnarmorling put his faith in the decorators :smile: . I'm not sure if you guys agree on my statement. If not, then this should not be a problem.

> The Requirements

Now on the use case. I've one for this as well. I work with Geographic Markup Language (GML). For objects that have a (geographic) location, the protocol demands a mandatory ID on the XML datatypes (JAXB beans). Now I generate this with an expression. Since there's no (counterpart) source object, I cannot use an external mapping method. Since the ID is  a String, I cannot use a factory method (it would apply everywhere). I'd like to 'control'  this ID in a global way, having some kind of naming convention (perhaps some prefix based on the type). This is not required right now, but I can imagine that something like this arises in the near future. A 'before' method would do this trick quite easily. 

Another use case is the one for which we introduced 'adder' method selection in the past: establishing child-parent, parent-child relations in entities. Adder methods might not always be available.

> How do we continue?

I like the idea you propose. In order to continue, it might be worthwhile to examine how our 'competitors' like Dozer and Orika (and perhaps also the .Net  mappers) have in place. 

If we decide the decorator mechanism and the proposed AOP mechanism are competing somehow, I think it would help clarity and ease of use if we make a choice. WDYT?

**Comment by agudian** [comment]
Merged and closed... :+1:
