### ISSUE TITLE
Use clear() / addAll(..) / putAll(..) for collection and map properties

### ISSUE THREAD

**Issue by agudian** [mapstruct/mapstruct#153]
We have the problem that when trying to map into existing (managed) entities using `@MappingTarget`, that collections are just replaced by new collection instances. Hibernate doesn't like that. 

Instead, we would like to have the following generated:

``` java
public void mapIntoEntity(CarDto source, @MappingTarget carEntity) {
    ...
    if ( carEntity.getPassengers() != null ) {
        carEntity.getPassengers().clear();
        carEntity.getPassengers().addAll( /* something with source.getPassengers() */ );
    } else {
        // what we do already:
        carEntity.setPassengers( new ArrayList<Passenger>( /* something with source.getPassengers() */ ) );
    }
}
```

Question is, how do we tell MapStruct to follow this approach. My straight-forward idea would be: do it, whenever we map into an existing target object (the `@MappingTarget` case).
Or, we do it always, as who-knows-what is created in the constructor of a target object or returned by a factory method (the collections might be already initialized with some special implementations).

What do you think?

Btw, that thing above should be doable with only modifying the templates, as all the information is already there.

**Comment by jannikweichert** [comment]
It's nearly 2 years later, but I'm struggling to do an update for an existing entity with some prefilled items in my collection. I'd really like to disable the clear all. In fact, explicitly defined a setter method and expected, that mapstruct would make use of it. Instead it uses the get and "bypasses" my setter-mechanism.

**Comment by gunnarmorling** [comment]
Hum, if a setter for the collection property is present I'd expect it to be used. Could you please open a new issue, showing the involved bean types and your mapper definition?

**Comment by gunnarmorling** [comment]
Ah, I might be wrong if we are talking about update methods via `@MappingTarget`. Not sure about the behaviour there out of my head, a complete example may help.

**Comment by jannikweichert** [comment]
I'll create a short Demo and upload it in my rep tomorrow - thanks for quick reply!

**Comment by marcoschulte** [comment]
The change to only calling clear if `@MappingTarget` is specified instead of always calling clear and keeping the collection breaks the possibility to use nested collections with JPA.

Assume the three entities `Grandparent`, `Parent` and `Child`. A mapping with `@MappingTarget` is defined for all entities in their mappers.

When mapping `List<Parent>` of `Grandparent`, clear is called on the list. Now all items are mapped using a returning mapping function and not the one with `@MappingTarget`. Now we are in the _"branch"_  where we won't clear lists anymore. Commit 8490231 introduced the behavior that `List<Child>` will be newly created, as we are not using a method specifying `@MappingTarget` to map each Parent object.
