### ISSUE TITLE
Add support for "adders" in combination with streams

### ISSUE THREAD

**Issue by sebastianhaberey** [mapstruct/mapstruct#1561]
Phew, this took me a while to figure out. Given a target entity like this:

```
public class Car {

  ...

  public Stream<String> getPartIds() {
    ...
  }

  public void addPartId(String partId) {
    ...
  }
}

```

MapStruct will not recognize the adder (regardless of collection mapping strategy) and will not generate the mapping code for the "partIds" attribute. Would it be difficult to implement this?

**Comment by sebastianhaberey** [comment]
I just had a go at the context-based approach you mentioned above. But I don't see how I could implement a generic context that applies to all our mapped classes, meaning that I'd probably have to write a considerable amount of repetitive code to accomodate each of our cases. 

Our current workaround would be to add a setter method like `setPartIds(Stream<String> partIds)` to all our target classes. Luckily, we have control over those. But I still think it would be great if MapStruct recognized adders here.

**Comment by filiphr** [comment]
Just had a quick look the fix is really easy we do https://github.com/mapstruct/mapstruct/blob/10f855fa9ec3fd8290cbb2536b352e2f1997d3c4/processor/src/main/java/org/mapstruct/ap/internal/model/common/Type.java#L626-L649 

so it is just a matter of adding a new if there to consider `Stream`. Will leave it for the community if someone wants to contribute to it, we can always help out here

**Comment by sebastianhaberey** [comment]
Ok cool I'd like to have a go at it if that's ok. I'll check out the repository and see if I can get the tests to run.

**Comment by filiphr** [comment]
Great. If you need any help you can find us in the MapStruct [gitter room](https://gitter.im/mapstruct/mapstruct-users) or just write here

**Comment by sebastianhaberey** [comment]
With your help I have located a few places that I think would have to be extended for this to work. The mapping of
 
an entity with methods Collection<X> getProperties / setProperties(Collection<X>) to / from
an entity with methods Stream<X> getProperties / addProperty(X)

works now. But when mapping 

an entity with methods Collection<X> getProperties + addProperty(X) to / from
an entity with methods Stream<X> getProperties + addProperty(X) 

i get:

for-each not applicable to expression type
  required: array or java.lang.Iterable
  found:    java.util.stream.Stream<java.lang.String>

@filiphr could you have a look at [my changes](https://github.com/sebastianhaberey/mapstruct/compare/master...sebastianhaberey:1561?expand=1) and see if you can spot the error? There's also a unit test  that will provoke the error when enabled.

**Comment by filiphr** [comment]
I forgot to get back to you @sebastianhaberey. Had a quick glance. The problem is in the `AdderWrapper` and `AdderWrapper.ftl`.

When mapping from `Stream` into an adder then we need to iterate over it and the current `AdderWrapper.ftl` does:

```
if ( ${sourceReference} != null ) {
    for ( <@includeModel object=adderType.typeBound/> ${sourceLocalVarName} : ${sourceReference} ) {
        ${ext.targetBeanName}.${ext.targetWriteAccessorName}<@lib.handleWrite><@lib.handleAssignment/></@lib.handleWrite>;
    }
}
```

In your case the `sourceReference` is the `Stream`. We probably need a new `StreamAdderWrapper` that would allow us to map from a `Stream` into a list using an adder.
