### ISSUE TITLE
Removing objects from collection

### ISSUE THREAD

**Issue by weilbaum** [mapstruct/mapstruct#1615]
When using MapStruct to _update_ a a JPA entity with data from a DTO, I'm configuring MapStruct to prefer adders. But it may happen (and it happens to me quite regularly) that there are less objects present on the collection of the DTO than on the entity's collection. I'd intuitively expect, that such surplus objects get removed from the entity's collection then, but that doesn't happen.

As far as I understood from #207, support for JPA "adders" has been implemented, but no support for "removers". I couldn't find anything on that topic in the documentation either.

Is there a way to achieve such behavior in MapStruct (with or without using removers), or would it make sense to you to add such a feature, if there is none yet?

---

Small sketch of what I want to achieve:

    +--------------------+-----------------------+
    |        DTO         |        Entity         |
    +--------------------+-----------------------+
    | myCollection[A, B] | myCollection[A, B, C] |
    +--------------------+-----------------------+

=> update (`C` gets removed from `myCollection` in the entity object, because it's not present in `myCollection` on the DTO anymore)

    +--------------------+
    |       Entity       |
    +--------------------+
    | myCollection[A, B] |
    +--------------------+

**Comment by sjaakd** [comment]
Removers are not implemented as such. In my own practice, I did write my own handwritten methods, since usually you need to detach C from the collection and A en B need to be updated with the new A and B. This is tricky business logic.

But we have a different solution.. Checkout this [example](https://github.com/mapstruct/mapstruct-examples/tree/master/mapstruct-jpa-child-parent).

**Comment by weilbaum** [comment]
Looks great! Thank you!

**Comment by sjaakd** [comment]
> Looks great! Thank you!

No problem!

**Comment by dirkniblick** [comment]
I know this is a very old thread, however I fail to see how the [solution above](https://github.com/mapstruct/mapstruct/issues/1615#issuecomment-424441403) solves this problem. The given solution creates a **new** entity rather than updating one.

In the initial example, `Entity` _already_ has relationships to A, B & C before using MapStruct to update it with `DTO`. I believe the goal here is the same as mine: When updating `Entity` with `DTO`, we want to _remove_ the elements **missing** from `DTO#myCollection` from `Entity#myCollection`. @sjaakd, how can we accomplish this with MapStruct? Do you have an example for updating (i.e., adding and removing) elements from a `@MappingTarget`?
