### ISSUE TITLE
Hickory warning during generation of mappers

### ISSUE THREAD

**Issue by sjaakd** [mapstruct/mapstruct#1644]
Warning:java: Supported source version 'RELEASE_6' from annotation processor 'net.java.dev.hickory.prism.internal.PrismGenerator' less than -source '1.8'

**Comment by filiphr** [comment]
Are you referring when you generate the code for MapStruct or within IntelliJ when the compilation for the mappers is created?

**Comment by sjaakd** [comment]
When generating mappers..

**Comment by sjaakd** [comment]
So it must be somewhere in the generated prisms..

**Comment by filiphr** [comment]
If I understood you properly, this is a bug in IntelliJ. See [IDEA-200481](https://youtrack.jetbrains.com/issue/IDEA-200481). IntelliJ is picking up the provided dependencies when doing the compilation.

I am going to close this one as there is nothing that we can do. We can't move the `hickory` dependency to the `annotationProcessorPaths` section of the maven compiler because the `@GeneratePrisms` annotations are part of the dependency, so we won't be able to use them. If you think that we could do something on our side reopen this issue.
