### ISSUE TITLE
Non-void update methods try calling build() on the @MappingTarget when a Builder is available

### ISSUE THREAD

**Issue by Chessray** [mapstruct/mapstruct#1681]
Given two Lombok POJOs

    @SuperBuilder
    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    public class Car {
        private String make;
        private int numberOfSeats;
        private CarType type;
    }

and

    @Data
    @SuperBuilder
    @NoArgsConstructor
    @AllArgsConstructor
    public class CarDto {
        private String make;
        private int seatCount;
        private String type;
    }

and a Mapper

    @Mapper
    public interface CarMapper {
        @Mapping(source = "numberOfSeats", target = "seatCount")
        CarDto carToCarDto(Car car);

        @Mapping(source = "numberOfSeats", target = "seatCount")
        CarDto updateFromCar(Car car, @MappingTarget CarDto dto);
    }

the generated code for the update method looks like this:

    @Override
    public CarDto updateFromCar(Car car, CarDto dto) {
        if ( car == null ) {
            return null;
        }

        dto.setSeatCount( car.getNumberOfSeats() );
        dto.setMake( car.getMake() );
        if ( car.getType() != null ) {
            dto.setType( car.getType().name() );
        }

        return dto.build();
    }

The setter calls are correct, but the last line should simply read `return dto;`. If the update method is declared as `void`, the generated code compiles fine.

Noticed in version 1.3.0.Beta2.

A complete example project is available [here](https://github.com/Chessray/mapstruct-examples/tree/master/bug-demo).

**Comment by sjaakd** [comment]
However pecular, I think we never defined the exact behavior of update methods that also return an object. Any solution should start there. The current behavior is (I presume) that we return the `@MappingTarget` annotated parameter.

 Honestly, I always struggled with these kind of methods. Probably we should only return an (fresh) object when the `@MappingTarget` is null (otherwise null). Only then the user could conclude that this is created in the mapping method.  Anyway, calling null on an object which is immutable is wrong.

**Comment by filiphr** [comment]
@sjaakd we don't do a null check for the `@MappingTarget` which means that if you pass `null` there will be an NPE, which is fine if you ask me. On top of that we always return the `@MappingTarget` back.

This is clearly a bug and needs to get fixed. I'll get on it, it is quite easy to do it actually.
