### ISSUE TITLE
How to ignore method for collection creation

### ISSUE THREAD

**Issue by bostandyksoft** [mapstruct/mapstruct#1725]
Mapstruct used my own parameters-free method as factory for List (instead of constructor)

I tried to map some objects tree, that should built level by level. So i have a method for hardcoded root nodes and another methods, that used for mapping entities to nodes. So i have a method for generation list of root names, and abstract methods for mapping.

```
@Mapper
public abstract class TestMapper {

public List<Name> rootNames() {
    List<Name> names = new ArrayList<>();
    names.add(Name.build("Homer"));
    names.add(Name.build("Marge"));
    return names;
}

@Mapping(target = "name", source = "name")
public abstract Name childrenName(FullName simpson);

public abstract List<Name> childredNames(List<FullName> children);

public static class Name {
    private String name;

    public static Name build(String value) {
        Name name = new Name();
        name.setName(value);
        return name;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}

public static class FullName {
    private String name;
    private String lastName;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
}
}
```

So in generated code "childrenNames" looks like @Override public List childrenNames(List children) { if ( children == null ) { return null; }

```
List<Name> list = rootNames();
    for ( FullName fullName : children ) {
        list.add( simpsonName( fullName ) );
    }

    return list;
}
```

How i can mark my rootNames method as ignored for mapping?

Best regards. Alexey

**Comment by chris922** [comment]
When should the `rootNames()` method be called? If it should not be called internally by the mapper I would suggest to move this to a different place, as the purpose of a mapper is not to create objects with predefined values (because this is not a mapping).

It looks like the `rootNames()` method will be used as an object factory and I don't know a way to ignore this, see the reference guide: http://mapstruct.org/documentation/dev/reference/html/#object-factories
Just one idea: Maybe you can annotate `rootNames()` with `org.mapstruct.Named`..

Anyway.. maybe it is a good enhancement to make it possible to ignore such methods or make `@ObjectFactory` by-default mandatory (or configurable if it is mandatory or not).
I think we already had some discussions in this direction in an issue regarding generated JAXB Object Factories.. or @sjaakd ?

**Comment by filiphr** [comment]
You are right @chris922 using `org.mapstruct.Named` will make this factory an opt in factory and thus making it ignored. 

@bostandyksoft I think that you also created [this](https://stackoverflow.com/questions/54745311/how-to-ignore-method-for-collection-creation) StackOverflow question.

@chris922 do you want to post your answer there as well?

I am going to close this as this is more of a question than an issue within MapStruct
