### ISSUE TITLE
Code generation not works when inherits from another project

### ISSUE THREAD

**Issue by RaphaelCavalcante** [mapstruct/mapstruct#1762]
Hi, i don't know if this is a question or a bug or a not implemented future feature but, i'm using Mapstruct to create a simplified generic project and while inside the same project the code generation works fine using generics like:

`public interface GenericMapper <T, D>`

`@Mapper public interface MainMapper extends GenericMapper <Entity, DTOclazz>`

The problem comes when i build the project .jar and use it as a dependency, the dependent project builds fine but the code implementations for the Mappers are not generated anymore.

I'm doing the same inheritance as mentioned above.

Can anyone help me to solve this issue?
thanks.

**Comment by filiphr** [comment]
@RaphaelCavalcante I am not quite following the issue. Are you saying that the `MainMapper` is in another project and that you want MapStruct to generate the mappers in a project that has the project from the `MainMapper` as a dependency? If that is the question then the answer is no. This is not possible due to the fact that MapStruct is an annotation processor. This means that it generates the mappers during the compilation phase of the project.

If this was not the question, then perhaps you can help us out and create a git repository that would display the problem you are seeing so we can analyse it better

**Comment by filiphr** [comment]
Closing due to no response. Once we get a response we can reopen it
