### ISSUE TITLE
Inconsistent argument naming in a shared method

### ISSUE THREAD

**Issue by JohnnyKikman** [mapstruct/mapstruct#1793]
In our project we've got two bean mapper interfaces (let's call them `FooMapper` and `BarMapper`) that inherit from a base interface (e.g. `BaseMapper`) which has mapping method definitions for several nested beans within `Foo` and `Bar`.
For example, `BaseMapper` looks like this:
```
public interface BaseMapper {
    @Mappings({
        @Mapping(target = "a", expression = "java(someComplexLogic(nested.getANotString()))")
    })
   NestedB mapNested(NestedA nested);
}
```
And its subclasses that share the same mapping method:
```
public interface FooMapper extends BaseMapper {
    @Mappings({
    ...
        @Mapping(target = "nested", source = "nestedA")
    ...
    })
   FooB mapFoo(FooA foo);
}
```
```
public interface BarMapper extends BaseMapper {
    @Mappings({
    ...
        @Mapping(target = "nested", source = "nestedA")
    ...
    })
   BarB mapBar(BarA foo);
}
```
Please note that I had to use `expression` clause in `BaseMapper` and referred to the mapped object as `nested` due to some complex conditional mapping involved.

Now the problem is - <i>sometimes</i> (and that's the main point - about inconsitency) after compilation this method is implemented differently in `FooMapperImpl` and `BarMapperImpl` - to be precise, in one the base entity argument might be named `nested` as defined in the interface, but in the other one it suddenly gets renamed to `arg0`.

Is naming constistency when using shared mapper methods not guaranteed and should I fall back to write explicit `default` method in this case? Or is this a bug needed to be fixed? Thanks in advance.

**Comment by JohnnyKikman** [comment]
<i>Additional info:</i> It looks like the problem occurs when I change either `FooMapper` or `BarMapper` and then try to build project with only this one change using Idea - then the implementation of `mapNested` has its argument renamed to `arg0` and the error occurs. If I rebuild the whole project, both `FooMapperImpl` and `BarMapperImpl` have `mapNested`'s argument name back to `nested`. Still, I wonder if it qualifies as a bug.

**Comment by chris922** [comment]
Is the `BaseMapper` stored in a different artifact / JAR file? `arg0` sounds like the real variable name is not available for MapStruct and thus the compiler falls back to `arg0`.

What I don't get: Do you have any compile issues when it is named `arg0`? Maybe a short extract from the generated mapper highlighting the argument that gets different names would be helpful (and in case there is a compile issue this part as well).


PS: You don't need to use an expression as this is error-prone, take a look at [qualifiers](http://mapstruct.org/documentation/stable/reference/html/#selection-based-on-qualifiers) -> annotate the `someComplexLogic` method with e. g. `@Named("complexLogic")` or an own defined qualifier annotation and use instead of the `expression` just `qualifiedBy`

**Comment by filiphr** [comment]
What you are explaining @JohnnyKikman is exactly what @chris922 said. If you are seeing something being renamed to `arg0` it means that the mappers are in different modules. 

If you are on Java 8 you could pass the `parameters` flag to the compiler, this flag would not rename the names of the parameters in your functions.

I am closing this, if you think that there is something that we could do, please let me know
