### ISSUE TITLE
How can i map an enum to non-enum value.

### ISSUE THREAD

**Issue by JokerSun** [mapstruct/mapstruct#1795]
I want to map enum to no-enum value, but i don't got any way, is there any solution?
Customized mapper is absolutely solution but not automatic.

```
// this code is suck
@Mapper(componentModel = "spring")
public interface EnumMapper {

	default Integer enumToInt(Status status) {
		switch (status) {
			case OK:
				return 1;
			case FAIL:
				return -1;
			default:
				return 0;
		}
	}
}
```

```
// this code is perfect
@ValueMappings({
	@ValueMapping(source = Status.OK, target = StatusCode.OK),
	@ValueMapping(source = Status.FAIL, target = StatusCode.FAIL),
	@ValueMapping(source = MappingConstants.ANY_REMAINING, target = StatusCode.UNKNOWN)
})
Integer enumToInt2(Status status);
```

**Comment by filiphr** [comment]
In theory we could reuse something that we are doing for `Mapping#defaultValue` and `Mapping#constant` and support only constant expressions and primitives. Having said this, I am not entirely certain that the code you wrote is that bad and that much different than the one you would need to do with MapStruct.

@JokerSun just FYI you don't have to make the `EnumMapper` a mapper. That can be a simple class as well. For example:

```java
public interface StatusMapper {

    static Integer enumToInt(Status status) {
        switch (status) {
	    case OK:
	        return StatusCode.OK;
	    case FAIL:
	        return StatusCode.FAIL;
	    default:
	        return StatusCode.UNKNOWN;
	}
    }
}
```

@sjaakd, @chris922 what do you think about this?

@JokerSun if the team agrees would you be interested in providing a PR for this.

**Comment by chris922** [comment]
> In theory we could reuse something that we are doing for `Mapping#defaultValue` and `Mapping#constant` and support only constant expressions and primitives.

Something like this?

```java
@ValueMapping(source = Status.OK, constant = "1")
```

Sounds fine for me and as we are allowing something very similar for `@Mapping` it is imho also a consistent approach.

**Comment by filiphr** [comment]
Was thinking to do that directly into `ValueMapping#target` in order not to remove the mandatory `target`.

Something like:

```java
@ValueMapping(source = Status.OK, target = "1")
```

@JokerSun what @chris922 said actually showed that you can't really use `StatusCode.OK` if that is an integer since the `target` or maybe even `constant` would be a string and not an int. Therefore I am not 100% certain that I would suggest someone to use something like this. Usually you want constants to have some name and have some meaning (which they do with `StatusCode`). I am also not inclined towards adding `constantInt`, `constantLong`, etc. I think that this might bloat the API and not bring a lot of value.

**Comment by chris922** [comment]
Hmm as target is already used there as a value and not an attribute name reusing it sounds also fine for me! Using an int constant probably would work with a small workaround: "" + StatusCode.OK
