### ISSUE TITLE
Multiparameter mapping using expressions generates method that fails to call all relevant parameters

### ISSUE THREAD

**Issue by IDoCodingStuffs** [mapstruct/mapstruct#1803]
Also refer to:
https://stackoverflow.com/questions/55959943/mapstruct-expression-mappings-using-multiple-source-parameters

This is version 1.3.0.Final

```
@Mapping(target = "myWrapperObject.myListObject",
        expression = "java(myListMap.get(keyParent.getKey()))")
    @Mapping(target = "myOtherObject", expression = "java(myOtherClassList.add(myOtherObject))")
    MyFinalClass mapStuff(Map<String, List<MyClass>> myListMap, MyOtherClass keyParent);
```

Using this code generates code that looks like this under impl:
```
 protected void stringListMapToMyWrapperClass(Map<String, List<MyClass>> map, MyWrapperClass mappingTarget) {
        if ( map == null ) {
            return;
        }

        mappingTarget.setMyListObject = myListMap.get(keyParent.getPropertyKey()) );
    }
```

There are actually two issues in the code above, see #1802 for the more glaring issue with map vs myListMap. For this issue, see how keyParent is passed as a source parameter for the mapping and is needed for the method generated. But it is never passed as a parameter and still called

**Comment by filiphr** [comment]
You've provided more information that on StackOverflow. Please do not create multiple issues and ask on StackOverflow in the same time.

If you ask me this works as designed. When using nested target with expressions there is no way for us to know which source you are using so everything is passed. On top of that I see that you are relying on some generated variables from MapStruct (`myOtherClassList`). I would suggest that instead of using such complex expressions to use `@AfterMapping` or some custom method that would do the mapping.

How did this work in 1.2.0.Final?

I am going to close this one as I don't really see what we can do about this. Maybe you can provide some examples for how you expect this to look like.
