### ISSUE TITLE
nullptr in 3.0 due to result type definition.

### ISSUE THREAD

**Issue by sjaakd** [mapstruct/mapstruct#1821]
Internal error in the mapping processor: java.lang.NullPointerException               at org.mapstruct.ap.internal.model.BeanMappingMethod$Builder.build(BeanMappingMethod.java:201)                 at org.mapstruct.ap.internal.processor.MapperCreationProcessor.getMappingMethods(MapperCreationProcessor.java:373)                  at org.mapstruct.ap.internal.processor.MapperCreationProcessor.getMapper(MapperCreationProcessor.java:149)                  at org.mapstruct.ap.internal.processor.MapperCreationProcessor.process(MapperCreationProcessor.java:120)     at org.mapstruct.ap.internal.processor.MapperCreationProcessor.process(MapperCreationProcessor.java:74)       at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:283)          at org.mapstruct.ap.MappingProcessor.processMapperTypeElement(MappingProcessor.java:263)               at org.mapstruct.ap.MappingProcessor.processMapperElements(MappingProcessor.java:221)       at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:152)

**Comment by sjaakd** [comment]
Reproducer in attached PR.

**Comment by Captain1653** [comment]
@sjaakd I have reproduced this exception. The problem is here
![null pointer](https://user-images.githubusercontent.com/4740207/64076357-8ea3b980-cccc-11e9-934a-93e13a619d01.png) . Our result types aren't assignable. If we will remove this bad line `BeanMappingPrism.getInstanceOn( method.getExecutable() ).mirror` then we will receive message from compiler something like that:

**org.mapstruct.ap.test.mypackage.Issue1821Mapper.Target not assignable to: org.mapstruct.ap.test.mypackage.Issue1821Mapper.ExtendedTarget.**

Is it acceptable for us? Should I do PR?

**Comment by sjaakd** [comment]
While many parameters of `@BeanMapping` can be inherited, it does not make sense to inherit the result type. 

Your proposal does not take away the cause of the problem, it solves the symptoms. The solution is not to copy the resultType when inheriting. I guess that's somewhere done in `MappingOptions` I guess.

**Comment by sjaakd** [comment]
done..  resolved by PR #1822
