### ISSUE TITLE
Expression does not work with qualifiedBy

### ISSUE THREAD

**Issue by dekelintelematics** [mapstruct/mapstruct#1851]
According to the javadoc on `expression()`:
>This attribute can not be used together with source(), defaultValue(), defaultExpression() or constant().

Either the behaviour should be updated to allow use with `qualifiedBy()`, or the doc should be updated to show that it doesn't.

**Comment by filiphr** [comment]
The reason for not mentioning that is because those methods `source()`, `defaultValue()`, `defaultExpression()`, `constant()` and `expression()` are used to control the source for the target.

The reason why it is not mentioned because `expression()` will take the value as is and everything else is ignored. It will not make sense to use `qualifiedBy()` here. Perhaps we can update the documentation on `qualifiedBy()` that it would only matter for `source()`. Would you like to prepare a PR for updating the Javadoc.

**Comment by dekelintelematics** [comment]
Sure, I'll probably do that on the weekend, thanks for the communication @filiphr 

@dekelpilli
