### ISSUE TITLE
Replace @Mapper.componentModel from string to enum

### ISSUE THREAD

**Issue by Captain1653** [mapstruct/mapstruct#1877]
@sjaakd @filiphr When I use Mapstruct on my work sometimes I can make mistake, when I write @Mapper.componentModel as string. Maybe it will be better to replace it on enum? I have prepared draft PR. If you think we need it, then I will fix documentation and ext.

**Comment by filiphr** [comment]
@Captain1653 the reason why it is a `String` is because we want to allow people to provide their own [`AnnotationBasedComponentModelProcessor`](https://github.com/mapstruct/mapstruct/blob/master/processor/src/main/java/org/mapstruct/ap/internal/processor/AnnotationBasedComponentModelProcessor.java) and use their own strings.

The IntelliJ plugin (not sure about the eclipse one) allows autocomplete for the known `componentModel`(s).

Last thing is that if we replace it with an enum this would be a breaking change and this is something that we don't really want to do.

**Comment by Captain1653** [comment]
Ok, I agree with it.
