### ISSUE TITLE
NullPointerException on List<SomeType> + lombok Builder.

### ISSUE THREAD

**Issue by Rouche** [mapstruct/mapstruct#1957]
- [x] Is this an issue (and hence not a question)? 

Hi,

When generating list conversion using Lombok builder, it creates something like this.
```
        List<SomeType> someTypeList = rootType.someTypeList( rootType );
        convertedType.someTypes( someTypeToConvertedSomeTypeCollection( someTypeList ) );
```
But `someTypeList` can be null, and calling the list setter of lombok's builder uses `addAll()` wich creates a NullPointerException
```
    public boolean addAll(Collection<? extends E> c) {
        Object[] a = c.toArray(); // Here
        ...
    }
```

Could it be possible to test the property before, like:
```
        List<SomeType> someTypeList = rootType.someTypeList( rootType );
        if(someTypeList != null) {
            convertedType.someTypes( someTypeToConvertedSomeTypeCollection( someTypeList ) );
        }
```
I guess i could pull request that one. Never went in MapStruct code tough.
Thanks.

**Comment by filiphr** [comment]
@Rouche can you please share the code that creates this? The source and target classes annotated with Lombok?

I would say that this is a bug in Lombok. It should be possible to set a `null` value via a setters.

Anyways, have you looked into `Mapper#nullValueCheckStrategy` with `NullValueCheckStrategy#ALWAYS`? That would create the expected code from MapStruct by always creating a null check before setting the value.

**Comment by Rouche** [comment]
It took a lot of time to recreate the test because i was unable to reproduce until i realized it was a JSON deserialized object. So the Default constructor was used and not the builder. (Builder initialize lists to emptyList()) It also needs to be a list inside another mapped object. Root object's lists are null safe.
There you go: https://github.com/Rouche/issue1957

**Comment by filiphr** [comment]
Thanks for taking the time to create an example @Rouche. 

The problem is in the way the builder "setter" works for the `Issue1957Other#someNulls`. That field is annotated with `@Singular`. So there is a single element in the builder that just adds everything into the field.

The code generated by Lombok looks like

```
public Issue1957Other.Issue1957OtherBuilder someNulls(Collection<? extends OtherClazz> someNulls) {
    if ( this.someNulls == null ) {
        this.someNulls = new ArrayList<OtherClazz>();
    }
    this.someNulls.addAll( someNulls );
    return this;
}
```

Since this is a constraint by the builder API, you'll have to use `NullValueCheckStrategy#ALWAYS`.

In case you don't want to do that for the entire mapper you can use
```
@Mapping( target = "someNulls", nullValueCheckStrategy = NullValueCheckStrategy.ALWAYS)
```

I am going to close this issue since in the end it is a matter of configuring the mapper with the correct properties.
