### ISSUE TITLE
Different behaviour for NullValuePropertyMappingStrategy.SET_TO_DEFAULT

### ISSUE THREAD

**Issue by VladSergeev** [mapstruct/mapstruct#1965]
Hello, I found a strange behaviour of that strategy for mapper.
I made simple project  to illustrate that behaviour:
https://github.com/VladSergeev/mapstruct-test-examples

There is a mapping of List and Set from one dto to another.
Mapper has configuration:
`@Mapper(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.SET_TO_DEFAULT)`

I expect that in target dto if null value in source then empty collection would be sent.
That is an example of generated mapper impl:
```
@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2019-11-08T16:40:50+0300",
    comments = "version: 1.3.1.Final, compiler: javac, environment: Java 11.0.2 (Oracle Corporation)"
)
public class MyMapperImpl implements MyMapper {

    @Override
    public ToDto to(FromDto test) {
        if ( test == null ) {
            return null;
        }

        ToDto toDto = new ToDto();

        List<String> list = test.getTest2();
        if ( list != null ) {
            toDto.setTest2( new ArrayList<String>( list ) );
        }
        Set<String> set = test.getTests();
        if ( set != null ) {
            toDto.setTests( new HashSet<String>( set ) );
        }

        return toDto;
    }
}
```

Can you clarify behaviour of that configuration in that case? Is it a bug or i missed something?

I tried `NullValueMappingStrategy` and it works as I expect only for version 1.2.0.FINAL, on version 1.3.*.FINAL it does not work.

**Comment by sjaakd** [comment]
@VladSergeev funny. I just answered a similar issue. Have a look at #1966 .. There's your solution  I guess.

Background: `NullValueCheck` was never intended to set an empty set but only perform checking. This was fixed in 1.3 (I guess you could find it in the release notes somewhere). For update mappings we introduced `NullValuePropertyMapping`..  (these are methods with the `@MappingTarget`). 

The end result has been some confusion. Sorry for that.

We are considering to redesign this part in 2.0 and have it consistent in naming. There's also an issue for that somewhere. 

Hope you this answer helps you. I'll proceed to close this one. If you feel there's still an issue let us know.
