### ISSUE TITLE
Exceptions thrown by used Mappers aren't properly handled in the generated code

### ISSUE THREAD

**Issue by HuismanErik** [mapstruct/mapstruct#198]
The code generated by Mapstruct doesn't handle checked Exceptions which are thrown by used Mappers. I would like to have the possibility to add these checked exceptions to throws clause of the Mapper methods. So the exception will be thrown to the top level of the mapping method.

**Comment by gcv-javier** [comment]
Hello:

I found this old issue, but I don't know if it's been resolved, because it was a while ago.

For the moment I can see that the exception thrown by a mapping method:

`  public Blob map(byte[] value) throws SQLException {
    return new SerialBlob(value);
  }`

and used in the interface with @Mapper(uses= DomainMapperUtil.class)

creates the implementation:

`try {
            importMetadata.setFile( domainMapperUtil.map( importMetadataMultipartFileBytes( importMetadata ) ) );
        }
        catch ( SQLException e ) {
            throw new RuntimeException( e );
        }`

so the problem still persist, but maybe there is an option in the mapping to change it.

Thank you in advance.

**Comment by filiphr** [comment]
@gcv-javier this issue was closed and resolved more than 6 years ago. If you think that something is not working correctly please open a new issue and provide an entire example. Please try with the last released version as we fixed some things in this area there.

FYI in order to not to rethrow a runtime exception your method should throw `SQLException` as well.
