### ISSUE TITLE
Use default timezone rather than UTC when converting date types

### ISSUE THREAD

**Issue by lscelestino** [mapstruct/mapstruct#2087]
I personally believe this is an improvement rather than a bug. It took a while for me to figure out what was going on, but I was mapping a DTO to an Entity `class` and (by mistake) DTO attribute happened to be an instance of `java.util.Date` whereas Entity counterpart attribute was an instance of `java.time.LocalDateTime` instead. I have set application's default timezone to mine `America/Sao_Paulo`, but when persisting data, for some reason, it was always converted to UTC. At first I thought it was a database setting I had to do, but then, after some deeper investigation, I finally noticed the mistake was that generated mapper was actually overriding my default timezone configuration with UTC. When date types match, everything is just okay. 

Actual
`trip1.setDepartureTime( LocalDateTime.ofInstant( trip.getDepartureTime().toInstant, ZoneId.of( "UTC" ) ) );`

Expected
`trip1.setDepartureTime( LocalDateTime.ofInstant( trip.getDepartureTime().toInstant, ZoneId.systemDefault() ) );`

**Comment by filiphr** [comment]
In the documentation it is written that the UTC zone is used when mapping between `LocalDateTime` and `Date`. Changing this will be a breaking change.

However, you can easily provide your own conversion method that would use the system default zone. MapStruct will then use your method instead of the default one.
