### ISSUE TITLE
Mapping multiple fields into collection

### ISSUE THREAD

**Issue by fenuks** [mapstruct/mapstruct#2104]
Let's say I have 
```java
class A {
   private String fieldA;
   private String fieldB;
}
```
and I'd like to map it to
```java
class B {
    private Collection<String> fields;
}
```

I think it would be natural to be able to define mapper as:
```java
@Mapper(unmappedSourcePolicy = ReportingPolicy.ERROR)
public interface Mapper {
    @Mapping(source = "fieldA,fieldB", target = "fields")
    B map(A obj);
}
```
or perhaps make source accept multiple arguments, which would allow to write it as `@Mapping(source = {"fieldA", "fieldB"}, target = "fields")`, and would make easier to ignore multiple fields at once `@Mapping(source = {"fieldA" ,"fieldB"}, ignore = true)` (or with first form, `@Mapping(source = "fieldA,fieldB", ignore = true)`).

**Comment by filiphr** [comment]
Ignoring multiple source fields at once can be done via `BeanMapping#ignoreUnmappedSourceProperties`. We have done this on purpose because we didn't want to make `Mapping#target` an optional value in the annotation.

Regarding the original request, mapping multiple fields into a collection. I am afraid that I will have to reject this request. I don't think that the complexity of the feature justifies adding it to the library. We strive for covering 80% of the cases and we offer really flexible hook mechanisms that user can use to write their own custom mapping.

In this situation this can be done really easily in an `@AfterMapping`.

e.g.

```
@Mapper(unmappedSourcePolicy = ReportingPolicy.ERROR)
public interface Mapper {
    @BeanMapping(ignoreUnmappedSourceProperties = { "fieldA", "fieldB" }
    @Mapping(target = "fields", ignore = true)
    B map(A obj);

    @AfterMapping
    void mapField(@MappingTarget B b, A obj) {
        Collection<String> fields = new ArrayList<>();
        if (obj.getFieldA() != null) {
            fields.add(obj.getFieldA());
        }

        if (obj.getFieldB() != null) {
            fields.add(obj.getFieldB());
        }

        b.setFields(fields);
    }
}
```

**Comment by fenuks** [comment]
Sorry for late answer, and I completely understand your reasoning. And thank you for detailed example how to do it the other way. :)
