### ISSUE TITLE
Conditional mapping

### ISSUE THREAD

**Issue by Desislav-Petrov** [mapstruct/mapstruct#2107]
Hi,

I've come across an interesting use case that doesn't seem to be directly supported by mapstruct - conditional mapping.

More precisely, suppose you have a target object where you want to only map given attributes if a condition is true.

To put a specific example in place:

(Source class):
Employee:
  residenceCountry;
  taxIDNumber;

(Target class) EmployeeData:
  employeSocialSecNumber;
  employeeNationalInsuranceNumber:

We would like to map the source taxIDNumber to
1) employeSocialSecNumber if residenceCountry == US
2) employeeNationalInsuranceNumber if residenceCountry == UK

The proposed extension would look like this:

**Option 1**
@Mapping(source = "taxIDNumber", target="employeSocialSecNumber", condition="residenceCountry.equals("US"))
@Mapping(source = "taxIDNumber", target="employeeNationalInsuranceNumber", condition="residenceCountry.equals("UK"))

**Option 2**
@Mapping(source = "taxIDNumber", @ConditionalTarget({
                @Condition(target="employeeNationalInsuranceNumber",
                                    condition="residenceCountry.equals("UK")),
                @Condition(target="employeSocialSecNumber",
                                    condition="residenceCountry.equals("US")));

We can leave null to be the default behavior if no condition is matches.

Does the community think such a feature would be useful and if so which syntax of the two we think is cleaner? I personally favour 2 to avoid the repetition. I'm happy to start a PR if this feature gets a blessing.

Thanks,
Des

**Comment by Desislav-Petrov** [comment]
Hi,

It would be great if somebody could comment on that feature - there would be a non-trivial amount of work involved so I'd like to get a green light from maintainers first if possible.

Thanks,
Des

**Comment by filiphr** [comment]
Thanks for the suggestion @Desislav-Petrov. Someone recently requested something similar in #2051 and we also have #2084 for custom presence check methods.

Actually #2051 is exactly the same as your **Option 1** proposal, it also uses the expression support we have `java(...)`. I prefer that one because it keeps the `target` in `@Mapping` being mandatory and this is something that we don't want to check.

Can you please sync @pherklotz because they also said they want to provide a PR for this.

I will close this issue in favour of #2051 and add some more information there
