### ISSUE TITLE
Field starting with "add" not mapped with Lombok builder

### ISSUE THREAD

**Issue by classnotfound** [mapstruct/mapstruct#2115]
I have an issue to map a field starting with "add" (addInfo in my case), the field is simply not mapped, I use Maptstruct (1.3.1.Final) with Lombok (1.18.10) and its builder feature.

If I try to force the mapping using annotation:

    @Mapping(source = "addInfo", target = "addInfo")

I get this error:

> AddressMapper.java:[32,20] Unknown property "addInfo" in result type net.classnotfound.dto.AddressDto. Did you mean "null"?

But it works when I remove the `@Builder` annotation which make me thinking that it may be  related to this issue #1799?

**Comment by filiphr** [comment]
Can you please share your `AddressDto`? Have you tried with 1.4.0.Beta1?

**Comment by classnotfound** [comment]
I made a small project reproducing the issue.
It is available [here](https://github.com/classnotfound/field-mapping)

You'll find a Foo and FooDto classes and a unit test which shows the issue.

And the issue is still present in 1.4.0.Beta1 version.

**Comment by filiphr** [comment]
Thanks a lot for the project. It helped me understand the problem a bit better.

This is a tricky one. MapStruct has the concept for setters and adders. When using the normal Java Bean convention the setter is `setAddInfo` and we can easily detect the `addInfo`. However, when using fluent setters it is more difficult. Imagine the following:

```
public class Builder {

    Builder address(String address) {
        //...
    }

    Builder addInfo(String addInfo) {
        //...
    }
}
```

We have an explicit check where we treat `address` as a fluent setter, but we treat `addInfo` as an adder for `info`. We explicitly check if the 4th character is uppercase to determine whether a fluent setter is an adder or setter.

This is a direct consequence of #1449. Currently I have no idea how we can clearly determine whether the method is an adder or setter based on how it looks like. 

I am closing this issue as "won't fix" if you have an idea how we can support both then please let us know and we can iterate over it.

## Side note

IMHO using `addInfo` for setting a single `addInfo` property is not an intuitive API, since I as a user would expect to add an info to the builder, and not to have a single property named `addInfo`.

**Comment by NicoStrecker** [comment]
Wouldnt it be possible to check if there is a field called addX and then check if there is a @Builder annotation that ensures that the Builder.addX is not an adder and rather a setter?

**Comment by filiphr** [comment]
@NicoStrecker we are not relying on the available fields, we are relying on the Java Bean getter / setter style methods and also for fluent setters. We do not have plans to change this

**Comment by NicoStrecker** [comment]
> @NicoStrecker we are not relying on the available fields, we are relying on the Java Bean getter / setter style methods and also for fluent setters. We do not have plans to change this

Thx for the clarification
