### ISSUE TITLE
How to use it in IntelliJ Idea with ECJ and LOMBOK

### ISSUE THREAD

**Issue by Robot-L** [mapstruct/mapstruct#2116]
I like to compile with ECJ（Eclipse Compiler for Java） in IDEA, because it will compile all the files when it encounters a compilation error, but I find that MapStruct and Lombok seem to be incompatible. I can run normally when I use each, but not together. Too.
The settings are as follows:
1. Use ECJ
![](https://tva1.sinaimg.cn/large/007S8ZIlgy1gfp9wooxxmj31300osjvp.jpg)

2. Enable Annotation Processors
![image](https://user-images.githubusercontent.com/16471200/84457005-1b37cb00-ac94-11ea-997f-2b0aad26da87.png)

3. Set compile options（for Lombok）
![](https://tva1.sinaimg.cn/large/007S8ZIlgy1gfpa0o6ibdj31ki0b4aas.jpg)

Then when I build project I get an error：
![image](https://user-images.githubusercontent.com/16471200/84457284-dceedb80-ac94-11ea-9ba6-918ec50fc99c.png)

I use gradle, build.gradle content is as follows：
![image](https://user-images.githubusercontent.com/16471200/84457750-09efbe00-ac96-11ea-8e31-ea7174e1eadb.png)

If I don’t configure Lombok (the third step above), just use MapStruct, then there is no problem。

By the way, If I build with gradle, it is ok, but gradle seems to be unable to use ECJ😕

How do i deal with it？

**Comment by filiphr** [comment]
I know that there are some special ways to make Lombok work with Eclipse (such as running Eclipse with a custom Lombok agent). 

I don't think that there is something that we can do from MapStruct side to make this work. We've also had an issue related to the similar error that we fixed in 1.4.0.Beta1. Please try with that version as well.
