### ISSUE TITLE
unmappedTargetPolicy for @BeanMapping

### ISSUE THREAD

**Issue by chris922** [mapstruct/mapstruct#2132]
In case you want to have a different unmapped-target-policy just for one mapping right now you have to go and move it to a dedicated class setting the `@Mapper` config accordingly.

I think in the past there was a similar issue, but I can't find a solution to it... I expected that `@BeanMapping` has a `unmappedTargetPolicy` property to change it just for this mapping.

Reason to have this:
Sometimes you map to objects you don't control and they've got a lot properties. To prevent defining a lot ignore `@Mapping`s and having troubles upgrading the external dependency that might introduce new targets it could make sense to decide that the unmapped-target-policy should be set to `IGNORE` - but just for this mapping and not for the others.

This doesn't sound like a big deal to add this.. but I would like to get some feedback from you guys @filiphr and @sjaakd if you also think this is helpful before I will start on it.
Maybe there is already a good way to do this so that we don't need this new option at all.

**Comment by filiphr** [comment]
With the current way our current API is (everything in the annotation) I don't think that there is another way.

I think that this is a good idea @chris922. With some of the refactorings for 1.4 from @sjaakd it is even easier to add this. 

Do you want to create a PR for this @chris922?

**Comment by mjustin** [comment]
I have a similar use case where I have a bidirectional mapper (similar to the bidirectional `CarMapper` example in the [reference guide](https://mapstruct.org/documentation/stable/reference/html/#inverse-mappings)) where one object is in my control, and the other is an external model.  The external model has a ton of extra properties that I don't want to set, and I don't want my compilation to break if I upgrade to a version in the future that adds even more properties to it.  Conversely, I _do_ want my compilation to break if my own mapper ever misses setting one of the properties on my own object, since I care very much that everything be either mapped, or explicitly and intentionally unmapped.

**Comment by LukeLaz** [comment]
I miss this feature a lot. While refactoring big legacy codebase from Dozer to Mapstruct there was a number of occasions where I had to decide whether to move a method to it's own mapper or list a bunch of properties as ignored (by default we have `unmappedTargetPolicy = ERROR` for all mappers). Both were suboptimal solutions and I missed a possibility to override unmappedTargetPolicy just for one method. My employer gave me time to work on this, is it OK to introduce PR?

**Comment by filiphr** [comment]
Yes it is ok to work on a PR for this @LukeLaz. I'll assign the issue to you.

Let us know if you have some questions.

**Comment by LukeLaz** [comment]
@filiphr Is it along the lines of what you would expect or it is completely off? https://github.com/LukeLaz/mapstruct/pull/1

**Comment by filiphr** [comment]
@LukeLaz that looks like what I would expect from this.

**Comment by LukeLaz** [comment]
https://github.com/mapstruct/mapstruct/pull/2419

**Comment by filiphr** [comment]
Implemented as part of PR #2419. Thanks @LukeLaz for the work on this
