### ISSUE TITLE
Set resolver generates incompatible types

### ISSUE THREAD

**Issue by akurutin** [mapstruct/mapstruct#2175]
- [ x] Is this an issue (and hence not a question)? 1.3.final version

Resolver does not generate correct collection type. For example:

```
public  Set<ShopType> resolveShopTypes(
      Set<ClassifierView> classifiers, @TargetType Class<Set<ShopType>> entitySetClass) {
    return classifiers.stream()
        .map(c -> this.resolve(new BaseEntityListView(c.getId()), ShopType.class))
        .collect(Collectors.toSet());
  }
```
generate code like this:

`shop.setShopTypes( baseResolver.resolveShopTypes( view.getShopTypes(), Set.class ) );`

where Set.class is incomatible with  `Set<ShopType>`

**Comment by akurutin** [comment]
For example, need to create default method like:
Set<ShopType> map(Set<DTOType extends ShopTypeView> set) {
 return  set.stream.forEach(e->this::resolve).collect(<...>);
}
and create mapper for each type of Classifier with Classifier Factory(for shopTypes, shopDeparts, etc)?

**Comment by sjaakd** [comment]
What about something like this::

```java
public <T extends ShopType> T resolveShopTypes(ClassifierView view, @TargetType Class<T> clz) {
    return this.resolve(new BaseEntityListView(c.getId()), ShopType.class));
  }
``` 

and keep the collection out of the mapping method? (Leave it up to mapstruct)?

Perhaps its also better to put this method in a context instead of in a mapper. Checkout [this](https://github.com/mapstruct/mapstruct-examples/tree/master/mapstruct-jpa-child-parent) example. 

BTW: you don't need classifiers if you don't create selection conflict.

**Comment by filiphr** [comment]
I am going to close this issue as I think that we can't do magic here and using `Class<Set<ShopType>>` is not a good idea anyways.
