### ISSUE TITLE
Field or Setter Injection does not inject a Spring Component into my abstract class mapper. Throws NPE.

### ISSUE THREAD

**Issue by Arpan-Chakra** [mapstruct/mapstruct#2176]
- [ ] Is this an issue (and hence not a question)? 

I have tried the following ways :  

1) Setter Injection
2) Field Injection as shown below
 
Issue : billingAccountService is null

```
@Mapper(componentModel = "spring", nullValueCheckStrategy = NullValueCheckStrategy.ALWAYS)
public abstract class OrderMapper {

    @Autowired
    protected BillingAccountService billingAccountService;

   @Mappings({
        @Mapping(target = "id", expression = "java(billingAccountService.getResourceCategory())")
    })
    public abstract GoTransverseServiceResourceCategory mapToGoTransverseServiceResourceCategory(BillingOrderItem orderItem);
}
```

3) Have also tried using "uses" however throws compilation error in Impl class

Issue : billingaccountservice is null

```
@Mapper(componentModel = "spring", nullValueCheckStrategy = NullValueCheckStrategy.ALWAYS, uses = BillingAccountService.class)
public abstract class OrderMapper {
@Mappings({
        @Mapping(target = "id", expression = "java(billingaccountservice.getResourceCategory())")
    })
    public abstract GoTransverseServiceResourceCategory mapToGoTransverseServiceResourceCategory(BillingOrderItem orderItem);
}
```

Please HELP. Have already gone through the following links : 
https://stackoverflow.com/questions/38807415/mapstruct-how-can-i-inject-a-spring-dependency-in-the-generated-mapper-class
https://stackoverflow.com/questions/55786718/mapstruct-constructor-injection-spring

**Comment by filiphr** [comment]
1. and 2. should work if you get the `OrderMapper` from an `ApplicationContext` or inject it in your own class. If you are using `Mappers#getMapper` then it doesn't work, because that is only meant for the default component model.

For 3. it is expected not to work as well. MapStruct will create  a field only if it is used by some mapping. Otherwise we do not include that field in the generated class. You should not rely on the way the class is generated.
