### ISSUE TITLE
Incorrect mapper generation when class has generic argument - collection element not mapped

### ISSUE THREAD

**Issue by ZuperKeurZ** [mapstruct/mapstruct#2184]
This is on mapstruct 1.3.0.Final
I included a sample that demonstrates the issue.

Class X has a list of A's called children
Class Y has a list of B's called children

class X has a generic Type argument **that is not used at all**

The generated code does conversion from A to B  when mapping X to Y.
The gernated code does NO conversion from B to A when mapping Y to X.

Generated code looks like this:

### X to Y - Note the mapToBs() call
```
    @Override
    public Y map(X x) {
        if ( x == null ) {
            return null;
        }

        Y y = new Y();

        if ( y.getChildren() != null ) {
            List<B> list = mapToBs( x.getChildren() );
            if ( list != null ) {
                y.getChildren().addAll( list );
            }
        }
        return y;
    }
```
### Y to X - the items are copied without being mapped
```
    @Override
    public X map(Y y) {
        if ( y == null ) {
            return null;
        }

        X x = new X();

        if ( x.getChildren() != null ) {
            List<B> list = y.getChildren();
            if ( list != null ) {
                x.getChildren().addAll( list );
            }
        }

        return x;
    }
```

[mapstructissue.zip](https://github.com/mapstruct/mapstruct/files/5119223/mapstructissue.zip)

**Comment by filiphr** [comment]
The reason for this is because you are using `X` as a raw type. When a generic class is used as a raw then all generics are dropped.

This is coming from JLS ([4.8](https://docs.oracle.com/javase/specs/jls/se8/html/jls-4.html#jls-4.8))

>The type of a constructor (§8.8), instance method (§8.4, §9.4), or non-static field (§8.3) of a raw type C that is not inherited from its superclasses or superinterfaces is the raw type that corresponds to the erasure of its type in the generic declaration corresponding to C.

In a nutshell: On raw type usages, all generics are dropped - even those with fixed bounds.

Have a look at https://github.com/mapstruct/mapstruct/issues/1467#issuecomment-412355041 for more information.

If you don't use raw types then it should work correctly.

**Comment by filiphr** [comment]
The reason why it does no conversion is because it can directly add `B` elements to a list of `Object`. For the compiler `x.getChildren()` is `List`.
