### ISSUE TITLE
Extract field mapping from Mapper

### ISSUE THREAD

**Issue by roll57** [mapstruct/mapstruct#2189]
Hello, 
I would like to request a feature that could be useful in case of validation. Currently it is not possible to remember the original field name and his corresponding mapping.

Here is a small example
```
public class PersonDemo {

    public static void main(String[] args) {
        final PersonMapper mapper = Mappers.getMapper(PersonMapper.class);
        Person person = mapper
            .toPerson(new PersonDto()
                .setFirstName("John")
                .setName("Doe"));

        System.out.println(person);

        System.out.println("Expected " + toPersonDesc("firstName") + " to be firstName");
        System.out.println("Expected " + toPersonDesc("name") + " to be lastName");
    }

    @Mapper
    public interface PersonMapper {
        @Mapping(target = "lastName", source = "name")
        Person toPerson(PersonDto dto);

    }

    //expected method to be generated somehow from the mapping.
    static String toPersonDesc(String fieldName) {
        switch (fieldName) {
            case "name": return "lastName";
            case "firstName": return "firstName";
        }
        return null;
    }

    @Data
    @Accessors(chain = true)
    public static class Person {

        private String lastName;
        private String firstName;
    }

    @Data
    @Accessors(chain = true)
    public static class PersonDto {

        private String name;
        private String firstName;
    }
}
```
It could be nice if maptruct can propose a way to generate the method _toPersonDesc_ from my example.

I could imagine a new annotation that take the method that we want describe.

```
    @Mapper
    public interface PersonMapper {
        @Mapping(target = "lastName", source = "name")
        Person toPerson(PersonDto dto);

        @MappingDescriptor(method="toPerson")
        String toPersonDesc(String fieldName);
        @MappingDescriptor(method="toPerson", inverse= true)
        String fromPersonDesc(String fieldName);
    }
```

Note:
I have ask the question on [stackoverflow](https://stackoverflow.com/questions/63613641/is-there-a-way-to-extract-mapstruct-mapping).

**Comment by sjaakd** [comment]
I'm not sure whether this should be part of the MapStruct core. I could imagine several solutions however:

1. Along your lines: when you come to think of it, you've made it independent by making your own `@MappingDescriptor` annotation. So it could be solved by another annotation processor. Since there's a strong coupling to the business logic of MapStruct it would make sense to "host" it near MapStruct. We have already some other tooling in our organisation related to Spring. @filiphr WDYT?

2. I had a similar problem myself. In my code I receive soap requests. These soap requests are in english (large object graphs). I map them to a DTO model (object graph) that reflects the domain model, also in english by means of MapStruct. 
However, all entities and attributes in the model are described in Dutch in the user documentation. The user should get feedback (error messages) on this level in Dutch. 
Now, we use bean validation to validate the DTO model (with many custom validators). 
The key (the  path to an entity / attribute in the model, or in java terms the DTO  bean / property) can be  used in a custom message interpolator that can use this path to map the attribute (bean-property) to the Dutch name in a property file (bean validation messages). Like: person.address.street=persoon.adres.straat. This is then rendered into the error message. 
Years ago, I wrapped the entirety bean validation framework by means of  java.reflect.proxy but fortunately the hibernate validation 6.1 has a PR of mine implemented to make the path available to the message interpolator. A resource bundle can be used to make the mapping in the end, which makes this rather straightforward. 
The nice thing: you solved the I18N problem as well this way in a general way.

**Comment by sjaakd** [comment]
@roll57 did my answer make sense to you?

**Comment by roll57** [comment]
Hi,
Thank you for your response.
I will have a look at how hibernate do it, but it is not really the same use case as mine.
With your first point I had the hope that somehow something was existing to do that.
I will try to come up with a solution, as you think that it is out of the scope of mapstruct.

**Comment by filiphr** [comment]
This is something similar to the needs described in #702. 

I agree with your point 1 @sjaakd. We do collect a lot of this information and we having during the generation of the mappers. In theory it could be possible to hook into the `ModelElementProcessor` and do something. However, I think that for the time being this is out of scope for us. Currently this is something that we are not focused on. Therefore, I am going to close this issue
