### ISSUE TITLE
Different behaviours in IntellijIDEA build and Maven Build

### ISSUE THREAD

**Issue by angelodelia** [mapstruct/mapstruct#2209]
Hello,
I'm using MapStruct 1.3.1.Final.
I have in my pom the following
```
        <!-- mapstruct -->
        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct-processor</artifactId>
            <version>${org.mapstruct.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct</artifactId>
            <version>${org.mapstruct.version}</version>
        </dependency>

```
I also use the Intellij IDEA (last version) together with the MapStruct plugin enabled (ver 1.2.2).
I have strange different behaviours.
Namely, when trying to map as target a property that is in a superclass, IDEA says it can't be found. If I run all with Maven, property is found and mapper generated as expected.
Other strangeness are sometimes popping about the handling of boolean fields. 
But more of the cases, I would like to understand the different behaviours. As I have IDEA set to "pick annotation processor from classpath" I'm surprised of having them.

**Comment by filiphr** [comment]
There shouldn't be any differences between IDEA and Maven. The plugin shouldn't make a difference, since it is not affecting the compilation at all. Maybe the IDEA incremental compilation causes some problems.

Can you please compare the values in the `@Generated` tag in the generated mappers?

Does the value in the `comments` match between the mappers generated from IDEA and Maven.

Are you by any chance using Lombok?

**Comment by angelodelia** [comment]
Hi Filip, yes, sorry, I forgot, to mention it, but lombok is in the mix.
Instead, the generation tags of the implementation are identicals (except the timestamp of course) once I workaround the issue and get the mappers generated by the IDEA compiler.
So, sounds the issue is more with the IDEA compiler and/or the "mixing up" with lombok.

**Comment by filiphr** [comment]
Since the only difference is the timestamp then it has to do with Lombok and how IDEA does the compilation. I don't think that we can do anything.

Btw IDEA does not have a compiler, it uses javac (default) or ecj to perform the compilation. However, they have some way of doing incremental builds and do not pass everything all the time to the compiler.
