### ISSUE TITLE
Deep cloning creates intermediate methods for primitive arrays

### ISSUE THREAD

**Issue by davidwbrown** [mapstruct/mapstruct#2213]
As in [#1558]

`@Mapper(mappingControl = DeepClone.class)`

Seems to pull in the annotations on byte[] to byte[] copy. If I remove the DeepClone it maps fine, but I need DeepClone.

**Comment by filiphr** [comment]
Thanks for raising this issue @davidwbrown.

I managed to reproduce it and fix it locally. Will push a fix shortly.

It should not be affected by the `DeepClone`. However, it causes generation of intermediate mapping methods for the arrays.

e.g. 

Generated without deep clone:
```
boolean[] booleanData = car2.getBooleanData();
if ( booleanData != null ) {
    car.setBooleanData( Arrays.copyOf( booleanData, booleanData.length ) );
}
```

Generated with deep clone

```
car.setBooleanData( booleanArrayTobooleanArray( car2.getBooleanData() ) );

...
protected boolean[] booleanArrayTobooleanArray(boolean[] booleanArray) {
    if ( booleanArray == null ) {
        return null;
    }

    boolean[] booleanTmp = new boolean[booleanArray.length];
    int i = 0;
    for ( boolean boolean1 : booleanArray ) {
        booleanTmp[i] = boolean1;
        i++;
     }

    return booleanTmp;
}
```

We should probably iterate over this, because in this case we are already creating a copy.

**Comment by filiphr** [comment]
@davidwbrown you can temporarily fix this by adding a default method for mapping between `byte[]` and `byte[]`. The fix is on its way, doing some final local testing
