### ISSUE TITLE
Explicitly set defaultValue for mapping changes generated code

### ISSUE THREAD

**Issue by idrissov** [mapstruct/mapstruct#2241]
Dear team,
I faced with the strange behavior of code generation.

In annotation `@Mapping`  attribute `defaultValue` has the default  "empty string". So I expect that `@Mapping` and `@Mapping(defaultValue = "")` should behave the same. But:

If I declare mapping as `@Mapping(target="id", source = "id"` then mapstruct generates the following:
```java 
tenant1.id = tenant.id;
```
if I declare mapping as `@Mapping(target="id", source = "id", defaultValue = ""` then mapstract generates the following:
```java
        if ( tenant.id != null ) {
            tenant1.id = tenant.id;
        }
        else {
            tenant1.id = "";
        }
```

Is this behavior by design or it's a bug?

**Comment by filiphr** [comment]
This works like this by design.

Your expectation is correct when the annotation would be evaluated during runtime. However, since we are an annotation processor we know whether a value has been set or not. This allows us to do fallbacks to defined values in `@Mapping`, `@Mapper`, `@MapperConfig` etc.

e.g the default for `nullValueCheckStrategy` in the `@Mapping` annotation is `ON_IMPLICIT_CONVERSION`. However, if you define something in `@Mapper` then the one from there will be used and not `ON_IMPLICIT_CONVERSION`.

We have to set `default` otherwise users will have compilation errors and will need to define the value always.
