### ISSUE TITLE
Cannot map a collection with named mapping method

### ISSUE THREAD

**Issue by MaciejDobrowolski** [mapstruct/mapstruct#2250]
After upgrading to mapstruct 1.4.1 we are having some problems with mapping collections using named mapping methods. I suspect this is a bug b/c it worked fine for mapstruct 1.2.0.

The full example can be found here: https://gist.github.com/MaciejDobrowolski/6a9b9bedfd873e8ffd822301ab333be4

I am getting the following errors:

> Demo.java:36: error: Qualifier error. No method found annotated with `@Named#value`: [ fromBase ]. See https://mapstruct.org/faq/#qualifier for more info.
>     House toEntity(HouseDto houseDto);
>           ^
> Demo.java:36: error: Can't map property "List<aseDto> dogs" to "List<og> dogs". Consider to declare/implement a mapping method: "List<og> map(List<aseDto> value)".
>     House toEntity(HouseDto houseDto);
>           ^

+short in-ticket summary:

Having the following model:
```
class BaseEntity {
    private Long id;
}

class Dog extends BaseEntity {
    private String name;
}

class House extends BaseEntity {
    private List<Dog> dogs;
}

class BaseDto {
    private Long id;
}

class HouseDto extends BaseDto {
    private List<BaseDto> dogs;
}
```

And the following mapper:

```
@Named("fromBase")
public <T> T fromBase(BaseDto baseDto, @TargetType Class<T> entityClazz) {
    return Optional.ofNullable(baseDto)
            .map(BaseDto::getId)
             // somehow create instance of T from id
            .orElse(null);
}
```
The above mapper is not used by the one below:

```
@Mapping(target = "dogs", qualifiedByName = "fromBase")
House toEntity(HouseDto houseDto);
```

If I only change `dogs` to be a single `dog` (without `List`), it works as expected.

update: I have just removed generics and `@TargetType` from `fromBase` mapping method and it still returns the same error

**Comment by filiphr** [comment]
We made the way qualifiers are used a bit more strict in 1.4. Are you sure that the `fromBase` methods was used before?

In order to make it work you'll need to add `Named` method that would map from `Collection` to `Collection`.

@sjaakd looking at this use case I think that we should relax a bit the checks here. When a user uses `qualifiedByName` for iterable mappings we could create an intermediate iterable mapping method like the user has defined `IterableMapping#qualifiedByName` that way the qualifier will be applied to the mapping of the single elements.

**Comment by sjaakd** [comment]
> @sjaakd looking at this use case I think that we should relax a bit the checks here. When a user uses `qualifiedByName` for iterable mappings we could create an intermediate iterable mapping method like the user has defined `IterableMapping#qualifiedByName` that way the qualifier will be applied to the mapping of the single elements.

I'm not entirely sure. I think its also confusing, especially if you have iterable mapping methods that you have annotated as well and would like to select. Perhaps we need to think about it a bit more. And what about map-mapping: are we qualifying on key or on value or not?

**Comment by filiphr** [comment]
If there are iterable mapping methods that you have annotated then we use them. My idea is to still allow creating intermediate iterable mapping methods like they have been written by a user and not throw a compile error.

>And what about map-mapping: are we qualifying on key or on value or not?

We don't have to do it for map mapping, I am not even sure how intermediate map methods look like right now.

**Comment by MaciejDobrowolski** [comment]
@filiphr I have just recompiled the above gist with mapstruct 1.3.1.Final to check if `baseMapper` was really picked up for iterable mapping. The code compiles, this is how iterable mapping was generated (it uses `fromBase` method):
```
    protected List<Dog> baseDtoListToDogList(List<BaseDto> list) {
        if ( list == null ) {
            return null;
        }

        List<Dog> list1 = new ArrayList<Dog>( list.size() );
        for ( BaseDto baseDto : list ) {
            list1.add( baseMapper.fromBase( baseDto ) );
        }

        return list1;
    }
```

I haven't succeeded in adding another `Named` method to map from `Collection` to `Collection`. It will not use this method b/c the return type is `Collection`, not `List` - as required in this case. Adding n methods for all n types of collections used in a project would work (`List<X> fromBase(Collection<Y>)`) but is... a nasty workaround :)

**Comment by filiphr** [comment]
>The code compiles, this is how iterable mapping was generated (it uses `fromBase` method)

It doesn't use the correct `fromBase` method right? It should use `fromBase(BaseDto, Class<T>)`, but it uses `fromBase(BaseDto)`. In 1.4 it correctly errors out instead of silently ignoring the `qualifiedByName`.

You can try removing the `@Named` for the `fromBase` if possible, they you won't need `qualifiedByName`.

By the way one side not, your `BaseMapper` doesn't have to be annotated with `@Mapper`, you don't have mapping methods in it. The classes defined in `Mapper#uses` don't have to be mappers.

**Comment by MaciejDobrowolski** [comment]
Sorry, I am mixing things up - in the meantime, I tried to simplify the code even more and this is why I have pasted a mapping method that uses `fromBase(BaseDto)` instead of `fromBase(BaseDto, Class<T>)`.

The point is that mapstruct generates correct mapping methods in 1.3.1.Final version, and cannot generate them in 1.4.1.Final. I have added a link to a ready-to-run gist in the first post - please, if you have 5 minutes, try to run it with 1.4 and 1.3 (just change versions in build.gradle). 

I really suspect there's no way now, in 1.4.1, to create a single mapper that would:
* work for **any** specific target type of a collection (like `List` or `Set`)
* accept @TargetType as a parameter
Previously this many-to-many mapper was generated by calling one-to-one mapper for each element of the collection

**Comment by Martin-Narvar** [comment]
I just encountered this problem when updating from mapstruct 1.3.1 to 1.4.1 because 1.3.1 no longer works with IntelliJ.

I read all of the comments here, but they provided no insight whatsoever about how to fix this problem in my code.
I am working with is an old application that has been in production for years, and the only change I made was to bump the version of mapstruct, nothing else, and it's broken, but this is not listed as a breaking change in mapstruct.

If some feature has been deprecated, then you need to provide guidelines on how to migrate to its replacement.

I didn't have anything to do with writing this application, I have no idea what qualifiedByName is supposed to do, and therefore have no idea where to start looking for a solution to this breaking change. I can't revert to 1.3.1 because it no longer works in IntelliJ.
