### ISSUE TITLE
Vague documentation and code samples of @Default annotation as of 1.4.X

### ISSUE THREAD

**Issue by Nikolas-Charalambidis** [mapstruct/mapstruct#2258]
I have encountered with the constructor support and the `@Default` annotation usage. 

At the first glance (I looked at the code samples first), I had a strong feeling there is already such annotation delivered with the new version ([3.9. Using Constructors](https://mapstruct.org/documentation/stable/reference/html/#mapping-with-constructors)), however, I had to come back to the documentation itself. These sentences confused me (emphesized mine):

> If a constructor is annotated with an annotation named `@Default` (**from any package**) it will be used. 

> If there are multiple eligible constructors then there will be a compilation error due to ambiguous constructors. In order to break the ambiguity an annotation named `@Default` (**from any package**) can used.

This pattern is unusual to MapStruct and unintuitive. I had to *guess* and *experiment* a bit to know I have to declare *my own* annotation. I think this message should be delivered more clearly for the users.

```
package com.mycompany.support.mapstruct;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

@Retention(RetentionPolicy.CLASS)
public @interface Default {
}
```

The solutions are these (picking one of them should make the usage clear):
- Deliver the `org.mapstruct.Default` annotation itself (I understand there *might* be reasons against this idea, however, I haven't found any communication concluding to such reason, hence I'd like to ask for some links explaining that) 
- Add the annotation definition to the documentation and explicitely state the annotation must be either **created** by the user or **reused** from a third-party library/framework with a reason behind this design.

Moreover, I propose the following one:
- Require `@DefaultConstructor` instead of `@Default`. The proposed one would be more suitable with regard to the use-case and also would not be confused with the one comming from Lombok, which a big friend with MapStruct (yet another my assumption)

I am open to submit a pull-request as soon as you point me to the relevant files to be changed as long as I am a new contributor :smile:

**Comment by filiphr** [comment]
I am sorry to hear about the confusion, since it was confusing to you, it would have most certainly been confusing to other users as well.

We thought that adding `(from any package)` would make it clear, but it seems not.

We didn't decide to deliver the `org.mapstruct.Default` annotation because we thought that users do not want to annotate their entity code with annotation from the mapstruct module. This would mean that they need to add a dependency to it. We similarly support any annotation named `ConstructorProperties` (it doesn't have to be `java.beans.ConstructorProperties`, it can also be user created, to detect the names of the parameters for the constructor.

I would go with making the documentation clearer. This is [here](https://github.com/mapstruct/mapstruct/blob/master/documentation/src/main/asciidoc/chapter-3-defining-a-mapper.asciidoc#using-constructors). Can you please submit a PR with what your suggestion?

Regarding the renaming of `@Default` to `@DefaultConstructor` it would be a bit difficult since we already released the final release and it would be a breaking change to change that. We could support `@DefaultConstructor` additionally, but I don't think that making our code more complex is worth it. I didn't know that Lombok already has the `@Default` annotation actually, even though our users use Lombok and MapStruct together, I personally am not a Lombok user.

**Comment by Nikolas-Charalambidis** [comment]
@filiphr Don't hesitate to assign this issue to me. Now I understand the reason behind not shipping such annotation and I have submitted a pull request, please have a look and let me ask you for the assistance.

Lombok is very popular nowadays and MapStruct works well with it. This would be worth mentioning in the documentation as well. Since a custom/third-party annotation design and Lombok have a common origin, I propose the following:

**Proposals:** 
- Create the 14th chapter named `14. Third-party integration`
- Create section 14.1. Non-shipped annotations` which would describe the reason behind the design in more detail and the way to create such annotation if necessary. 
- Create section 14.2. Lombok` which would describe that generated getters/setters and constructors are compliant with MapStruct mappings. The very idea of this section would be to introduce the "Lombok-MapStruct" friendship in terms of set-up, one simple example and tips to deal with possible issues (Maven plugins).
- In the documentation let the "from any package" sentence be a alink to the `14.1.` section, such as:
> If a constructor is annotated with an annotation named `@Default` ([from any package]()) it will be used.

Such chapter would open possibilities for description of further third-party libraries integration.

Again, I am open to the discussion (it might require to open another issue) and further pull-requests.

**Comment by filiphr** [comment]
I love the idea @Nikolas-Charalambidis, really good suggestions. I assigned this issue to you. I don't think we need a new issue. You can do all of that as part of this one.

**Comment by Nikolas-Charalambidis** [comment]
@filiphr Please, kindly take a look at the pull-request https://github.com/mapstruct/mapstruct/pull/2262. 

Regarding to the proposed `14.2. Lombok` section, I would rather submit a different pull-request (therefore an issue) to make this issue mainly about `@Default` easier to close. 😄

**Comment by filiphr** [comment]
Thanks @Nikolas-Charalambidis. Had a look at left a review.

>Regarding to the proposed `14.2. Lombok` section, finally, I would rather submit a different pull-request (therefore an issue) to keep the things organized, to make this issue mainly about `@Default` description easier to close and to move on. 😄

Sure no problem for me. Feel free to create the issue and the PR whenever you can.
