### ISSUE TITLE
[Bug] Using @MapperConfig from another jar with multiple arguments throws error

### ISSUE THREAD

**Issue by sp4ce** [mapstruct/mapstruct#2260]
- [x] Is this an issue (and hence not a question)? 
- version: 1.3.1.Final

When using a `@MapperConfig` coming from another jar (a dependency), MapStruct is using the compiled code to read the argument of the configuration, so it's expected source parameter to be referenced as `arg0`, `arg1`, etc.

Example code (this is a made up example to show case the problem, not a real use case, but something very similar)

```java
// mapper-config.jar

@MapperConfig
public interface PersonMapperConfig {

    @Mapping(target = ".", source = "person")
    @Mapping(target = "petId", source = "pet.id")
    PersonDto toDto(Person person, Animal pet);
}


// person-service.jar

@Mapper(config = PersonMapperConfig.class)
public interface PersonMapperConfig {

    @InheritConfiguration
    PersonDto toDto(Person person, Animal pet);
}
```

When compiling `person-service.jar`, you will get the errors:

```
java: Method has no source parameter named "person". Method source parameters are: "arg0, arg1".
java: Method has no source parameter named "pet". Method source parameters are: "arg0, arg1".
```

----

### workaround

The workaround is to use directly `arg0`, `arg1`, etc. in the config. This is not ideal and it makes your config relying on the compiler and unusable inside the same jar.

```java

@MapperConfig
public interface PersonMapperConfig {

    @Mapping(target = ".", source = "arg0")
    @Mapping(target = "petId", source = "arg1.id")
    PersonDto toDto(Person person, Animal pet);
}
```

----

### proposed solution

1. Fix the problem directly, I don't know enough the code of MapStruct, but would it be possible not to read the `.class` file for the argument name, but only the current `@Mapper` code? This way the argument name in the actual mapper will have to match the one in the config, and we would ignore the one in the configuration.

2. Add a `@ParamName` annotation that would override the name of the variable. So basically the code in the configuration would look like

```java

@MapperConfig
public interface PersonMapperConfig {

    @Mapping(target = ".", source = "person")
    @Mapping(target = "petId", source = "pet.id")
    PersonDto toDto(@ParamName("person") Person whatever0, @ParamName("pet") Animal whatever1);
}
```

**Comment by filiphr** [comment]
The reason why we are reading from the `@MapeprConfig` is because your `@Mapper` might not use the same names. Since that is entirely valid.

Doing something like `@ParamName` would indeed solve this problem, but I am not sure that I like that. Especially since you can compile your other jar with Java 8 `parameters` option and thus keep the parameter names in the byte code.

By the way we are not reading the `.class` file we are using the utils provided by the Java compiler to get access to the Abstract Syntax Tree of the classes.

**Comment by sp4ce** [comment]
Hum, so you are saying I could also solve the problem by simply activating the `-parameters` flag. But it looks like this is not something desirable in the long term: https://stackoverflow.com/a/44075684/541796

`@ParamName` would be optional for those who don't/can't use the `-parameters` flag. Sometimes in medium/big companies, you don't control entirely the build system and you have an imposed mechanism that does not allow all sort of customization.

Another simple workaround I used is to wrap the multiple param into a unique class.

```java
@MapperConfig
public interface PersonMapperConfig {

    @Mapping(target = ".", source = "person")
    @Mapping(target = "petId", source = "pet.id")
    PersonDto toDto(ToDtoInput input);

    default PersonDto toDto(Person person, Animal pet) {
        return toDto(new ToDtoInput(person, pet));
    }

    @Data
    @RequiredArgsConstructor
    class ToDtoInput {
        private final Person person;
        private final Animal pet;
    }
}
```

**Comment by filiphr** [comment]
>Hum, so you are saying I could also solve the problem by simply activating the `-parameters` flag. But it looks like this is not something desirable in the long term: https://stackoverflow.com/a/44075684/541796

Yes adding the `-parameters` flag would solve the problem.

From the StackOverflow answer I don't see why it wouldn't be desirable in the long term. Yes it can affect certain things like the class size and the details about Jackson. However, from the point of view of MapStruct there is no difference, you will get a compile error if something doesn't match.

I think that we've had a discussion about `@ParamName` and I don't think that it is worth adding it to the API surface of MapStruct. If you are having some global MapStruct configurations you can always put them in a dedicated module that you will compile with `-parameters`, which would be controlled only for that module.

I am not sure if your workaround works, because the `MapperConfig` is used to inherit mappings, and not to implement methods. So I don't see how the workaround works.

**Comment by filiphr** [comment]
Closing this as we don't want to add something like `@ParamName`.

**Comment by sp4ce** [comment]
Related issue for reference: https://github.com/mapstruct/mapstruct/issues/1198
