### ISSUE TITLE
Retention change

### ISSUE THREAD

**Issue by huifer** [mapstruct/mapstruct#2302]
Now there are many mapping interfaces. I need to search a large number of interface files when I use them. I hope I can modify the retention property in mapper and mappings. 
Now I have an idea that unified portal is called. Automatically search for methods to be executed based on the types of the original and target objects, and then return the conversion results

**Comment by filiphr** [comment]
I guess that you are looking for a way to detect classes annotated with `@Mapper` during runtime. This is something that we are not interested in providing. 

I would suggest looking at an alternative approach. Instead of using reflection you can use annotation processing and create your own `MapperFactory`. Have a look at the [mapstruct-spring-extensions](https://github.com/mapstruct/mapstruct-spring-extensions). Have a look at the [mapstruct-mapper-repo](https://github.com/mapstruct/mapstruct-examples/tree/master/mapstruct-mapper-repo) example as well.
