### ISSUE TITLE
Retain iteration order for Sorted(Map|Set) values

### ISSUE THREAD

**Issue by MatthiasBechtold** [mapstruct/mapstruct#2303]
We experienced a strange bug in our software recently, that took us a while to find. The insight we finally ended up with was:
The iteration order of a specific `Map` value caused the issue. Please consider following example:

```java
class SortedMapDto {
  public SortedMap<String, String> theMap = new TreeMap<>();
}

class TargetDto {
  public Map<String, String> theMap;
}

@Mapper
interface SortedMapMapper {
  TargetDto map(SortedMapDto sortedMapDto);
}
```
The code MapStruct (1.4.1.Final) generates from this is:
```java
// ...
SortedMap<String, String> sortedMap = sortedMapDto.theMap;
if ( sortedMap != null ) {
  targetDto.theMap = new HashMap<String, String>( sortedMap );
}
```

Now as any reasonable Java developer knows, the iteration order of `Map` is not guaranteed. So this bug was of course *our fault* and what MapStruct does is technically correct.

[Immutables](https://immutables.github.io/) though, has a bit more *resilient* take on that by always using `LinkedHashMap` for creating defensive copies of any `Map` types to retain their iteration order.

What I want to suggest is considering to use `LinkedHashMap` (and its counterpart `LinkedHashSet`) just like Immutables for defensive copies instead of `HashMap`.

What's your take on that?

**Comment by filiphr** [comment]
I completely understand what you are saying and it makes sense to use `LinkedHashMap` and `LinkedHashSet` instead in order to preserve the iteration order when creating defensive copies.

Currently this is done in:

https://github.com/mapstruct/mapstruct/blob/84c3bda5a23e48956ad5de4955792ef0a278638e/processor/src/main/java/org/mapstruct/ap/internal/model/common/TypeFactory.java#L115-L133


I am curious of whether there are some performance or memory implications if we do this change. Perhaps doing it in 1.5 is OK for this. WDYT @sjaakd?

**Comment by chris922** [comment]
Humm.. hard to judge the performance impact, because it totally depends on the usage pattern that MapStruct obviously don't know.

But in general `LinkedHashMap` and `HashMap` has the same complexity O(1) when working with the entries (see e.g. https://stackoverflow.com/a/17708526). So afaik `LinkedHashMap` just has a small overhead in terms of memory usage for keeping the order.

Anyway in most of the cases this overhead is negligible and I would propose to go for `LinkedHashMap` as using this is safer to prevent hard-to-debug-bugs _(what a word :smile: ) like the one @MatthiasBechtold describes and that's imho more important than providing the best possible performance.. if someone requires this it should always be possible to override the behavior with own mapping methods or object factories.

Of course also some config could be introduced to revert this behavior... buuut, there are already so many configurations :see_no_evil: 


PS: Don't miss to mention this in the documentation (e.g.  here: https://mapstruct.org/documentation/stable/reference/html/#mapping-maps)

**Comment by filiphr** [comment]
You are right @chris922. I was overthinking this I think.

Let's do this switch for 1.5.

>Of course also some config could be introduced to revert this behavior... buuut, there are already so many configurations 🙈

There is already an option for this. You could use `@ObjectFactory` 😄 .

Good idea for the pointer in the docs. We should do that there as well.

**Comment by NoFuchsGavin** [comment]
Same problem applies to "Set<String>" where the implementation should be "LinkedHashSet<String>".

**Comment by filiphr** [comment]
@NoFuchsGavin please create a new issue if you are interested in preserving the order of a `Set`. However, I am not sure how open we would be in accepting it since a `Set` is by definition unordered. It might be better if we can look into supporting the upcoming Java 21 [Sequenced Collections](https://openjdk.org/jeps/431). I also created #3240 for supporting Sequenced Collections
