### ISSUE TITLE
Even after upgrading mapstruct and mapstruct-processor to 1.4.1.Final, mapstruct isnt able to generate implementation at compilation...I get errors saying

### ISSUE THREAD

**Issue by manoranjanb** [mapstruct/mapstruct#2314]
**IntelliJ 2020.3 EAP (Community Edition)
Runtime version: 11.0.9+11-b944.49 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.7**
Even after upgrading mapstruct and mapstruct-processor to 1.4.1.Final, mapstruct isnt able to generate implementation at compilation...I get errors for `@Mapping`  source and target saying 
`No property named "<attribute>" exists in source parameter(s). Did you mean "null"?`
I have also updated the lombok to 1.18.16

Finally, I am downgrading to proceed with regular work.
After downgrading IntelliJ to 2020.2, I had to downgrade mapstruct to 1.3.1.Final and Lombok to 1.18.12.
Things are working now as expected (:-)

Not sure, if the EAP version is causing problems, I didn't find any update

_Originally posted by @manoranjanb in https://github.com/mapstruct/mapstruct/issues/2215#issuecomment-751297722_

**Comment by spyvip** [comment]
try lombok 1.16.22 and mapstruct 1.4.1.final, that should be fine.

**Comment by filiphr** [comment]
@manoranjanb you might be affected by the breaking change in Lombok 1.18.16. Please do not open a new issue since #2215 is the issue that handles the problems for IntelliJ and has a lot of explanations to how you can make it work. Including a way to fix it in IntelliJ itself explained in https://github.com/mapstruct/mapstruct/issues/2215#issuecomment-703120512

You need to add [lombok-mapstruct-binding](https://search.maven.org/artifact/org.projectlombok/lombok-mapstruct-binding).
