### ISSUE TITLE
Mapper method code is empty for mapping target for Koltin data class

### ISSUE THREAD

**Issue by krupt** [mapstruct/mapstruct#2315]
Hello. Found empty compilation result for mapper method with the code below:

```
@Mapper
interface TournamentMapper {

    fun applyUpdateRequestToEntity(
        request: TournamentUpdateRequest,
        @MappingTarget entity: TournamentEntity
    ): TournamentEntity
}

data class TournamentUpdateRequest(
    val name: String?,
    val description: String?,
    val information: String?,
    val startDate: LocalDate,
    val endDate: LocalDate
)

data class TournamentEntity(
    @Id
    val id: UUID? = null,
    val name: String?,
    val description: String?,
    val information: String?,
    val startDate: LocalDate,
    val endDate: LocalDate,
    val state: TournamentState
)
```
It generates the Java code below without errors or wrnings:
```
    @Override
    public TournamentEntity applyUpdateRequestToEntity(TournamentUpdateRequest request, TournamentEntity entity) {
        if ( request == null ) {
            return null;
        }

        return entity;
    }
```
Have no idea how to fix it.
MapStruct 1.4.1, Kotlin 1.4.21.
Thank you.

**Comment by filiphr** [comment]
From my little knowledge about Kotlin `val` means that the variable is immutable, i.e. there is no setter for it.

The way the update mappings work is by invoking the setter on the `@MappingTarget`. Your `TournamentEntity` does not have any setters. Therefore, the method is generated like that.

We do not create a copy of the object in order to return it.
