### ISSUE TITLE
Optimization: Make java.time.format.DateTimeFormatter instances final members

### ISSUE THREAD

**Issue by abomb4** [mapstruct/mapstruct#2329]
- [x] Is this an issue (and hence not a question)? 

This is an optimization request: making the `DateTimeFormatter` in the generated MapperImpl a static member may improve performance.
Currently MapStruct (v1.4.1.Final) will generate date mapping method like:
```java
if ( entity.getTime() != null ) {
    dto.setTime( DateTimeFormatter.ofPattern( "yyyy-MM-dd HH:mm:ss" ).format( entity.getTime() ) );
}
```
If make `DateTimeFormatter.ofPattern( "yyyy-MM-dd HH:mm:ss" )` a static final member may be better.
`DateTimeFormatter` is thread-safe (https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html#patterns).

**Comment by filiphr** [comment]
I think that this makes. However, I am not sure how easy it is for us to do this with the current implementation.

@abomb4 would you be interested in working on this?

**Comment by abomb4** [comment]
I can’t guarantee that I can do it. I have no experience in contributing code on github yet. I have to learn the source code first.

**Comment by eforest** [comment]
Hi everybody,
I found a possible solution to this with a few changed to HelperMethod / SupportingMappingMethod.
See here: https://github.com/mapstruct/mapstruct/pull/2380

The only problem I would see here is that the generated mapper source wins no clean code award (to be positive).

Here's an example of a generated mapper (for test Java8TimeConversionTest)
[SourceTargetMapperImpl.java.txt](https://github.com/mapstruct/mapstruct/files/6131522/SourceTargetMapperImpl.java.txt)

Another approach would be to extend HelperMethod to support SupportingField/SupportingConstructorFragment like BuiltInMethod does. But actually I wasn't sure how often such a mapper instance is created.

**Comment by eforest** [comment]
Hi @filiphr ,
thanks for your inputs on my first draft. I thought as much :-)

Now, here's a second try using mapper instance fields (non static as yet). 
HelperXX and BuiltInXX are very close now, so it might be necessary to do some refactorings here afterwards (but I'm not familiar with all those package restrictions and enforced rules)
Please see here: https://github.com/mapstruct/mapstruct/pull/2386

Here's again an example of a generated mapper (for test Java8TimeConversionTest)
[SourceTargetMapperImpl.java.txt](https://github.com/mapstruct/mapstruct/files/6175883/SourceTargetMapperImpl.java.txt)

Field names of DateTimeFormatters are more readable now but hopefully still unique enough.
Another option would be to create static fields with inline initialization.

**Comment by filiphr** [comment]
Thanks a lot for working on this @eforest. 

I like the new approach way more. The code reads way better now 😄.

> Now, here's a second try using mapper instance fields (non static as yet).

I think that not making them static is OK. The mappers are singletons anyways and the goal is to remove the creation of the date time formatter during the mapping.

------------
Now some feedback on the PR:

>HelperXX and BuiltInXX are very close now, so it might be necessary to do some refactorings here afterwards (but I'm not familiar with all those package restrictions and enforced rules)

Yes I just realised that the `BuiltInXX` are in the `org.mapstruct.ap.internal.model.source.builtin` package. I would say that you should reuse as much as possible. This would mean that you'll need to move some of the classes to `org.mapstruct.ap.internal.model.common`, which is completely fine, better than having 2 identical classes.

I saw that you also added a constructor fragment. I don't think that you need to do that since you can create a dedicated `DateTimeFormatterFinalField` in which you will call `DateTimeFormatter.ofPattern`. The fragment is needed for the `DateTypeFactory` since it throws an exception.

I also saw that you added Pseudo-HelperMethod to be able to create the field. I would suggest to maybe expose another getter in the `ConversionProvider` that will return the helper fields.

I am not too keen on creating the fields with those unique names using the hash code, but I guess that this is the easiest way for now, without big changes with some special registering in the `ConversationContext`.

I saw you removed the equals and hash code from `SupportingField`, why did you need to do that?

Can you also add some tests? Perhaps a new test with a fixture? For testing the generated output,

**Comment by eforest** [comment]
> I saw you removed the equals and hash code from SupportingField, why did you need to do that?

equals / hashCode of 'SupportingField' was done solely on templateName (without calling super). But now we have multiple fields using the same template. At some point all the stuff for a mapper is collected and these fields would end up in a set, with just one of them surviving. 

> Can you also add some tests? Perhaps a new test with a fixture? For testing the generated output,

I was happy that all existing tests worked without changes. 
Possible tests I can think of:
 - dateTimeFormatter for same pattern reuses field (and doesn't create two fields)
 - no field generated in case default DTF is used
 - ...

**Comment by filiphr** [comment]
>equals / hashCode of 'SupportingField' was done solely on templateName (without calling super). But now we have multiple fields using the same template. At some point all the stuff for a mapper is collected and these fields would end up in a set, with just one of them surviving.

Indeed you are right, not sure why it was like that.

>I was happy that all existing tests worked without changes.

I am ecstatic about that as well. Really good work. The reason why I asked for such fixture tests is because they will test the field generation, no field generated in case default DTF, etc. One test with what you already described should be enough

**Comment by filiphr** [comment]
Thanks for your work on this @eforest. It has been integrated.
