### ISSUE TITLE
NullValueMappingStrategy option to map collections/maps, but not beans

### ISSUE THREAD

**Issue by mjustin** [mapstruct/mapstruct#2351]
I have a mapper type that's mapping optional list elements from user input to required list elements internally.  MapStruct provides the option to set a `NullValueMappingStrategy`, but that also maps beans to null.  It would be helpful for my use case if `NullValueMappingStrategy` had the option to return default for collection-like objects (map/iterable), but not for beans.  It seems something generically useful as well; often code that null collection elements as equal to empty wouldn't want to do the same for beans.

My current workaround is to add a custom mapping type for lists to my mappers:

```java
    default <T> List<T> mapList(List<T> value) {
        return value == null ? Collections.emptyList() : value;
    }
```

## Proposed solution:
```java
public enum NullValueMappingStrategy {
    RETURN_NULL,
    RETURN_DEFAULT,
    RETURN_DEFAULT_COLLECTIONS,
    RETURN_DEFAULT_BEANS; // For completion's sake
}
```

**Comment by filiphr** [comment]
The requirement makes sense, but instead of extending `NullValueMappingStrategy` which is also used in `@BeanMapping`, `@IterableMapping` and `@MapMapping` why not add new options to `@Mapper` and `@MapperConfig` that would allow to configure the iterable and map mappings.

e.g. we can add `nullValueIterableMappingStrategy` and `nullValueMapMappingStrategy` that you can use to override the mapping for the iterables / maps.

Then the inheritance for iterables would be the following from top to bottom:

1. `IterableMapping#nullValueMappingStrategy`
2. `Mapper#nullValueIterableMappingStrategy`
3. `Mapper#nullValueMappingStrategy`
4. `MapperConfig#nullValueIterableMappingStrategy`
5. `MapperConfig#nullValueMappingStrategy`

I think that doing it like this will make it clear from the API point of view and won't lead to some weird options like doing `@BeanMapping(nullValueMappingStrategy = NullValueMappingStrategy#RETURN_DEFAULT_COLLECTIONS)`

What do you think @mjustin? Would you also be interested in helping us out with this functionality and providing a PR?

**Comment by mjustin** [comment]
I like that solution well enough: it avoids the combinatorial explosion of types, and makes the user's intentions more explicit.

I could be wrong, but I'm not sure if there's much value in having separate configuration for  maps & iterables.  They're both collection-like, and it seems odd that a user would want one type null but the other type empty.

As for helping/providing a PR, that depends on whether I can carve out the time aside from my other non-work commitments.  I'd love to if I can find the time to help, though I'm not sure when/if that will happen, so I'd say don't rely on it unless I've given indication that I've started working on it.

**Comment by filiphr** [comment]
The reason why I mentioned having difference between iterable and map is because we also have `@IterableMapping` and `@MapMapping`, I know that in most of the cases you want the maps and iterables to be treated the same.

What do you think @sjaakd, should we have one new option in the `@Mapper` and `@MapperConfig` or 2 new options?

**Comment by filiphr** [comment]
>As for helping/providing a PR, that depends on whether I can carve out the time aside from my other non-work commitments. I'd love to if I can find the time to help, though I'm not sure when/if that will happen, so I'd say don't rely on it unless I've given indication that I've started working on it.

No problem, if you have time it would be great. I have anyways put this issue for 1.5.0 and marked it as "good first issue" in case someone else from the community wants to step up and offer support here. Otherwise, we will see how we are with time and do something about it.

**Comment by adwsingh** [comment]
@filiphr I have started working on this. Can you assign this to me to avoid duplicate efforts by someone else.

**Comment by filiphr** [comment]
Thanks for the initiative @adwsingh. I've assigned this to you. Please let us know if you have any questions

**Comment by JudeNiroshan** [comment]
@adwsingh are you working on this issue? If not I can start on this issue. 🙂

cc: @filiphr
