### ISSUE TITLE
How to use mapstruct in maven2 and jdk1.6?

### ISSUE THREAD

**Issue by cityiron** [mapstruct/mapstruct#2509]
I want to use mapstuct to convert DTO to DO, but my project is old, maven2 and jdk 1.6

I only see config like follow:

```xml
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.mapstruct</groupId>
                            <artifactId>mapstruct-processor</artifactId>
                            <version>${org.mapstruct.version}</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
        </plugins>
```

maven2 have no annotationProcessorPaths.

**Comment by hpoettker** [comment]
Support for Java 6 has been dropped with version 1.3. So you'll need to used an older version.

If you browse the `readme.md` for older versions by choosing different tags, you can also find older Maven snippets. See e.g. https://github.com/mapstruct/mapstruct/tree/1.0.0.Final

Please note that is usually preferred if questions like this are asked on Stack Overflow and not on GitHub.

**Comment by filiphr** [comment]
Thanks @hpoettker. 

Indeed since 1.3 MapStruct requires Java 8 in order to compile the code. However, the generated code might still be Java 6 compliant.

In any case, I am not sure about maven2. You'll need to find a way to invoke annotation processors with maven2. However, I would strongly advise you to migrate your project to use maven3. The last release of Maven2 was in 2009, the first release of MapStruct was in 2013 (there won't be any examples of running MapStruct with Maven2 in our repo).

**Comment by cityiron** [comment]
> Support for Java 6 has been dropped with version 1.3. So you'll need to used an older version.
> 
> If you browse the `readme.md` for older versions by choosing different tags, you can also find older Maven snippets. See e.g. https://github.com/mapstruct/mapstruct/tree/1.0.0.Final
> 
> Please note that is usually preferred if questions like this are asked on Stack Overflow and not on GitHub.

Tks.
