### ISSUE TITLE
[Bug] constant mapping is generated dependent on unrelated field

### ISSUE THREAD

**Issue by mickroll** [mapstruct/mapstruct#2523]
Given a mapper:
```java
@Mapper
public interface FaultyMapper {

    @Mapping(target = "inner.ident", constant = "Example value")
    Target map(Source source);

    public class Target {
        private TargetInner inner;

        public TargetInner getInner() {    return inner;    }
        public void setInner(final TargetInner inner) {    this.inner = inner;    }

        public static class TargetInner {
            private String ident;
            private String otherValue;

            public String getIdent() {    return ident;    }
            public void setIdent(final String ident) {    this.ident = ident;    }
            public String getOtherValue() {    return otherValue;    }
            public void setOtherValue(final String otherValue) {    this.otherValue = otherValue;    }
        }
    }

    public class Source {
        private SourceInner inner;

        public SourceInner getInner() {    return inner;    }
        public void setInner(final SourceInner inner) {    this.inner = inner;    }

        public static class SourceInner {
            private String otherValue;

            public String getOtherValue() {    return otherValue;    }
            public void setOtherValue(final String otherValue) {    this.otherValue = otherValue;    }
        }
    }
}
```

Now, because `@Mapping(target = "inner.ident", constant = "Example value")` is mapped explicitely, i would expect it to always be present in the resulting object. But it isn't.

Mapstruct generates the following mapper implementation:
```java
public class FaultyMapperImpl implements FaultyMapper {

    @Override
    public Target map(Source source) {
        if ( source == null ) {
            return null;
        }
        Target target = new Target();
        target.setInner( sourceInnerToTargetInner( source.getInner() ) );
        return target;
    }

    protected TargetInner sourceInnerToTargetInner(SourceInner sourceInner) {
        if ( sourceInner == null ) {
            return null;
        }
        TargetInner targetInner = new TargetInner();
        targetInner.setOtherValue( sourceInner.getOtherValue() );
        targetInner.setIdent( "Example value" );
        return targetInner;
    }
}
```

As you can see, `targetInner.setIdent( "Example value" );` is only called, if `source.inner` is present. This is unintuitive, because of the explicit `constant` mapping.

mapstruct: 1.4.2.Final

**Comment by Zegveld** [comment]
There is a chapter about how mapstruct handles null-values and how you can influence this: https://mapstruct.org/documentation/dev/reference/html/#mapping-result-for-null-arguments 
Perhaps this specific case can become a new NullValueMappingStrategy, or perhaps the `NullValueMappingStrategy.RETURN_DEFAULT` variant already suffices.

Here is a situation when I would not expect it to be always present:
What if you have a mapping that needs to be done where every address that has a car needs to get a value set in the car. The source doesn't contain that field, so I want to use a constant mapping for this. Assume that I've already got a mapping going for the addresses, then I would add `@Mapping (target = "car.lease", constant = "Unknown")` to that mapping.
It would be strange in this context if every address suddenly has a car.

The options that I see for this issue:
1. This becomes the default behavior and there is a NullValueMappingStrategy in which this behavior can be disabled.
2. Default behavior stays the same and the existing NullValueMappingStrategy's suffice.
3. Default behavior stays the same and a new NullValueMappingStrategy is created for this behavior.
4. Something I have not thought of as a solution....

**Comment by filiphr** [comment]
I agree with @Zegveld. I do not think that the constant value being present is expected here. Considering the fact that we do have `NullValueMappingStrategy`.

Your mapper is equivalent to writing:

```
@Mapper
public interface FaultyMapper {

    Target map(Source source);

    @Mapping(target = "ident", constant = "Example value")
    Target.TargetInner map(Source.SourceInner source);
}
```

You can easily achieve what you want by doing:

```
@Mapper
public interface FaultyMapper {

    Target map(Source source);

    @BeanMapping(nullValueMappingStrategy = NullValueMappingStrategy.RETURN_DEFAULT)
    @Mapping(target = "ident", constant = "Example value")
    Target.TargetInner map(Source.SourceInner source);
}
```

or 

```
@Mapper(nullValueMappingStrategy = NullValueMappingStrategy.RETURN_DEFAULT)
public interface FaultyMapper {

    @Mapping(target = "inner.ident", constant = "Example value")
    Target map(Source source);
}
```

Keep in mind that in the second case the `NullValueMappingStrategy` is applied to all the methods.

@Zegveld your proposed options are OK, but I am not sure that it is worth it.

1. This option is quite invasive since it is a change in behaviour that might have quite a big influence. We are usually reluctant in doing such drastic incompatible changes
2. This is the best option and requires no changes in MapStruct. This is what I showed in the examples above.
3. I am not sure that adding a new `NullValueMappingStrategy` is worth the effort. One will need to explicitly set it, and if they are setting a `nullValueMappingStrategy` they can easily set it `NullValueMappingStrategy` in the mapping that they need.


Since I think that Option 2 is the best approach I am going to go ahead and close this issue. Thanks @Zegveld for the analsyis and thanks @mickroll for the detailed explanation.
