### ISSUE TITLE
mapstruct global config

### ISSUE THREAD

**Issue by tonycody** [mapstruct/mapstruct#2539]
Can you refer to Lombok?
Lombok is configured by placing a lombok. Config file in the project root directory.
The way mapstruct is configured in Maven is too coupled to the build tool

**Comment by filiphr** [comment]
You'll need to be a bit more specific @tonycody.

The way you can configured MapStruct is coupled with how you can configure any annotation processor. Different builds tools have different ways of passing arguments to the compiler.

Closing this because we are not interested in providing such a functionality and I am not sure how we can do it with the current API of the annotation processor. If you have an idea please provide a PR showcasing this functionality.
