### ISSUE TITLE
TYPE_USE annotations on method parameters cause them not to match when using errorprone

### ISSUE THREAD

**Issue by facboy** [mapstruct/mapstruct#2541]
When using the errorprone javac compiler (which afaik is based on a newer compiler version than jdk8) Mapstruct gets confused when method parameters have `TYPE_USE` annotations (eg as used in `checker-qual`).  It seems to see the annotated type variable and the unannotated type variable as different types:

```
static <T> Optional<T> toOptional(@Nullable T value) {
    return Optional.ofNullable(value);
}
```

Example project: https://github.com/facboy/mapstruct-bug

**Comment by filiphr** [comment]
Thanks for the reproducible project, it helped locate the bug and will be fixed in PR #2550

A side note. It seems that the way you should use error prone with Java 11+ is slightly different. Not changing the compiler. I read that [here](https://errorprone.info/docs/installation). Using that configuration and using Java 11 to run maven everything seems to work fine.
