### ISSUE TITLE
Produce finals in generated code

### ISSUE THREAD

**Issue by H-Lo** [mapstruct/mapstruct#2602]
When generating mapper methods, finals should be used as none of input parameters or local variables are changed during the process. It can lead to faster and more strict and robust code without any downsides.
It could be the default behaviour or it could be handled by some annotation e.g.

    @UseFinals
    public abstract CountryDTO toDto(Country c);

### Discussed in https://github.com/mapstruct/mapstruct/discussions/2601

<div type='discussions-op-text'>

<sup>Originally posted by **H-Lo** October  1, 2021</sup>
When you create simple mapping

    public abstract CountryDTO toDto(Country c);

generated code have no finals. Is there a way to get a finals in generated code?

    @Override
    public CountryDTO toDto(Country c) {
        if ( c == null ) {
            return null;
        }
        CountryDTO countryDTO = new CountryDTO();
        countryDTO.setId( c.getId() );
        countryDTO.setName( c.getName() );
        countryDTO.setStatus( c.getStatus() );
        return countryDTO;
    }
    
Desired code:
    
    @Override
    public CountryDTO toDto(   **final**   Country c) {
        if ( c == null ) {
            return null;
        }
        **final**   CountryDTO countryDTO = new CountryDTO();
        countryDTO.setId( c.getId() );
        countryDTO.setName( c.getName() );
        countryDTO.setStatus( c.getStatus() );
        return countryDTO;
    }</div>

**Comment by filiphr** [comment]
As I said in the #2601 discussion. Since Java 8, Java has effectively final parameters. Therefore, I do not see why we adding it explicitly will lead to faster code. Please provide some benchmarks showing that the code is slower without `final`.

There is a downside about this though, the code is more verbose and it is more difficult in reading this code.

Let's keep the discussion in the #2601 discussion and close this issue for now.
