### ISSUE TITLE
Issue with qualifiedByName used together with defaultValue

### ISSUE THREAD

**Issue by RHarryH** [mapstruct/mapstruct#2636]
- [x] Is this an issue (and hence not a question)? 

Hello,

Today I decided to upgrade `mapstruct` from `1.3.1.Final` to `1.4.2.Final` and my code stopped to work. I also chcecked `1.5.0.Beta1` and from my perspective the behavior is still wrong. For following mapping:

```java
@Mapping(source = "folder.ancestor.id", target= "parent", defaultValue = "#", qualifiedByName = "uuidToString")
DirectoryNode convert(Folder folder);

@Named("uuidToString")
default String uuidToString(UUID id) {
    return id.toString();
}
```
I'm getting following results:

`1.3.1.Final` **Expected behavior**
```java
if ( folderAncestorId( folder ) != null ) {
    directoryNode.setParent( uuidToString( folderAncestorId( folder ) ) );
}
else {
    directoryNode.setParent( "#" );
}
```
`1.4.2.Final`

The code generating fails with following error
`Can't map "#" to "String parent"`

`1.5.0.Beta1`
```java
UUID id = documentFolderId( document );
if ( id != null ) {
    directoryNode.setParent( uuidToString( id ) );
}
else {
    directoryNode.setParent( uuidToString( UUID.fromString( "#" ) ) );
}
```

`#` is not a correct `UUID` but from my perspective it is the correct indicator of directory root. I don't want to call my named method when applying the default value. I just want to set the value when `id` is `null`.

**Comment by Zegveld** [comment]
Thank you for reporting this issue. I agree that it should indeed just take the default-value as specified instead of attempting to convert it if there is no conversion needed.

I've created a PR for it, and hope to have it fixed in the 1.5.0.Beta2 or if it does not make that one then the 1.5.0 release.

**Comment by RHarryH** [comment]
Many thanks for such fast reaction.

**Comment by filiphr** [comment]
This is a tricky one @RHarryH.

Lets take this example


```java
@Mapper
public interface MyMapper {

    @Mapping(target = "name", source = "firstName", defaultValue = "unknown", qualifiedByName = "uppercase")
    Customer map(CustomerDto dto);

    @Named("uppercase")
    default String uppercase(String value) {
        return value == null ? null : value.toUpperCase(Locale.ROOT);
    }
}
```

Here MapStruct will generate

```java
if ( dto.getFirstName() != null ) {
    customer.setFirstName( uppercase( dto.getFirstName() ) );
}
else {
    customer.setFirstName( uppercase( "unknown" ) );
}
```

The reason why it worked in your case was due to a bug in the way we handled qualifiers for direct assignments and combined with 2 steps. We did work for this in #1714.

One can argue that what was in 1.3.1.Final was not super expected, especially if you take my example (that works in 1.3).

We are still discussing with the team how to proceed with this one and whether we can do something about it. In the meantime you can do one of the following:

### Add custom mapping method
```java
@Named( "uuidToString" )
default String defaultUuidToString(String value) {
    return value;
}
```

### Use `defaultExpression`
```java
@Mapping( source = "folder.ancestor.id", target = "parent", defaultExpression = "java(\"#\")", qualifiedByName = "uuidToString" )```

**Comment by sjaakd** [comment]
documenation has been updated to provide explanation for this case.
