### ISSUE TITLE
cannot find symbol for generic type while using 1.5.0.beta1

### ISSUE THREAD

**Issue by belligerent** [mapstruct/mapstruct#2639]
- [✓] Is this an issue (and hence not a question)? 

I have a generic interface like this

```Java
public interface Service<T> {
}
```

when use 1.4.2.Final it works fine
```Java
public class ServiceImpl implements Service {
    public ServiceImpl() {
    }
}
```

but when I switch to 1.5.0.Beta1, it will generate
```Java
public class ServiceImpl implements Service<T> {
}
```

which will cause an error:cannot find symbol symbol: class T

**Comment by filiphr** [comment]
@belligerent I believe that this is identical to #2638.

See https://github.com/mapstruct/mapstruct/issues/2638#issuecomment-959199444.

Why do you need MapStruct to generate something for a generic interface? What is done in 1.4.2.Final is not correct since generic types are lost. 

Can you please provide a better example. I can imagine that you do not use MapStruct to generate you empty classes.

**Comment by belligerent** [comment]
> @belligerent I believe that this is identical to #2638.
> 
> See [#2638 (comment)](https://github.com/mapstruct/mapstruct/issues/2638#issuecomment-959199444).
> 
> Why do you need MapStruct to generate something for a generic interface? What is done in 1.4.2.Final is not correct since generic types are lost.
> 
> Can you please provide a better example. I can imagine that you do not use MapStruct to generate you empty classes.


Thanks for reply, I now understand what's going wrong here.
