### ISSUE TITLE
Unmapped source property with expression mapping and unmappedSourcePolicy =  ReportingPolicy.ERROR

### ISSUE THREAD

**Issue by psloboda** [mapstruct/mapstruct#2646]
When the unmappedSourcePolicy =  ReportingPolicy.ERROR is used, and in the Mapping annotation the expression is used to map some field. There should not be an error witgh information 'Unmapped source property...."

Example of code:
```
@Mapper(unmappedSourcePolicy =  ReportingPolicy.ERROR, componentModel = "spring")
public interface RequestMapper {

    @Mapping(target = "userRoles", expression = "java(map(partnerSearchRequest.getUserRoles()))")
    SearchRequest map(SearchRequestDto searchRequest);

    default List<UserRole> map(UserRoleDto userRole) {
        List< UserRole > userRoles = new ArrayList<>();
        if (userRole != null) {
            userRoles.add(UserRole.fromValue(userRole.name()));
        }
        return userRoles;
    }
}

public class SearchRequestDto {
    
    private UserRoleDto userRoles;

    public UserRoleDto getUserRoles() {
        return userRoles;
    }

    public void setUserRoles(UserRoleDto userRoles) {
        this.userRoles = userRoles;
    }
}

public class SearchRequest {

    private List<UserRole> userRoles;

    public List<UserRole> getUserRoles() {
        return userRoles;
    }

    public void setUserRoles(List<UserRole> userRoles) {
        this.userRoles = userRoles;
    }
}

```

**Comment by Zegveld** [comment]
Taking this as an example: it is because mapstruct will not interpret the expression you have put there. So whatever the expression is will not be linked to a source element. You can add the `@BeanMapping( ignoreUnmappedSourceProperties = { "userRoles" } )` to the mapping method to have it remove the error because you know it is handled inside the expression. ( The `{`, `}` should be optional for a single value. )

Also in the above situation you do not need to specify the `@Mapping` at all. Mapstruct will notice that the map method exists inside the mapper and use that one for mapping the userRoles.

**Comment by filiphr** [comment]
Closing this because @Zegveld explained how this works.
