### ISSUE TITLE
Nested mapping and ignoreUnmappedSourceProperties

### ISSUE THREAD

**Issue by robp94** [mapstruct/mapstruct#2648]
When using `unmappedSourcePolicy = ReportingPolicy.ERROR`, not explicitly defining nested mappings and using `ignoreUnmappedSourceProperties` you run into an error which is not really clear how to solve.

It seems that annotation `@BeanMapping(ignoreUnmappedSourceProperties = "...")` is handed down to all automatically generated mapping methods and likewise applied there. This results in one or multiple errors like `Ignored unknown source property: ` although it is correct for the method where the annotation is used.

If it is wanted that the configuration of the annotation is handed down maybe we could enhance the error message or the Javadoc. Maybe we could add the name of the method, so it would be clear that the error is at a nested method?

Small example of the problem:
[mapstruct-field-mapping.zip](https://github.com/mapstruct/mapstruct/files/7498213/mapstruct-field-mapping.zip)

**Comment by tarunmanchanda** [comment]
Is this problem solved? I am also getting this error where it says Ignore unknown source and couldn't find that property. How do I ignore some fields that are not available in target.

**Comment by filiphr** [comment]
I believe that this is the same as #2743 which was fixed in 1.5.3. 

@tarunmanchanda I am not sure if you are having the same problem, but I would suggest trying out 1.5.3 and if you are still having an issue please create a new issue.

@robp94 same story, please try out 1.5.3 and if you are still experiencing a problem, let us know.
