### ISSUE TITLE
method's param Case problem

### ISSUE THREAD

**Issue by wjzxc123** [mapstruct/mapstruct#2656]
```
@Mapping(target = "userId.userId",source = "userId")
@Mapping(target = "accountId.accountId",source = "accountId")
@Mapping(target = "accountNumber.accountNumber",source = "accountNumber")
@Mapping(target = "available.amount",source = "available")
@Mapping(target = "available.currency",expression = "java(Currency.getInstance(accountPo.getCurrency()))")
@Mapping(target = "dailyLimit.amount",source = "dailyLimit")
@Mapping(target = "dailyLimit.currency",expression = "java(Currency.getInstance(accountPo.getCurrency()))")
@Mapping(target = "currency",expression = "java(Currency.getInstance(accountPo.getCurrency()))")
Account toAccount(AccountPO accountPo) throws Exception;
```

```
public class Account {
	private UserId userId;
	private AccountId accountId;
	private AccountNumber accountNumber;
	private Money available;
	private Money dailyLimit;
	private Currency currency;
}
```

```
public class Money {
	private BigDecimal amount;
	private Currency currency;
}
```
Class
```
protected Money accountPOToMoney(AccountPO accountPO) {
        if ( accountPO == null ) {
            return null;
        }

        BigDecimal amount = null;

        amount = accountPO.getAvailable();

        Currency currency = Currency.getInstance(accountPo.getCurrency());

        Money money = new Money( amount, currency );

        return money;
    }
```
param name  is **accountPO** ,but use **accountPo**

Is this a bug?

**Comment by Zegveld** [comment]
It is not a bug, but a difference in the casing of parameters, combined with the use of expressions.

Mapstruct uses the class name in the generated methods but then with a lowercase starting letter to create the parameter name. In your case this would turn `AccountPO` into `accountPO`. But in your defined method it is `accountPo`. For everything that mapstruct generates this will work correctly. 

But in your case you use an expression to supply the way the currency field should be created and there you have defined it as being `accountPo`. The mapstruct generated method with `accountPO` doesn't match due to this reason. You can fix this in a few ways:

1. Rename the parameter and change the expressions so that they use `accountPO` instead of `accountPo`.
2. (Recommended) Create a helper method for creating the currency and use `source` instead of `expression`.

Here is an example for the recommended solution:
```
@Mapping(target = "userId.userId",source = "userId")
@Mapping(target = "accountId.accountId",source = "accountId")
@Mapping(target = "accountNumber.accountNumber",source = "accountNumber")
@Mapping(target = "available.amount",source = "available")
@Mapping(target = "available.currency",source = "currency")
@Mapping(target = "dailyLimit.amount",source = "dailyLimit")
@Mapping(target = "dailyLimit.currency",source = "currency")
@Mapping(target = "currency", source="currency") // this one is now optional as both target and source are the same. Mapstruct will create a mapping for this even when not specified.
Account toAccount(AccountPO accountPo) throws Exception;

// I assumed that the currency source field would be a String, if it is something else then adjust the parameter accordingly.
default Currency toCurrency(String value) {
    return Currency.getInstance(value);
}
```
Mapstruct will notice that a method is available to convert to the `Currency` object and use that.

Hope this helps.

**Comment by wjzxc123** [comment]
Thank you for your answer. The problem has been solved. Thank you very much!

**Comment by filiphr** [comment]
@wjzxc123 if you are using `java.util.Currency` then I would suggest upgrading MapStruct to 1.3 or newer. In 1.3 we added support for implicit support for conversion between `java.uti.Currency` and `String`.
This would mean that you will not need the `toCurrency` method from the example of @Zegveld. This was done in #1355.

If your `Currency` object is something else, then the example from @Zegveld is the way to go.
