### ISSUE TITLE
when compiling, I get an exception: GC overhead limit exceeded

### ISSUE THREAD

**Issue by sapphireHL** [mapstruct/mapstruct#2659]
I try to use mapstruct in our company's project, but when I import mapstruct in my build.gradle, I can't get my project compile successfully, it tells me: GC overhead limit exceeded. And when I remove mapstruct dependency in build.gradle, project can be compiled successfully. 
I use jprofiler to analyze hprof file and discover that the biggest object is lombok
![image](https://user-images.githubusercontent.com/23159360/142427251-156028ff-d420-4002-b5d3-125118a8c071.png)

here is some of my build.gradle file:
`implementation 'org.mapstruct:mapstruct:1.4.2.Final'
    implementation 'org.mapstruct:mapstruct-processor:1.4.2.Final'`
and lombok version is 1.18.12

can anyone help me with this problem?

**Comment by sapphireHL** [comment]
and my gradle version is 4.10

**Comment by filiphr** [comment]
How is this a MapStruct problem? You just showed that Lombok is the one that uses the most memory.

I would suggest upgrading your Gradle version, since it is really old and upgrading Lombok and trying again. If you are having problems with Lombok I would suggest raising an issue in their issue tracker.
