### ISSUE TITLE
Mapstruct unable to create Beans when using AnnotationBeanNameGenerator

### ISSUE THREAD

**Issue by arnabsarkardhn** [mapstruct/mapstruct#2717]
I am working on a project where my application uses several third party jars which are built on spring-core. These jars have duplicate class names hence, I am using AnnotationBeanNameGenerator to register these bean-names uniquely by giving them fully-qualified-path name. Now, my application also have mapstruct. I can see the mapstruct is not able create beans. Though, the mapstruct impl classes are properly generated in target folder. 
**NOTE**: Earlier the mapstruct was working all fine. When I introduced AnnotationBeanNameGenerator, it started throwing error at runtime. 
The error stack clearly says that mapper beans are not getting created.
How shall I create mapper beans manually?? 

For unique Bean name generation here is the code:
```
public class UniqueBeanNameGenerator extends AnnotationBeanNameGenerator {

    @Override
    public String generateBeanName(BeanDefinition definition, BeanDefinitionRegistry registry) {
        String val = definition.getBeanClassName();
        logger.info(val);
        return val;
    }
}
```

Mapstruct code:
```
@Mapper(componentModel = "spring")
    public interface PayloadConversion {
    
        
        TargetPayload mapFrom(SourcePayload req);
}
```

Usage of MapStruct:
```
@Component
public class ConvertType {

    @Inject
    private PayloadConversion convert;
  
}
```

App start class:
```
@SpringBootApplication
@ComponentScan(nameGenerator=UniqueBeanNameGenerator.class)
public class Application {
   public static void main(String[] args) {
       SpringApplication.run(Application.class, args);
   }
}
```

Error stack during app start:
```
***************************
APPLICATION FAILED TO START
***************************

Description:

Field mapper in com.dataconversion.ConvertType required a bean of type 'com.dataconversion.PayloadConversion' that could not be found.


Action:

Consider defining a bean of type 'com.dataconversion.PayloadConversion' in your configuration.


```

**Comment by Zegveld** [comment]
I've got the following questions concerning this issue:

1. In what packages does your application live and do the generated mapper implementation classes live?
2. Do the generated mapper implementation classes contain the `@Component` annotation or any derivative thereof?
3. Can you test if this only applies to mapstruct beans, for example by replacing the PayloadConversion field with another bean for which the implementation is not generated by mapstruct?

Concerning manually creating beans (**not recommended**) :
I'm not that familiar with how spring handles beans exactly, but I think it was something like:
```
@Bean
public PayloadConversion getPayloadConversion() {
    return org.mapstruct.Mappers.getMapper( PayloadConversion.class );
}
```
and put this inside a class that is found with the component scanning.

Also noticed on this stackoverflow question that someone used a different way of configuring the nameGenerator: https://stackoverflow.com/questions/63722709/springboot-configuring-beannamegenerator-to-use-qualifier-names
instead of adjusting the `@ComponentScan` they adjust the entire application:
```
ApplicationContext ctx = new SpringApplicationBuilder(Application.class)
            .beanNameGenerator(new UniqueBeanNameGenerator())
            .run(args);
```

Hope that some of this is useful to get it working.

**Comment by filiphr** [comment]
Thanks @Zegveld for providing a detailed explanation for this question. I am going to go ahead and close it this issue now.

**Comment by mohamed-taha-1** [comment]
just @Mapper(componentModel = "spring") it is not default to be seen by spring application

**Comment by filiphr** [comment]
@mohamed-taha-1 please do not comment on old closed issues. If you have some question feel free to create a discussion
