### ISSUE TITLE
Support decorators with the CDI component model

### ISSUE THREAD

**Issue by gunnarmorling** [mapstruct/mapstruct#272]
MapStruct decorators should be mapped to actual CDI decorators when working with componentModel="cdi".

**Comment by sjaakd** [comment]
@sonata82 , any progress on this? Anything I can do to help?

**Comment by sonata82** [comment]
I've created a solution for CDI using [Decorator and Delegate annotations](http://docs.oracle.com/javaee/6/api/javax/decorator/package-summary.html) - or so I thought, because my integrationtest is still failing.

I don't have a good solution for Spring yet. Please feel free to have a look at [my code](https://github.com/sonata82/mapstruct/tree/cdi_decorator/) and tell me if I'm going into the wrong direction ^^

**Comment by gunnarmorling** [comment]
Hi @sonata82, sorry for the late reply, I somehow missed your last comment. Could you rebase your branch to the current master and submit a pull request? Then we can see the exact change and can discuss it right in place. No worries about Spring, if we got a working solution for CDI, that'd already by a good step forwards. Thx!

**Comment by gunnarmorling** [comment]
> I've created a solution for CDI using Decorator and Delegate annotations

Yes, that's the right way.

Btw. I just took a quick look at your branch, shouldn't `SourceTargetMapperDecorator` be annotated with the @Decorator annotation? And do we actually have to generate two classes in this case? I'd expect CDI to take care of marrying the mapper bean and the manually written decorator. The two classes we currently generate should only be required with the default component model where we need to take care of the decorator application ourselves.

You might start by writing all the required classes from hand so you have a working example as a basis. Then you could think about which of these should be generated by MapStruct.

**Comment by gunnarmorling** [comment]
Done. Thanks a lot, @sonata82!
