### ISSUE TITLE
Duplicate null check while mapping non-iterable to iterable when CollectionMappingStrategy = ADDER_PREFERRED

### ISSUE THREAD

**Issue by amseager** [mapstruct/mapstruct#2799]
Assume the following mapper:

```
@Mapper(collectionMappingStrategy = CollectionMappingStrategy.ADDER_PREFERRED)
public interface MyMapper {

  @Mapping(target = "myClassText", source = "text")
  @Mapping(target = "myClassItems", source = "sourceItems")
  MyClass map(String text, Collection<SourceItem> sourceItems);
}
```
In this case, something like that will be generated:
```
...
 if ( sourceItems != null ) {
    if ( sourceItems != null ) {
        for ( SourceItem sourceItem : sourceItems ) {
            myClass.addMyClassItem( toMyClassItem( sourceItem ) );
        }
    }
}
...
```
This can cause minor troubles like Sonar warning etc.

I'm using mapstruct 1.4.2.Final

**Comment by Zegveld** [comment]
Thank you for the bug report.

I can indeed reproduce this with `1.4.2.Final`, but not with `1.5.0.RC1` using the exact same scenario.
this issue could be related to #2023, which was fixed in `1.5.0.Beta1`.

Therefor closing this issue.
If you can reproduce this in `1.5.0.RC1` feel free to reopen this issue with a minimal reproduction scenario that includes source/target classes.
