### ISSUE TITLE
mapstruct-lombok：This format is not supported. eg:cTime. The first letter is lowercase and the second letter is uppercase.

### ISSUE THREAD

**Issue by zhoulitong** [mapstruct/mapstruct#2832]
- [ ] Is this an issue (and hence not a question)? 

If this is a question how to use MapStruct there are several resources available.
- Our reference- and API [documentation](http://mapstruct.org/documentation/reference-guide/).
- Our [examples](https://github.com/mapstruct/mapstruct-examples) repository (contributions always welcome)
- Our [FAQ](http://mapstruct.org/faq/)
- [StackOverflow](https://stackoverflow.com), tag MapStruct 
- [Gitter](https://gitter.im/mapstruct/mapstruct-users) (you usually get fast feedback)
- Our [google group](https://groups.google.com/forum/#!forum/mapstruct-users)

**Comment by zhoulitong** [comment]
![image](https://user-images.githubusercontent.com/22739017/165492321-903e4906-b82f-4307-ba70-175e9dd71443.png)

**Comment by Zegveld** [comment]
MapStruct follows the java bean specification for this.

[java bean specification](https://www.oracle.com/java/technologies/javase/javabeans-spec.html) has the following to say about this: 
`8.8 Capitalization of inferred names.`
`Thus when we extract a property or event name from the middle of an existing Java name, we normally convert the first character to lower case. However to support the occasional use of all upper-case names, we check if the first two characters of the name are both upper case and if so leave it alone.`

In this case you have a method called `getCTime()`, which after removing the get/set part results in `CTime`. Of this we take the first two characters `CT`, since they are uppercase we leave it alone and end up with the property `CTime`.

Closing this issue since addressing it as `CTime` for mapstruct is correct.
