### ISSUE TITLE
Which package do you usually put Mapper in, it is easy to conflict with the Mapper of mybatis, and will be scanned by mybatis

### ISSUE THREAD

**Issue by liunancun** [mapstruct/mapstruct#2910]
Which package do you usually put Mapper in, it is easy to conflict with the Mapper of mybatis, and will be scanned by mybatis

**Comment by Zegveld** [comment]
Also in gitter a same kind of question got asked:

kliarist
@kliarist
[20:15](https://gitter.im/mapstruct/mapstruct-users?at=62bb45333bbb384889bfa228)
I am guessing this question has come up before. Where should I be injecting my mappers? In the presentation layer (controllers) or application layer (services)? What is the best practice when it comes to DTOs? Shall they only be present on controllers or be used as input/output for methods in the services
Raimund Klein
@Chessray
[21:08](https://gitter.im/mapstruct/mapstruct-users?at=62bb51c81227f62be3e2b539)
That depends entirely on your general architecture approach. My personal favourite is proper DDD combined with a Ports and Adapters architecture. In that scenario, I've got mappers between REST layer DTOs and domain objects in the Controllers and mappers between domain objects and adapter value objects in the respective adapter modules.

Also converting this to a discussion since it is not an issue.
