### ISSUE TITLE
Support regular expressions in @Mapping#source / @Mapping#target

### ISSUE THREAD

**Issue by agudian** [mapstruct/mapstruct#292]
Sjaak mentioned that idea, but I think we didn't have an issue for this, so here it comes:

It would be great if we could use regular expressions for `source` and/or `target` (and likewise in `expression` and `constant`)

One use case is that you might want to ignore all properties ending with "Internal". Or map any `(.*)Obj` properties to `\1`. Or for enum mappings, map any `_([0-9]+)` to `NUM_\1`.

That would also be a great addition to what #168 (`@GlobalMapping` configuration) introduces.

The question is: would we try to auto-detect if source or target contain reg-exp stuff? Or should we do it similar to what we do in the `expression` attribute, e.g. to distinguish the following two variants (for a mapping method with several source objects):
`@Mapping( source="inputBean1.fooObj" )` vs `@Mapping( source="regExp( inputBean1\.(.+)Obj )" )`

I'd suggest that groups may only be defined in a regular expression in `source`, but those matched groups should be allowed to be referenced in `target`, `expression` and `constant`.

**Comment by gunnarmorling** [comment]
Tbh. I'm no big fan of this. Using reg exps for mapping selection doesn't really fit with MapStruct's general philosophy of predictability and ease of use. Also I think the most use cases are covered with the prototype mapping mechanism we have now. I'd this be inclined to close this issue. WDYT?

**Comment by shawnrusaw-wf** [comment]
This would be useful when mapping to Apache Thrift generated objects (https://thrift.apache.org/).

Given the following Thrift structure for a `TThing`

```
struct TThing
{
  1: i32 field1
  2: string field2
}
```

the Thrift compiler generates some boilerplate around "is set" for EVERY field

```
  /** Returns true if field field1 is set (has been assigned a value) and false otherwise */
  public boolean isSetField1() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __FIELD1_ISSET_ID);
  }

  public void setField1IsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __FIELD1_ISSET_ID, value);
  }
```

When mapping from a `Thing`

```
@Data // lombok
public class Thing {
  private int field1;
  private String field2;
}
```

we need to stack a bunch of `@Mapping` to ignore these "is set" fields.

```
@Mapper
public interface ThingMapper {
  @Mapping(target = "field1IsSet", ignore = true)
  @Mapping(target = "field2IsSet", ignore = true)
  TThing map_Thing_to_TThing(Thing thing);
}
```

in order to avoid 

```
Warning:(8, 10) java: Unmapped target properties: "field1IsSet, field2IsSet".
```

Using `ReportingPolicy.IGNORE` is too severe, since we want to be alerted to mapping issues that do not include "is set" fields. The `MappingExclusionProvider` SPI does not seem to match either.

A regex on `target` seems like it would accomplish this, with minimal cruft.

```
@Mapper
public interface ThingMapper {
  @Mapping(target = "^.*IsSet$", ignore = true) // proposed api, not actually supported
  TThing map_Thing_to_TThing(Thing thing);
}
```

**Comment by fred01** [comment]
Same with GRPC/Protobuf generated entities, they bloated with service fields, so eventually it's better to avoid use mapStruct and manual mapping instead ignoring bunch of target fields. Maybe consider adding some kind of TargetFieldResolver in @Mapping, @MappingConfig, so @shawnrusaw-wf can be implement it with regex, i can implement it with list of grpc service fields. I think it make sense and don't break MapStruct's philosophy

**Comment by nettadhp** [comment]
Is there any intention on implementing this? As fred mentioned, it would be super useful with grpc/protobuf generated entities.

**Comment by filiphr** [comment]
This is a really old issue. I am not too keen on complicating our API to support things like this.

We already have the `AccessorNamingStrategy` that can be used to expand on certain things.

I know that there is the [mapstruct-spi-protobuf](https://github.com/entur/mapstruct-spi-protobuf) (Note: this is not maintained by the MapStruct team). 

We can of course extend our API in order to facilitate better integration with grpc/protobuf entities if there is a request for that from the community

**Comment by nobei** [comment]
when i use thrift, i also need this function to avoid some mistakes. Can suppor it @filiphr

**Comment by BernhardBln** [comment]
Same problem here, when using Lombok's [@With](https://projectlombok.org/features/With) (which I do a lot for immutable objects).

Would need something like `@Mapping(target="with[A-Z].*", ignore=true)`

**Comment by filiphr** [comment]
@BernhardBln we have the `AccessorNamingStrategy` that you can use to ignore all Lombok `@With` methods. See [Custom Accessor Naming Strategy](https://mapstruct.org/documentation/stable/reference/html/#_custom_accessor_naming_strategy) in our documentation.

@nobei if something special is needed for thrift it can certainly be achieved with `AccessorNamingStrategy` as well.

Closing this as not planned
