### ISSUE TITLE
Private collection field with getter gives incorrect compilation error

### ISSUE THREAD

**Issue by andye2004** [mapstruct/mapstruct#2952]
Erroneous `Unmapped target property` compilation error when private collection field has a `get` method but no `set` method. 

Versions: Java 11, Mapstruct 1.5.2-Final.

Given the following classes:

```java
public class Source {
    private String sourceField;

    public Source() {
        // no-op
    }

    public String getSourceField() {
        return sourceField;
    }

    public void setSourceField(String sourceField) {
        this.sourceField = sourceField;
    }
}

public class Target {
    private final Map<String, String> attributes = new HashMap<>();
    private String targetField;

    public Target() {
        // no-op
    }

    public Map<String, String> getAttributes() {
        return attributes;
    }

    public String getTargetField() {
        return targetField;
    }

    public void setTargetField(String targetField) {
        this.targetField = targetField;
    }
}

@Mapper
public interface S2TMapper {
    @Mapping(target = "targetField", source = "sourceField")
    Target map(Source source);
}
```
When the compiler is run we get the following compilation error.

![image](https://user-images.githubusercontent.com/15898957/183594110-bb339b17-7967-43df-b0e7-0a4d9be5e83d.png)

If the `getAttributes` method is ommitted, everything compiles fine, so it seems Mapstruct mistakenly believes the field should be writable on the basis that it has an accessor.

NOTE: I haven't tested this with other collection type classes.

Reporoducible project [here](https://github.com/andye2004/mapstruct-issue.git)

**Comment by andye2004** [comment]
Apologies all, having dug into the docs more, it seems this behaviour is expected.

**Comment by filiphr** [comment]
Thanks for your analysis @andye2004. Have you seen `CollectionMappingStrategy.TARGET_IMMUTABLE`? I think that this should achieve what you are looking for (conceptually). I am saying conceptually, because I tried it on your example and it still complains about the unmapped property and if I add another `attributes` map to the `Source` then we have an error like

> No write accessor found for property "attributes" in target type.

I've created https://github.com/mapstruct/mapstruct/issues/2967 in order to track this bug and fix it. Therefore, I am closing this one. Is that OK with you?
