### ISSUE TITLE
Method annotate with AfterMapping is not called

### ISSUE THREAD

**Issue by kris2kris** [mapstruct/mapstruct#2955]
Method annotate with `@AfterMapping` is no more called in 1.5.2.Final version when using a method with 2 arguments.
It works in 1.4.2.Final and it works when using a method with one argument and an object returned.
Example:
```
void updateDomain(MyDto dto, @MappingTarget MyDomain domain);

@AfterMapping
public default MyDomain doAfterMapping(@MappingTarget MyDomain domain, MyDto dto) {
    return domain;
}
```

**Comment by filiphr** [comment]
This is a tricky one @kris2kris.

When you have such an `@AfterMapping` we are invoking it and if the returned result is not `null` then we return from the original method the returned type.

However, in this case the return type of the `updateDomain` method is `void`. If I change it to `MyDomain` then the after mapping method is invoked. The method is also invoked if you change the return type of the `doAfterMapping` from `MyDomain` to `void`.

Nevertheless, we are going to look into this issue to figure out why the functionality changed.

**Comment by filiphr** [comment]
I did some analysis on this one and the problem is the changes we've done in our improved generics matching in PR #2320. More precisely the change in the `TypeSelector` and the usage of the `returnType` there (which is `void`).

@sjaakd what do you think we should do to fix this? I tried replacing the use of the `returnType` with `mappingTargetType`, but then the `BuilderLifecycleCallbacksTest` fails because it doesn't invoke `afterWithBuilderTargetReturningTarget`. We discussed in the original PR and what I said in https://github.com/mapstruct/mapstruct/pull/2320#issuecomment-782834648

>I think that what you are doing is correct there. However, we need to provide this information when we are gathering the `@BeforeMapping` and `@AfterMapping` lifecycle methods and call it twice, once with the final type and once with the builder. However, I think that this is not that easy with our current setup.

**Comment by Zegveld** [comment]
I've attempted to fix this, and currently believe that we should not fix this.

The reason lies in the differences between the 2 mapping flows:
Normal Mapping flow:
(not entirely certain of the order of the beforeMappings compared to eachother or the afterMappings compared to eachother.)
```java
Object method( Object source ) {
    beforeMapping( source );
    result = beforeMapping( source );
    if ( result != null ) {
        return result;
    }
    // create result object
    beforeMapping( source, result );
    result1 = beforeMapping( source, result );
    if ( result1 != null ) {
        return result1;
    }
    // do Mapping
    result2 = afterMapping( source, result );
    if ( result2 != null ) {
        return result2;
    }
    afterMapping( source, result );
    result3 = afterMapping( result );
    if ( result3 != null ) {
        return result3;
    }
    afterMapping( result );
    return result;
}
```
Update Mapping flow:
```java
void method( Object source, @MappingTarget Object mappingTarget ) {
    beforeMapping( source );
    beforeMapping( source, mappingTarget );
    // do mappings
    afterMapping( source, mappingTarget );
    afterMapping( mappingTarget );
}
```

The major difference here is the null-checks. With the update mapping flow you do not get any null-checks.

When also supporting returnType before/aftermappings you will get the following flow for UpdateMappings:
```java
void method( Object source, @MappingTarget Object mappingTarget ) {
    beforeMapping( source );
    result = beforeMapping( source );
    if ( result != null ) {
        return; // mappingTarget has not been adjusted.
    }
    // create result object
    beforeMapping( source, result );
    result1 = beforeMapping( source, result );
    if ( result1 != null ) {
        return; // mappingTarget has not been adjusted.
    }
    // do Mapping
    result2 = afterMapping( source, result );
    if ( result2 != null ) {
        return;  // mappingTarget has been mapped, but because there is a result other afterMappings are not called.
    }
    afterMapping( source, result );
    result3 = afterMapping( result );
    if ( result3 != null ) {
        return;  // mappingTarget has been mapped, but because there is a result not all afterMappings are called.
    }
    afterMapping( result );
    return result;
}
```

It suddenly becomes unpredictable which `@AfterMapping`s are called and which are not.
As for the `@BeforeMapping`s, these will suddenly make it so that the `@MappingTarget` is not mapped at all.

My suggestion would be to use `Context` classes and create a separate `UpdateMapper`.
For example:
```java
class Context {
    @AfterMapping
    ReturnType method( Object source, @MappingTarget ReturnType target ) {
        // impl
    }
}
```
and
```java
class UpdateContext extends Context{
    @AfterMapping
    void updateMethod( Object source, @MappingTarget ReturnType target ) {
        method( source, target);
    }
}
```

If we do choose to fix this then my suggestion would be to also change it as follows:
```java
void method( Object source, @MappingTarget Object mappingTarget ) {
    beforeMapping( source );
    beforeMapping( source ); // with returntype but we ignore it.
    beforeMapping( source, mappingTarget );
    beforeMapping( source, mappingTarget ); // with returntype but we ignore it.
    // do mappings
    afterMapping( source, mappingTarget ); // with returntype but we ignore it.
    afterMapping( source, mappingTarget );
    afterMapping( mappingTarget ); // with returntype but we ignore it.
    afterMapping( mappingTarget );
}
```
and also give a warning that before-/afterMappings are used but the returned value is ignored.

wdyt @filiphr ?

**Comment by filiphr** [comment]
>I've attempted to fix this, and currently believe that we should not fix this.

I disagree with this @Zegveld. This used to work reliably and we should fix it in order for this to work as it used to work. There should be no difference between the update and regular mappings in the way the lifecycle methods are handled.

>It suddenly becomes unpredictable which `@AfterMapping`s are called and which are not.
As for the `@BeforeMapping`s, these will suddenly make it so that the `@MappingTarget` is not mapped at all.

The lifecycle with return values was done in order to facilitate support for cyclic mappings. If you are comparing something I would suggest comparing the code generated in 1.4 vs 1.5. We should be generating the same code

**Comment by Zegveld** [comment]
I did indeed not think about the cyclic mappings. To support those the flow with returning early is wanted.
Guess I'll continue with the route already taken and add tests for cyclic mappings to the code.
