### ISSUE TITLE
Can provide converter between enum and int 

### ISSUE THREAD

**Issue by Ikki-Dai** [mapstruct/mapstruct#2963]
provide enum copy to int and int copy to enum 
such as Mybatis EnumOrdinalTypeHandler

```
int  = enums.ordinal()

enums.values()[int]
```

**Comment by filiphr** [comment]
This is a good enhancement @Ikki-Dai. Thanks for raising it.

Would you be interested in providing this functionality through a PR? This issue is a good one for anyone that is interested in contributing to MapStruct. Therefore, if @Ikki-Dai is not interested in providing a PR, please reach out to us in this issue if you would like to work on this.

**Comment by jccampanero** [comment]
If  @Ikki-Dai is not interested in providing this functionality through a PR himself, I would be glad to help you with this issue.

**Comment by filiphr** [comment]
Thanks for the offer @jccampanero. I am going to wait until Friday for @Ikki-Dai  in case they are interested. Otherwise, I'll assign the issue to you

**Comment by Ikki-Dai** [comment]
Thanks @jccampanero and @filiphr, I have no time to provide PR these days. and @jccampanero,  pls do it.

I'm glad to provide some advice and review, if i have spare time.

**Comment by filiphr** [comment]
Thanks for letting use know @Ikki-Dai. @jccampanero I've assigned this issue to you let us know if you need some pointers

**Comment by jccampanero** [comment]
Sorry for the late reply.

Thank you very much @Ikki-Dai, and thank you very much you too @filiphr.

I will try to do my best to implement the required functionality. I will contact you if I need any help.

Thank you both very much again.

**Comment by liuxiansheng990710** [comment]
@filiphr On the basis of mapstruct, I realized the conversion of enum and int. May I have a try?

**Comment by filiphr** [comment]
@liuxiansheng990710 this issue is already assigned to @jccampanero. If you would like to contribute, feel free to have a look at the issue tracker for some other issue.

**Comment by jccampanero** [comment]
Thank you very much @filiphr and sorry for the late reply, I was unable to work on the task until yesterday.

I pushed an initial version of the code.

I defined the unit tests in a new package named `enumtointeger` under `org.mapstruct.ap.test.conversion`. Is it the right place? I noticed some tests related to `enum` to `String` in the `org.mapstruct.ap.test.value.enum2string` package.

Please let me know if I need to make any changes, I'll be happy to do so.

Thank you very much.

**Comment by filiphr** [comment]
>Thank you very much @filiphr and sorry for the late reply, I was unable to work on the task until yesterday.

Take as much time as you need @jccampanero.

>I defined the unit tests in a new package named `enumtointeger` under `org.mapstruct.ap.test.conversion`. Is it the right place? 

Yes the `org.mapstruct.ap.test.conversion` is the right place. However, I would do it under a package named `_enum` there and also add the tests for the string conversion. 

>I noticed some tests related to enum to String in the `org.mapstruct.ap.test.value.enum2string` package.

You spotted things well. We do have those package. However, that is more for value mappings. When you want to explicitly define a mapping method from String to enum using `@ValueMapping`.

>Please let me know if I need to make any changes, I'll be happy to do so.

Can you please create a PR so we can discuss potential changes there? On first glance, I think it would be good to have a test case where the `Integer enumValue` will be `null`. I would like to see that this works and that there isn't an NPE.

**Comment by jccampanero** [comment]
Thank you very much for your understanding @filiphr.

I did the changes you proposed.

Before creating the PR, do you want me to squash the different commits of the branch as suggested in the contributing guide?

Thank you very much again.

**Comment by filiphr** [comment]
>Before creating the PR, do you want me to squash the different commits of the branch as suggested in the contributing guide?

Up to you. We usually squash the PR anyways when we do the merge in GitHub.

**Comment by jccampanero** [comment]
Thank you very much @filiphr.

Then, for now I have left the work split into the commits of the original branch, so that code review can be done more easily and to make it easier to add additional changes if needed. 

At the moment I didn't provide any additional tests related to testing the enum to string conversion we mentioned in the comments above: if you want to, and you think it is within the scope of the issue, I can refactor the `XXXMapper`, `XXXSource`, `XXXTarget` and `XXXEnum` enum to integer conversion defined auxiliary tests classes in order to reuse them for the enum to string conversion as well, and provide an initial implementation of the enum to string conversion tests.

Please, do not hesitate to contact me to make the changes you consider necessary, I will gladly make them.

**Comment by filiphr** [comment]
Done in PR #3000. Thanks @jccampanero
