### ISSUE TITLE
Support configurable Spi Implementations

### ISSUE THREAD

**Issue by ro0sterjam** [mapstruct/mapstruct#3071]
### Use case

Spi Implementations have a better opportunity for reusability if they are configurable. Currently MapStruct's `MappingProcessor` does not pass the compilerArgs down to the `MapStructProcessingEnvironment` which is received on the `init` methods of the Spi classes (such as `AccessorNamingStrategy`).

Example of such use case: https://github.com/entur/mapstruct-spi-protobuf/pull/133 (this approach ultimately failed because a workaround was needed to retrieve the `options` that MapStruct does not pass through).

### Generated Code

To resolve this we can just pass the options down to `MapStructProcessingEnvironment`. To be safe, we can limit this to only options under the namespace of `mapstruct.ap.spi`.

### Possible workarounds

There are no viable work arounds. An attempt was made to have the options loaded from a parallel processor but there is no guarantee of processor initialization order.

### MapStruct Version

MapStruct 1.5.3

**Comment by ro0sterjam** [comment]
It would be amazing if this could make it to the next minor version, since this is a backwards compatible change.

**Comment by ro0sterjam** [comment]
Bump on this. I already have a fix in place if someone was willing to review it https://github.com/mapstruct/mapstruct/issues/3071

**Comment by filiphr** [comment]
I understand what you are trying to achieve @ro0sterjam. It is always good to see SPIs for MapStruct thriving and needing more features. However, I do not agree with the proposal. Options exposed to annotation processors which are not reported by any processor will produce a warning, in addition to that I believe that the names of the custom SPI should provide options that are prefixed with its own prefix. Otherwise, it can clash with a potential future MapStruct options.

Having said all of this, we can achieve the required functionality, but in a different way. Options can actually be dynamically provided by overriding the `Processor#getSupportedOptions` method for annotation processors. We could allow the SPIs to provide additional options or provide a dedicated SPI that can be implement to provide the options that would be available. We can then expose all the options to all the other SPIs

**Comment by ro0sterjam** [comment]
I see what you mean. I'll take a crack at your suggestion.
