### ISSUE TITLE
Using `jaxb2-rich-contract-plugin` results in empty mapper implementation

### ISSUE THREAD

**Issue by armanlulu** [mapstruct/mapstruct#3114]
### Expected behavior

I'm using MapStruct and `jaxb2-rich-contract-plugin` with fluent builders enabled:

```xml
      <args>
          <arg>-Xfluent-builder</arg>
      </args>
```

This generates builder methods for XML entities that have `with` method prefix. I believe MapStruct should be able to resolve those methods when mapping objects.

### Actual behavior

MapStruct generates an empty mapper implementation:

```java
public class WidgetContainerMapperImpl implements WidgetContainerMapper {

    @Override
    public WidgetContainer toContainer(WidgetContainerDto dto) {
        if ( dto == null ) {
            return null;
        }

        WidgetContainer.Builder<Void> widgetContainer = WidgetContainer.builder();

        return widgetContainer.build();
    }
}
```

### Steps to reproduce the problem

Please see the following minimal sample that reproduces the issue:

https://github.com/armanlulu/mapstruct-jaxb2-rich-contract-plugin

The configuration part that's causing the problem is at:

https://github.com/armanlulu/mapstruct-jaxb2-rich-contract-plugin/blob/main/pom.xml#L102

### MapStruct Version

1.5.3.Final

**Comment by filiphr** [comment]
I haven't heard of the jaxb2-rich-contract-plugin before. 

It seems like it uses a non conventional style of fluent builder methods that have the property names prefixed with `with`. This can easily be fixed by implementing a custom `AccessorNamingStrategy`. We even have an example with such an accessor naming strategy in our docs.

I will leave this issue to see how many people are affected by this and let the community vote in order to see whether we need to do something on MapStruct side. For now I would say that this should either be addressed by the authors of the plugin itself (provide a MapStruct extension) or write your own custom accessor naming strategy.

**Comment by thunderhook** [comment]
In April 2022 i opened a pull request mklemm/jaxb2-rich-contract-plugin#71 for this to provide the functionality to configure the builder prefix. With this configuration the default `with` prefix can be changed to an empty string. Then the builder will be generated like a "normal" builder without any prefix.

In that PR I also provided an option to disable to copyBuilder method which confuses the mapstruct-idea plugin. Unfortunately nothing has happened since then.

**Comment by filiphr** [comment]
Thanks for the information @thunderhook. I am going to close this issues, since I can see that not too many people are affected by this. If someone thinks that there is something that we can do on the MapStruct side please let us know.

> In that PR I also provided an option to disable to copyBuilder method which confuses the mapstruct-idea plugin.

@thunderhook if this only affects the mapstruct-idea plugin and not the mapstruct-processor than this is a bug in the IntelliJ plugin. Please create an issue there so that we can have a look at it. If it is something around fluent setters it might be the same as https://github.com/mapstruct/mapstruct-idea/issues/121
