### ISSUE TITLE
Doesn't construct/map some field name 

### ISSUE THREAD

**Issue by anup5708** [mapstruct/mapstruct#3121]
### Expected behavior

Hi Team,

I might be the wrong somewhere but I found one problem while mapping my one DTO to another DTO the code is like 

```
class TestFirstDto{
private String myCustomToken;
//Multiple Properties
//Getter
//Setter
}
```

```
class TestSecondDto{
private String sSOTransferTokens;

//Multiple Properties
//Getter
//Setter
}
```

```
@Mapper
public interface MyMapper {

@Mapping(source = "testSecondDto.sSOTransferTokens", target = "testSecondDto.myCustomToken")
public mapSecondToFirst toMapSecondToFirst(
		TestSecondDto testSecondDto
	);
}
```

In this case, it doesn't map my field name from **myCustomToken** to **sSOTransferTokens**. when I change  **sSOTransferTokens** to somethings as **dsSOTransferTokens** then it works fine.

I am using .....

> mapstruct version : 1.5.3.Final
> JDK : 1.8

If I am wrong please let me know 

Thanks.

### Steps to reproduce the problem

<properties>
		<java.version>1.8</java.version>
		<org.mapstruct.version>1.5.3.Final</org.mapstruct.version>
		<lombok-mapstruct-binding.version>0.2.0</lombok-mapstruct-binding.version>
	</properties>

<dependency>
			<groupId>org.mapstruct</groupId>
			<artifactId>mapstruct</artifactId>
			<version>${org.mapstruct.version}</version>
</dependency>

<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.8.1</version>
				<configuration>
					<source>1.8</source> 
					<target>1.8</target> 
					<annotationProcessorPaths>
						<path>
							<groupId>org.mapstruct</groupId>
							<artifactId>mapstruct-processor</artifactId>
							<version>${org.mapstruct.version}</version>
						</path>
						
						<path>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok</artifactId>
							<version>${lombok.version}</version>
						</path>
						<path>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok-mapstruct-binding</artifactId>
							<version>${lombok-mapstruct-binding.version}</version>
						</path>
					</annotationProcessorPaths>
					<compilerArgs>
						<compilerArg>
							-Amapstruct.defaultComponentModel=spring
						</compilerArg>
					</compilerArgs>
				</configuration>
			</plugin>

### MapStruct Version

1.5.3

**Comment by Zegveld** [comment]
This works as expected because of the java bean convention. The java bean convention does not support properties that start with a single lowercase letter followed by an uppercase letter.

This mean that the method `getSSOTransferTokens()` is meant for a property named `SSOTransferTokens` because the first two letters are uppercase.
If you would have `getSsoTransferTokens()` then the property would be named `ssoTransferTokens` because the second character is not uppercase, the first one becomes lowercase.

Mapstruct uses the java bean convention to determine the property name from the getters/setters instead of the field if the field is private. You could try `@Mapping(source = "testSecondDto.SSOTransferTokens", target = "testSecondDto.myCustomToken")` as `SSOTransferTokens` is the property name derived from the getter according to the java bean spec.

for more information see also this stackoverflow question which concerns an issue similar to your own:
[javabean convention method naming for property gId](https://stackoverflow.com/questions/11114147/javabean-convention-method-naming-for-property-gid)

Hope this explanation helps with why this problem arises.

Closing this issue because the functionality works as expected due to java bean spec behaviour.
