### ISSUE TITLE
"uses" and "expression" dose not work together

### ISSUE THREAD

**Issue by kuntaljy** [mapstruct/mapstruct#3155]
### Expected behavior

I want to uses another component to generate a value for a field, like this:

```
@Mapper(componentModel = "spring", uses = IdGenerator.class)
public interface MyMapper {
    @Mapping(target = "id", expression = "java(idGenerator.nextId())")
    User to(UserDTO userDto);
}

public class User {
    private Long id;
    private String name;
    private String address;
}

public class UserDTO {
    private String name;
    private String address;
}

@Component
public class IdGenerator {
    public Long nextId(){
        //generate id value;
    }
}
```

### Actual behavior

There is not field named "idGenerator" injected in to the generated class, and the expression dose not work

### Steps to reproduce the problem

as above

### MapStruct Version

1.5.2

**Comment by Zegveld** [comment]
This behaviour is by design.

Mapstruct will only make use of fields mentioned at the `uses` argument if there is a by mapstruct detected reason to use it. The expression parameter is free input, there is no analysis done on what it contains. So if you need a field named `idGenerator` then you would need to supply this yourself.

See also: #2415 and #2237
