### ISSUE TITLE
Missing null check on secondary source field after upgrading from 1.4.x to version 1.5.x 

### ISSUE THREAD

**Issue by ntinnemeier** [mapstruct/mapstruct#3160]
### Expected behavior

In version 1.4.2 MapStruct generates this mapping code:
```java
    public ATarget map(ASource value, Integer i) {

        String s = null;
        if ( value != null ) {
            s = value.getS();
        }
        Double i1 = null;
        if ( i != null ) {
            i1 = map( i );
        }

        ATarget aTarget = new ATarget( s, i1 );

        return aTarget;
    }
```

### Actual behavior

After upgrading to 1.5.3 MapStruct gives us this:
```java
    public ATarget map(ASource value, Integer i) {

        String s = null;
        if ( value != null ) {
            s = value.getS();
        }
        Double i1 = null;
        i1 = map( i );

        ATarget aTarget = new ATarget( s, i1 );

        return aTarget;
    }
```

Now the ``map`` method is called with a ``null`` value, whereas before the ``map`` method was not called at all. This could introduce NPEs if the ``map`` method does not expect ``null`` values.

This behaviour was probably introduced to remove a redundant null check in version 1.4.x when the variable ``i`` can be mapped directly without an additional ``map``, e.g.:
```java
        Double i1 = null;
        if ( i != null ) {
            i1 = i;
        }
```

### Steps to reproduce the problem

See: https://github.com/ntinnemeier/mapstruct-1.5-upgrade-bugs/tree/main/null-check-on-source for an example.
Switch between version 1.4.x and 1.5.x to see the difference in behaviour.

Side note: I was forced to add ``@Mapping(target = "i", source = "i")`` to make things work in version 1.4.x. This is no longer needed in version 1.5.x, so kudos for fixing this! 👍 

### MapStruct Version

MapStruct 1.5.3

**Comment by filiphr** [comment]
This actually works correctly. MapStruct does null checks by default on implicit conversions. This means that if you do not have a custom mapping method then there will be a null check done. 

The null check in 1.4 was incorrect and was coming from a wrong place. I believe that the fix for #2023 removed that null check. You can see this by moving the `i` in the `ASource` and having a single mapping. You'll see that when using a custom method there is no null check done before calling the custom map method for an integer.

If you want to always do a null check I would suggest that you use `@Mapper(nullValueCheckStrategy = NullValueCheckStrategy.ALWAYS)`.
