### ISSUE TITLE
unable to build mapstruct

### ISSUE THREAD

**Issue by delanym** [mapstruct/mapstruct#3228]
### Expected behavior

Following instructions at https://github.com/mapstruct/mapstruct#building-from-source
I should be able to build commit 89db26a1af35fb759a2fa74b8bc7586cb743c454 successfully.

### Actual behavior

With Apache Maven 3.9.0 on Windows OS and JDK11

```
[INFO] --- surefire:3.0.0-M5:test (default-test) @ mapstruct-integrationtest ---
[WARNING] useSystemClassLoader setting has no effect when not forking
[WARNING] The parameter forkCount should likely not be 0, not forking a JVM for tests reduce test accuracy, ensure to have a <forkCount> >= 1.
[INFO] Running org.mapstruct.itest.tests.MavenIntegrationTest
[ERROR] Tests run: 62, Failures: 0, Errors: 34, Skipped: 28, Time elapsed: 0.583 s <<< FAILURE! - in org.mapstruct.itest.tests.MavenIntegrationTest
[ERROR] org.mapstruct.itest.tests.MavenIntegrationTest.namingStrategyTest  Time elapsed: 0.078 s  <<< ERROR!
org.apache.maven.it.VerificationException: Parsing exception for file C:\Users\delanym\.m2\settings.xml
Caused by: org.xml.sax.SAXException: Invalid mavenProfile entry. Missing one or more fields: {localRepository}.
```

### Steps to reproduce the problem

```
git clone https://github.com/mapstruct/mapstruct.git
cd mapstruct
mvn clean install
```

### MapStruct Version

1.5.3-Final

**Comment by Chr3is** [comment]
Seems to be a local issue with your maven settings.xml
`Parsing exception for file C:\Users\delanym\.m2\settings.xml
Caused by: org.xml.sax.SAXException: Invalid mavenProfile entry. Missing one or more fields: {localRepository}.`

**Comment by delanym** [comment]
I have "<localRepository/>" in my settings, which is perfectly valid: https://maven.apache.org/settings.html#quick-overview
You might want to use maven-invoker-plugin rather.

**Comment by delanym** [comment]
BTW can you give me an instruction to run in the console that proves filiphr's claim in https://github.com/mapstruct/mapstruct/issues/2804
When I try run maven in any of the it-test examples I get issues.

**Comment by delanym** [comment]
And then what? What other lurgies are hiding under the covers in your build?
My setting file is valid according to the XSD it says it follows and that's all that should matter.

**Comment by delanym** [comment]
There some complexity to this issue (see https://lists.apache.org/list.html?dev@maven.apache.org), but bottom line is if you're going as far as evaluating the settings.xml file then it should probably go via Maven.

Integration tests validate functionality in its intended context - in this case a Maven build. If Mapstruct wasn't a compiler/build plugin it might not be a concern.

**Comment by filiphr** [comment]
@delanym there is really no need to be rude. Seems like you have some complex non standard settings.xml which is causing you problems. The only thing you need to do to run from source is to use Java 11 and use `./mvnw clean install`. If you try to run maven manually in the `integrationtest` folder it won't work because it expects you to have the project version of mapstruct and mapstruct-processor installed in your local repository.

The integration tests are intended to be run using the `MavenIntegrationTest` class and not manually. This is how this project is setup. If you don't like this then you can provide a PR that is doing something else and the MapStruct team will look into it.

>There some complexity to this issue (see https://lists.apache.org/list.html?dev@maven.apache.org), but bottom line is if you're going as far as evaluating the settings.xml file then it should probably go via Maven.

If you check [`ProcessorInvocationInterceptor`](https://github.com/mapstruct/mapstruct/blob/main/integrationtest/src/test/java/org/mapstruct/itest/testutil/extension/ProcessorInvocationInterceptor.java) you will see that we are using `maven-verifier` to invoke Maven. So everything goes through Maven.

>I'm working on a closed source project so i can't offer a reproducer. Can you give me a command that proves Mapstruct is not at fault?

You can have a look at our GitHub actions. You'll see that everything runs without any issues. So MapStruct can't be at fault.

>This ticket is resolved, but I would appreciate some assistance on https://github.com/mapstruct/mapstruct/issues/2804
which I felt was prematurely/rudely closed without the slightest help. I see this project has a lot of open issues so I understand the loathsomeness of having to inspect yet another one, but the stack trace had no classes from my own project and I am really at a loss what my next steps should be.

The issue was closed because you didn't provide any information of what kind of problem you have. Without we being able to run a minimal reproducible example we cannot provide any help. Everyone that works on MapStruct works on it in their own free time and according to their own schedule. This is a free project and anyone can provide help and / or contribute to the project. If you don't like it, then you don't have to use it. The fact that you are working on a closed source project doesn't mean that we are required to guess your problems.

**Comment by filiphr** [comment]
@Chr3is I forgot to say thank you for the help you provided to @delanym for the issue that they had. I am really sorry that your help was rejected in a rude way. The MapStruct team really appreciates everyone in the community and we are really thankful for anyone that is willing to help in any way possible

**Comment by delanym** [comment]
> So MapStruct can't be at fault.
You don't know that, and closing the ticket right after I open it tells me that you don't care either because as far as you're concerned the issue is closed. The person who opens a ticket is the one who closes it, like I did here.
