### ISSUE TITLE
Mapper ignores `@InheritConfiguration` from used mapper

### ISSUE THREAD

**Issue by thunderhook** [mapstruct/mapstruct#3252]
### Expected behavior

A mapper inheriting its configuration from a used mapper should be considered as stated in the docs:
> Methods that are considered for inheritance need to be defined in the current mapper, a super class/interface, **or in the shared configuration interface (as described in [Shared configurations](https://mapstruct.org/documentation/stable/reference/html/#shared-configurations))**.

... and mentioned in this comment of the IntelliJ plugin: https://github.com/mapstruct/mapstruct-idea/issues/65#issuecomment-1518707160

### Actual behavior

The `@InheritConfiguration` is not considered and giving the error: 

```
java: Unmapped target properties: "numberOfSeats, manufacturingDate".
```

### Steps to reproduce the problem

```java
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.factory.Mappers;

@Mapper
public interface UsedMapper {

    UsedMapper INSTANCE = Mappers.getMapper( UsedMapper.class);

    @Mapping(target = "manufacturingDate", source = "manufacturingYear")
    @Mapping(target = "numberOfSeats", source = "seatCount")
    Car carDtoToCar(CarDto car);

}
```

```java
import org.mapstruct.InheritConfiguration;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;

@Mapper(uses = UsedMapper.class)
public interface InheritConfigurationFromUsedClassMapper {

    @InheritConfiguration
    void carDtoIntoCar(CarDto carDto, @MappingTarget Car car);

}
```

---

I tried to fix this myself.
The first problem is, that referenced methods do not fill in the mapping options, see [here](https://github.com/thunderhook/mapstruct/blob/1bc3436c5c64077503a1656eb8ef516c69d0e3b4/processor/src/main/java/org/mapstruct/ap/internal/processor/MethodRetrievalProcessor.java#L234-L234) and [here](https://github.com/thunderhook/mapstruct/blob/1bc3436c5c64077503a1656eb8ef516c69d0e3b4/processor/src/main/java/org/mapstruct/ap/internal/processor/MethodRetrievalProcessor.java#L380-L390).
The second problem are [NPEs when filling the inheritance options](https://github.com/thunderhook/mapstruct/blob/1bc3436c5c64077503a1656eb8ef516c69d0e3b4/processor/src/main/java/org/mapstruct/ap/internal/model/source/MappingMethodOptions.java#L161-L182), because bean, iterable, map and enum mapping options also not getting filled for referenced methods.
The third problem is, that [`canInheritFrom()`](https://github.com/thunderhook/mapstruct/blob/1bc3436c5c64077503a1656eb8ef516c69d0e3b4/processor/src/main/java/org/mapstruct/ap/internal/model/source/SourceMethod.java#L361) returns `false` because a declaring mapper is set for the referenced method.

Removing the `method.getDeclaringMapper() == null` check results in other test failures.
This may be colliding with (the thoughts of) this PR: [!1027](https://github.com/mapstruct/mapstruct/issues/1027).

I already created a forked branch with a corresponding test (and my proposed unfinished solution) here: https://github.com/mapstruct/mapstruct/compare/main...thunderhook:mapstruct:3252

### MapStruct Version

MapStruct 1.5.4

**Comment by filiphr** [comment]
@thunderhook the snippet of the documentation you shared does not mention classes in the `Mapper#uses`

Methods that are considered for inheritance need to be defined in:

* the current mapper - This is clear
* a super class/interface, or - this is in parents of the current mapper, for `public class CarMapper extends OtherMapper` the methods defined in `OtherMapper`
* in the shared configuration interface - This means the methods defined there. If you go to [Shared Configurations](https://mapstruct.org/documentation/stable/reference/html/#shared-configurations) you'll see:

> The interface holding the `@MapperConfig` annotation may also declare **prototypes** of mapping methods that can be used to inherit method-level mapping annotations from. Such prototype methods are not meant to be implemented or used as part of the mapper API.

The prototype being in bold.

---
I might have made a mistake in my comment for the plugin (I didn't check with the documentation). Let's take the current situation as a reference.

Fixing this might be a bit tricky since it might lead to unexpected things and might be backwards incompatible, because methods that previously were not treated as prototype will become prototype methods.

**Comment by thunderhook** [comment]
Okay thanks, I think we can close this issue then. 👍🏻 Feel free to tag this issue as invalid.
