### ISSUE TITLE
mapstruct编译后的实现类未进行get Set处理

### ISSUE THREAD

**Issue by shuaixiaomi** [mapstruct/mapstruct#3269]
### Actual behavior

![image](https://github.com/mapstruct/mapstruct/assets/77660384/bd2cde2f-c5ec-4e05-961d-ac3c04462a21)

### Steps to reproduce the problem

no

### MapStruct Version

1.4.2.Final

**Comment by filiphr** [comment]
If MapStruct didn't provide any errors then I guess you are using Lombok, but have not setup everything properly. Have a look at https://mapstruct.org/faq/#Can-I-use-MapStruct-together-with-Project-Lombok. If you are not using Lombok, then please provide your `CustomTaskFollowHistoryDTO` and `CustomTaskResultDTO` so that we can understand what is happening`
