### ISSUE TITLE
3.5. Mapping nested bean properties to current target - not working for multiple parameters

### ISSUE THREAD

**Issue by lowcasz** [mapstruct/mapstruct#3315]
### Expected behavior

I have method:
`
@Mapping(target=".", source="p1")
Target map(Type1 p1, Type2 p2);
`
p1, and p2 has overlapped property names and all ambiguity should by resolved by the annotation, but it isn't happend and "error: Several possible source properties for target property" is thrown.

I didn't check is it still works for one parameter and nested bean.

### Actual behavior

I have method:
`
@Mapping(target=".", source="p1")
Target map(Type1 p1, Type2 p2);
`
p1, and p2 has overlapped property names and all ambiguity should by resolved by the annotation, but it isn't happend and "error: Several possible source properties for target property" is thrown.

### Steps to reproduce the problem

`
@Mapping(target=".", source="p1")
Target map(Type1 p1, Type2 p2);
`
`
class Target {
 String prop1;
 String prop2;
 String prop3;
 String prop4;
 String prop5;
 String prop6;
}
`
`
class Type1 {
 String prop1;
 String prop2;
 String prop3;
 String prop4;
}
`
`
class Type2 {
 String prop3;
 String prop4;
 String prop5;
 String prop6;
}
`

### MapStruct Version

1.4.2.Final

**Comment by filiphr** [comment]
@lowcasz this works as designed. Have a look at https://mapstruct.org/documentation/stable/reference/html/#mapping-nested-bean-properties-to-current-target. It talks about having conflicts.

Using `@Mapping(target = ".", ...)` means map the rest of the non implicitly mapped properties. It doesn't mean map all the properties from target. You are getting the error because the implicit mapping fails. When having an example like this you have to explicitly define which target comes from which source.

**Comment by filiphr** [comment]
@lowcasz it works with single parameter because there isn't any ambiguity in the parameters. It doesn't work for multiple parameters because it is designed like that. Using `@Mapping(target = ".", ...)` means that it will map all the properties that were not mapped already, that comes later after the implicit properties are mapped and implicit properties cannot be mapped because MapStruct doesn't know which source to use for them.
