### ISSUE TITLE
Mappings do not work in Kotlin when variable has an uppercase letter after lovercase ie yXy.

### ISSUE THREAD

**Issue by Summeli** [mapstruct/mapstruct#3352]
### Expected behavior

I would expect get-function getyXy for variable yXy.

### Actual behavior

Get function is missing in Kotlin. This problem is not in JAVA side. You can go around this issue by defining the GET-fuction by hand @get:JvmName("GetyXy").

### Steps to reproduce the problem

name a variable yXy in Kotlin class.

### MapStruct Version

1.5.3.Final

**Comment by Zegveld** [comment]
This works as expected because of the java bean convention. The java bean convention does not support properties that start with a single lowercase letter followed by an uppercase letter.

for more information see also this stackoverflow question which concerns an issue similar to your own:
[javabean convention method naming for property gId](https://stackoverflow.com/questions/11114147/javabean-convention-method-naming-for-property-gid)

See also https://github.com/mapstruct/mapstruct/issues/3121#issuecomment-1364671033

Hope this explanation helps with why this problem arises.

Closing this issue because the functionality works as expected due to java bean spec behavior.
