### ISSUE TITLE
Unit test leaks classes from @WithClasses

### ISSUE THREAD

**Issue by sjaakd** [mapstruct/mapstruct#338]
To demonstrate this, just add:

```java
   @Test
    @WithClasses({ ArtistToChartEntryAdder.class, ChartPositions.class, AdderUsageObserver.class })
    public void shouldUseGetAsTargetAccessor2() {

        AdderUsageObserver.setUsed( false );
        Song song = new Song();
        song.setPositions( Arrays.asList( 3, 5 ) );

        Chart chart = new Chart();
        chart.setSong( song );

        ChartPositions positions = ArtistToChartEntryGetter.MAPPER.map( chart );
        assertThat( positions ).isNotNull();
        assertThat( positions.getPositions() ).containsExactly( 3L, 5L );

        assertFalse( AdderUsageObserver.isUsed() );
    }
```

As last method to the unit test: `org.mapstruct.ap.test.nestedsourceproperties.NestedSourcePropertiesTest`.

Note: `ArtistToChartEntryAdder` is added to the `@WithClasses` while `ArtistToChartEntryGetter` is actually used. Presumably `ArtistToChartEntryAdder` 'leaks' from the previous method.

**Comment by agudian** [comment]
The problem is that we use one classloader instance for all methods in one test class.
To fix this, we'd have to rewrite a lot of the test framework, including copying down quite some methods from the JUnit runner superclasses in order to be able to use different classloaders for the test methods, if necessary. That's quite a little undertaking and I wonder if it's worth the hassle. We could alternatively make ```@WithClasses``` be only applicable at class-level to avoid this case entirely, and I think we wouldn't loose too much. I see that as being of any value only for tests on errorneous mappers, but also there we usually pack all the possible/tested errors into one single set of files and not into multiple ones.

WDYT?

**Comment by agudian** [comment]
> To fix this, we'd have to rewrite a lot of the test framework, including copying down quite some methods from the JUnit runner superclasses in order to be able to use different classloaders for the test methods, if necessary.

Ok, I take back a part of that: in JUnit 4.12, there are some changes that allow me stuff like that... :smile:

**Comment by gunnarmorling** [comment]
Cool, thanks for fixing this. At some point I'd like to clean-up the testing infra, I feel we've gathered some hacks/work-arounds. But that can wait until after the final release.
