### ISSUE TITLE
lombok builder - property with first letter lowercase and second letter uppercase - mismatch

### ISSUE THREAD

**Issue by MarneusCalgarXP** [mapstruct/mapstruct#3408]
### Expected behavior

hello,

having a bean with a property name with first letter lowercase and second letter uppercase :

```java
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class Foo {

    private String aA;

}
```

having another bean, same structure, but no builder

```java
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
public class Bar {

    private String aA;

}
```

defining a mapstruct mapper like :
```java
Foo toFoo(Bar bar);
```

### Actual behavior

Mapstruct isn't able to manage the mapping, it generates an empty mapping:
```java
 @Override
    public Foo toFoo(Bar bar) {
        if ( bar == null ) {
            return null;
        }

        Foo.FooBuilder foo = Foo.builder();

        return foo.build();
    }
```

this is because, in the lombok generated builder, the method starts with a lowerCase
![image](https://github.com/mapstruct/mapstruct/assets/1315177/d7a5a0f7-892b-43bd-b6cf-8669b39f7cf8)

and in the the getter the property starts with an upperCase:
![image](https://github.com/mapstruct/mapstruct/assets/1315177/eb0866b5-9f25-4c90-9426-c430e7a7a912)

so today there's a workaround, adding a `@Mapping` annotation, but it shouldn't be necessary, MapStruct should detect it automatically.

```java
   @Mapping(source = "AA", target = "aA")
    Foo toFoo(Bar bar);
```

### Steps to reproduce the problem

* openjdk 17 (openjdk 17.0.8.1 2023-08-24 / OpenJDK Runtime Environment (build 17.0.8.1+1-Ubuntu-0ubuntu122.04))
* mapstruct 1.5.5.Final

```xml
<!-- MapStruct mapping -->
        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct</artifactId> 
            <version>${mapstruct.version}</version>
        </dependency>

        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct-processor</artifactId>
            <version>${mapstruct.version}</version>
        </dependency>
```

### MapStruct Version

Mapstruct 1.5.5.Final

**Comment by foaw** [comment]
As far as I can tell, this is the expected behaviour. This has to do with the JavaBeans specification, which dictates that properties where the first word is a single letter are not capitalised—that is, for `aA`, the getter name would be `getaA`, whereas Lombok, by default, generates `getAA`.

To get around this problem, you can either tweak Lombok to follow the JavaBeans naming convention, or hand-specify the name of the source property. As for tweaking Mapstruct instead, read the comment below. From what I remember, there is not a simple setting for this yet, or at least not in version 1.5.5.Final. Although I encourage you to do your own research on this.

- https://github.com/mapstruct/mapstruct/issues/1643#issue-378165232
- https://github.com/mapstruct/mapstruct/issues/3374#issuecomment-1722216448
- https://github.com/mapstruct/mapstruct/issues/3230#issuecomment-1500388521
- https://mapstruct.org/documentation/stable/reference/html/#lombok

**Comment by filiphr** [comment]
Thanks for your explanation @foaw. @MarneusCalgarXP MapStruct does not look into the names of the fields, but it uses the JavaBean convention to determine the property names. A getter like `getAA` is for a property named `AA` according to the JavaBean convention. Have a look at the links shared by @foaw for more information.
