### ISSUE TITLE
Mapper definition via XML/JSON/YAML/external file driven

### ISSUE THREAD

**Issue by banandh** [mapstruct/mapstruct#3420]
### Use case

Hi- Currently Mapstruct supports the mapping definition via annotation on the java objects. I would like to use the same mapping via XML file. Dozer has the support for XML mapping if something similar exist with Mapstruct , it will be easy adopting it.

**Comment by filiphr** [comment]
@banandh MapStruct is an annotation processor that runs during the compile phase of the project. Can you please elaborate a bit why you would like to have an external file to define a mapper definition?

**Comment by thy3368** [comment]
use to define low code

**Comment by filiphr** [comment]
In order to support something like this we would need to do quite some refactoring in MapStruct.

I have some refactorings in mind, that would decouple MapStruct from the Java compiler and then we can have better support for KSP (see #2522). Only after something like this is done support for file driven mapping could be done.

For now, I'll close this issue and let's see what the future brings.
