### ISSUE TITLE
Unknown property with Lombok `@SuperBuilder` and JDK 17 

### ISSUE THREAD

**Issue by xkernal** [mapstruct/mapstruct#3509]
### Expected behavior

integration with lombok>1.8.24 using jdk17 

### Actual behavior

compile error Unknown property "stakeToken" in result type ProductDetailResp.ProductDetailRespBuilder<?,?>. Did you mean "null"?    I have also tried 1.5.5.Final produce the same error

### Steps to reproduce the problem

![image](https://github.com/mapstruct/mapstruct/assets/1595056/141e02d4-4225-4905-8c32-8cf196a49c1c)

plugin configs:
![image](https://github.com/mapstruct/mapstruct/assets/1595056/17446611-9c59-454b-806f-178dbb82c290)

![image](https://github.com/mapstruct/mapstruct/assets/1595056/b2046cce-acd0-48b8-8663-47bbdaf1d1e8)

### MapStruct Version

mapStruct 1.4.2.Final

**Comment by thunderhook** [comment]
Hi @xkernal 

We are using Java 17 in many of our projects and it works fine with the same pom definitions as you provided.
The error message indicates that you're using `@SuperBuilder` - could you please provide the lombok annotations of your source and target objects? No need to share all of your code, just some skeletons without the fields, but maybe the inheritances would be good too. So that we can reproduce it.

There seems to be a problem with `@SuperBuilder` in some edge cases. As I said, we have not had any problems with it yet. But the following issue also mentions problems with it:
* #2508

Unfortunately, I have not been able to reproduce it yet. Perhaps it has something to do with `@Accessors(chain=true)`.

Note on the example you wanted. Increasing the Java and dependency versions here still worked here: https://github.com/mapstruct/mapstruct-examples/blob/main/mapstruct-lombok/pom.xml

**Comment by filiphr** [comment]
Closing this due to lack of feedback. We can reopen it if we get more information
