### ISSUE TITLE
How could I map a primitive attribute with default value to null?

### ISSUE THREAD

**Issue by Qomolang** [mapstruct/mapstruct#3554]
### Use case

In thrift, the params in request are always primitive type, which means they always have values! And this may incuur some problem, so we must do the convert handly

what we want is like: int = 0 -> Integere = null, long = 0 -> Long =null and so on.

for example:
public class Car {
	private int numberOfSeats;
}

public class CarDTO {
	private Integer seats;
}

When numberOfSeats in Car is 0, I want to set seats to be null rather than Integer(0), is there an Option or a mature solution？

### Generated Code

may be like:

public CarDto toCarDto(Car car) {

        if ( car == null ) {
            return null;
        }

        CarDto carDto = new CarDto();

        if(car.numberOfSeats != 0){
               carDto.setSeat(car.numberOfSeats);
        }

}

**Comment by filiphr** [comment]
@Qomolang please do not use the issue tracker to ask questions. You can either use our [GitHub Discussions](https://github.com/mapstruct/mapstruct/discussions) or [StackOverflow](https://stackoverflow.com/questions/tagged/mapstruct).

to answer your question you can use a custom condition or a custom presence checker for this.

e.g.

```java
@Mapper
public interface CarMapper {

    @Mapping(target = "seats", source = "numberOfSeats", conditionQualifiedByName = "hasSeats")
    CarDto map(Car car);

    @Named("hasSeats")
    @Condition
    default boolean hasSeats(int seats) {
        return seats != 0;
    }
}
```

another alternative instead of `@Condition` would be if you define a `boolean hasSeats` method on the `Car`.

**Comment by Qomolang** [comment]
> @Qomolang please do not use the issue tracker to ask questions. You can either use our [GitHub Discussions](https://github.com/mapstruct/mapstruct/discussions) or [StackOverflow](https://stackoverflow.com/questions/tagged/mapstruct).
> 
> to answer your question you can use a custom condition or a custom presence checker for this.
> 
> e.g.
> 
> ```java
> @Mapper
> public interface CarMapper {
> 
>     @Mapping(target = "seats", source = "numberOfSeats", conditionQualifiedByName = "hasSeats")
>     CarDto map(Car car);
> 
>     @Named("hasSeats")
>     @Condition
>     default boolean hasSeats(int seats) {
>         return seats != 0;
>     }
> }
> ```
> 
> another alternative instead of `@Condition` would be if you define a `boolean hasSeats` method on the `Car`.

sry for this issue and thanks for the reply, but it does not solve my problem completely.
It may have 8 or more primitive type params in the request, I would rather convert it handly than using this way, because this way has too many hard-coding

**Comment by filiphr** [comment]
>sry for this issue and thanks for the reply, but it does not solve my problem completely.
It may have 8 or more primitive type params in the request, I would rather convert it handly than using this way, because this way has too many hard-coding

My example was for how to apply this for a single property (thus the use of `@Named` and `conditionQualifiedByName`). If you remove `@Named` then the condition method would be applied to all the primitive `int` properties
