### ISSUE TITLE
Cyclic dependency problem when using mappers with annoations "componentModel = SPRING" and "uses = {...}"

### ISSUE THREAD

**Issue by twallmey** [mapstruct/mapstruct#3558]
### Expected behavior

Objects structures may form cycles, e.g. A -> B -> A. If a dedicated mapper should be used for mapping referenced objects of A (e.g. B) they can be named via "uses"-attribute in @Mapper annotation. In case componentModel = SPRING is defined each of these referenced mappers get autowired but without annotation @Lazy. Hence, the application startup stops when it detects such a cyclic dependency of mappers. By adding @Lazy the problem should/could be avoided at startup.

### Actual behavior

Application stops starting because of cyclic dependency.

### Steps to reproduce the problem

* Define a cycly object structure, e.g. A->B->A
* Define a mapper for A and B
* add mapper for B in A via annotation "uses" and make use of component model = SPRING

### MapStruct Version

Mapstruct 1.5.5

**Comment by thunderhook** [comment]
Hi @twallmey,

Using `@Lazy` is one possible approach to support cycles in your code. However it has the disadvantage of detecting errors at runtime rather than at application startup, and some other drawbacks. See https://github.com/mapstruct/mapstruct/issues/2741#issuecomment-1030589468 for more details.

Please also have a look at the following solutions for circular references:
* using setter injection
  * https://github.com/mapstruct/mapstruct/issues/2741#issuecomment-1065410535
  * [Spring Docs](https://docs.spring.io/spring-framework/reference/core/beans/dependencies/factory-collaborators.html#beans-dependency-resolution)
* Using the unofficial `springlazy` component model
  * https://github.com/mapstruct/mapstruct/issues/2741#issuecomment-1067304830

I'll close this as there are other solutions for this.
