### ISSUE TITLE
unmappedSourcePolicy=ERROR and unmappedTargetPolicy=ERROR not work as expected

### ISSUE THREAD

**Issue by developer-sunnywu** [mapstruct/mapstruct#3571]
### Expected behavior

Would expect that I don't need to specify the method properties to be ignore. 

Remarks: In this example, target properties would result exception, but also I am facing source properties need to be also explicitly ignored in my test

### Actual behavior

Got Unmapped target properties: "withId, withNewId" exception without specifying ignore the withNewId and withId

E.g
`   @Mapping(target = "withNewId", ignore = true)
    @Mapping(target = "withId", ignore = true)`

### Steps to reproduce the problem

1. Set the unmappedSourcePolicy=ERROR and unmappedTargetPolicy=ERROR
2. Create source class, target class, and mapper interface 

```
public class SourceFoo {
    private Long id;
    private Long newId;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getNewId() {
        return newId;
    }

    public void setNewId(Long newId) {
        this.newId = newId;
    }

    public SourceFoo withId(Long id) {
        this.setId(id);
        return this;
    }

    public SourceFoo withNewId(Long newId) {
        this.setNewId(newId);
        return this;
    }
}
```

```
public class TargetFoo {
    private Long id;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }
}

```

```
@Mapper
public interface FooMapper {

    FooMapper INSTANCE = Mappers.getMapper(FooMapper.class);

    @Mapping(target = "newId", ignore = true)
    SourceFoo targetFooToSourceFoo(TargetFoo targetFoo);
}
```

### MapStruct Version

1.5.5.Final and java 17

**Comment by filiphr** [comment]
This works as designed. MapStruct is looking at the methods using the JavaBean specification and fluent setters to determine if a method is an applicable property or not.

MapStruct treats a method like `public SourceFoo withNewId(Long newId) ` as a fluent setter and that's why you are getting those warnings. If you do not want some methods to be considered as mapping methods then perhaps you need to implement a custom `AccessorNamingStrategy`.

**Comment by developer-sunnywu** [comment]
Thanks for the explanation!

**Comment by developer-sunnywu** [comment]
May I know if is there any reference on how to implement it?

**Comment by filiphr** [comment]
@developer-sunnywu have a look at the [Customer Accessor Naming Strategy](https://mapstruct.org/documentation/stable/reference/html/#_custom_accessor_naming_strategy) in our documentation.

**Comment by developer-sunnywu** [comment]
> @developer-sunnywu have a look at the [Customer Accessor Naming Strategy](https://mapstruct.org/documentation/stable/reference/html/#_custom_accessor_naming_strategy) in our documentation.

Thank you! After playing around with it and was successfully implemented. And get two questions 
1. Is that in the build cycle, just to confirm it will get all the setter and getter method tgt with getPropertyName to get the actual property name?
2. As a user point of view, why do we need to implement in separate jar and then use the spi method to get use of the CustomAccessorNamingStrategy but cannot just implement the AccessorNamingStrategy. Because it might cause a little trouble to use it and just want to know the intention or design methodology behind it.

**Comment by filiphr** [comment]
>1. Is that in the build cycle, just to confirm it will get all the setter and getter method tgt with getPropertyName to get the actual property name?

I'm not sure that I fully understand the question. MapStruct is an annotation processor and during the compilation phase it is going to get all the getters / setters and based on them determine the property names.

>2. As a user point of view, why do we need to implement in separate jar and then use the spi method to get use of the CustomAccessorNamingStrategy but cannot just implement the AccessorNamingStrategy. Because it might cause a little trouble to use it and just want to know the intention or design methodology behind it.

This is because MapStruct is an annotation processor, which means that it gets invoked during the compilation phase. If your custom `AccessorNamingStrategy` is part of the same module as the mappers then there is chicken or egg problem. The custom accessor naming strategy needs to be compiled before it can be used by MapStruct, but in order to compile it the java compiler needs to run the annotation processor. This is a Java compiler limitation, not a MapStruct one.

**Comment by developer-sunnywu** [comment]
Thank you very much! very clear
