### ISSUE TITLE
mapstruct-processor jar is missing when package from spring2.4

### ISSUE THREAD

**Issue by hepengju** [mapstruct/mapstruct#3648]
### Expected behavior

use this classes in org.mapstruct.mapstruct-processor. ex: `org.mapstruct.ap.internal.util.Collections`

### Actual behavior

when package to fatjar, mapstruct-processor is excluded because the  `Spring-Boot-Jar-Type: annotation-processor` in MANIFEST.MF. 
when app is running , throw exception: java.lang.NoClassDefFoundError: org/mapstruct/ap/internal/util/Collections

### Steps to reproduce the problem

https://github.com/spring-projects/spring-boot/issues/41610

### MapStruct Version

1.5.5.Final

**Comment by philwebb** [comment]
The `Collections` is in an `org.mapstruct.ap.internal` package so I don't think it's intended to be used in your own code.

**Comment by hepengju** [comment]
It's ok, I won't use org.mapstruct.ap.internal.Collections. But some others use it in other projects. When I upgrade 100+ apps from jdk8 to jdk21 (SpringBoot2 to SpringBoot3), this may cause risks only when running to the code.

**Comment by philwebb** [comment]
Perhaps an [openrewrite](https://docs.openrewrite.org/) recipe could help you migrate. In my opinion, the `Spring-Boot-Jar-Type: annotation-processor` should remain and an jar should be filtered.

**Comment by hepengju** [comment]
Thanks. But we intend modify the MANIFEST.MF and deploy the new jar to our nexus, so no risk when upgrade so many apps. 
`Spring-Boot-Jar-Type: annotation-processor-ark`
`mapstruct-processor-1.5.5.Final.Ark.jar`

**Comment by filiphr** [comment]
Thanks for chiming in @philwebb.

This referenced class (`org.mapstruct.ap.internal.util.Collections`) is indeed an internal class and it is not meant to be used outside of MapStruct itself. The `Spring-Boot-Jar-Type: annotation-processor` for MapStruct is correct, since that dependency is an annotation processor.


> this may cause risks only when running to the code.

Keep in mind that the class you are using might completely change even in a patch release without any announcement. Which means that you have the risk always.

@hepengju, what I would suggest to you is instead of putting `mapstruct-processor` in the dependencies to use the `annotationProcessorPaths` of the `maven-compiler-plugin`

e.g.

```maven
<build>
    <plugins>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-compiler-plugin</artifactId>
            <configuration>
pending on your project -->
                <annotationProcessorPaths>
                    <path>
                        <groupId>org.mapstruct</groupId>
                        <artifactId>mapstruct-processor</artifactId>
                        <version>${org.mapstruct.version}</version>
                    </path>
                    <!-- other annotation processors -->
                </annotationProcessorPaths>
            </configuration>
        </plugin>
    </plugins>
</build>
```

or use `annotationProcessor` scope if you are using Gradle.
