### ISSUE TITLE
MapStruct does not map boolean properties when using Builder pattern

### ISSUE THREAD

**Issue by agitrubard** [mapstruct/mapstruct#3702]
### Expected behavior

I expected MapStruct to correctly map boolean properties between two classes using the Builder pattern, especially when the property names are identical (e.g., `isSuper`).

The `isSuper` property should be mapped from Source to Target.

### Actual behavior

MapStruct does not map the boolean property isSuper from the Source class to the Target class when using the Builder pattern. It behaves as though the property does not exist and generates no mapping for it in the implementation.

There is no line of code generated for the isSuper property in the MapStruct-generated mapping code, even though both the Source and Target classes have this field, and the Builder pattern provides a method to set it.

For example, in the generated mapping implementation, the isSuper field is completely ignored:
`// No mapping for 'isSuper' is generated`
```java
Target.TargetBuilder target = Target.builder();
return target.build();
```

However, when I manually add the following line to the generated implementation, it works as expected:
`target.isSuper(source.isSuper());`

I believe MapStruct should generate this line automatically, as both the Source and Target classes contain the isSuper field, and the Builder pattern has a setter method for it. The lack of this mapping is unexpected and requires manual intervention, which should not be necessary.

### Steps to reproduce the problem

**1. Define a Source class with a boolean field**
The Source class contains a boolean field named isSuper, along with its getter and setter methods. This class serves as the source of the data that will be mapped to the Target class.

```java
class Source {
    private boolean isSuper;

    public boolean isSuper() {
        return isSuper;
    }

    public void setSuper(boolean isSuper) {
        this.isSuper = isSuper;
    }
}
```

**2. Define a Target class using the Builder pattern:**
The Target class contains the same boolean field isSuper and uses an inner TargetBuilder class to implement the Builder pattern. The builder has a method to set the isSuper field and returns the Target instance via the build() method.

```java
class Target {
    private boolean isSuper;

    private Target(TargetBuilder builder) {
        this.isSuper = builder.isSuper;
    }

    public static class TargetBuilder {

        private boolean isSuper;

        public TargetBuilder isSuper(boolean isSuper) {
            this.isSuper = isSuper;
            return this;
        }

        public TargetBuilder build() {
            return new Target(this);
        }
    }

    public boolean isSuper() {
        return isSuper;
    }
}
```

**3. Create a MapStruct interface to map Source to Target:**
The MyMapper interface defines a mapping method that uses MapStruct to convert a Source object into a Target object using the Builder pattern.

```java
@Mapper
public interface MyMapper {
    Target map(Source source);
}
```

**4. Generate the MapStruct implementation:**
After defining these classes and the mapping interface, use MapStruct to generate the implementation. In this step, you expect MapStruct to generate code that maps the isSuper field from Source to Target.

**5. Observe the generated code:**
The issue arises here. When MapStruct generates the mapping code, the boolean field isSuper from the Source class is not included in the generated Target object. It’s as though MapStruct does not recognize or handle the boolean field properly when using the Builder pattern.

**6. Manually add the missing mapping (optional):**
You can manually resolve the issue by adding the following line to the generated MapStruct implementation:
`target.isSuper(source.isSuper());`

This manually added line ensures that the isSuper field is correctly transferred from the Source class to the Target class, which is what MapStruct should ideally do automatically.

### MapStruct Version

MapStruct 1.6.0

**Comment by thunderhook** [comment]
This works as designed. MapStruct is using the JavaBeans specification to identify the fields to map.

It is defined like this:
> https://download.oracle.com/otn-pub/jcp/7224-javabeans-1.01-fr-spec-oth-JSpec/beans.101.pdf
> 
> In addition, for boolean properties, we allow a getter method to match the pattern:
> ```java
> public boolean is<PropertyName>();
> ```
> This “is<PropertyName>” method may be provided instead of a “get<PropertyName>” method, or it may be provided in addition to a `"get<PropertyName>"` method.
> In either case, if the `"is<PropertyName>"` method is present for a boolean property then we will use the `"is<PropertyName>`" method to read the property value.
> An example boolean property might be:
> ```java
> public boolean isMarsupial();
> public void setMarsupial(boolean m);
> ```

So, your current getter `Source#isSuper()` makes MapStruct think that there is a boolean property named `super`.
This generates a warning during compile: `java: Unmapped target property: "isSuper".` since target `isSuper` cannot be automatically mapped to the source parameter `super`.

For this to work properly, you must generate/write your getter of `Source` like the Java Beans specification, like one of these:

```java
    public boolean isIsSuper() {
        return isSuper;
    }
```

or:
```java
    public boolean getIsSuper() {
        return isSuper;
    }
```

I think we can agree that a boolean field should not be named starting with `is`. So, if you have the code under control I would suggest renaming it like an adjective (other than `super` that is obviously reserved). For further information see: https://stackoverflow.com/a/5322666

**Comment by SomeDeveloper13** [comment]
The most widely uses standard and which all main IDEs default to is to use isPropertyName for booleans.
This has been this way for at least the last 25 years.

**Comment by thunderhook** [comment]
> The most widely uses standard and which all the major IDEs default to is to use isPropertyName for booleans. This has been this way for at least the last 25 years.

Then I don't get your 👎 on my last comment. As I wrote, `isPropertyName` is perfectly fine, so in this case: `isIsSuper()` because the property name is `isSuper`.

Imagine a private field `boolean isSupplier` which is a flag for an abbreviated "input stream supplier" - using the `isSupplier()` getter would expose this field to the outside scope as `supplier`. This would be confusing at the other end.

Starting a boolean property with `is` just leads to problems, with various frameworks, e.g. [Jackson](https://stackoverflow.com/a/38969817). It is best to avoid it, especially if you have control over the code.

Just for the record: the title of the issue is misleading because it has nothing to do with the target builder pattern, which works fine. It is about the getter of the source. I have renamed it accordingly.
