### ISSUE TITLE
@Generated should list the maven version of the processor

### ISSUE THREAD

**Issue by sjaakd** [mapstruct/mapstruct#390]
I'm dealing with a problem that I'm not sure what compiler plugin is used by Maven. Somehow I believe it deviates from the one used by my IDE.

To make sure, it would be very handy if the compiler plugin lists its version in the @Generated tag.

**Comment by gunnarmorling** [comment]
+1 for adding the generator version to the generated output. An option for this seems reasonable.

The suggested "verbose" switch is something different IMO (I believe there is even an issue for it). But rather than adding comments to the generated code, we should create annotation processor diagnostics using the level NOTE, stating things such as candidate mapping methods and so on. It requires some testing though, e.g. I'm not sure how Maven deals with NOTE-level diagnostics.

**Comment by sjaakd** [comment]
Done!
