### ISSUE TITLE
Allow to map source enum constants which do not exist in target to null values

### ISSUE THREAD

**Issue by Fundu4ek** [mapstruct/mapstruct#509]

**Comment by sjaakd** [comment]
There is an ignore which you can specify on a mapping.. Would that do the trick?

**Comment by Fundu4ek** [comment]
I have a case when some enum constants can be mapped directly but others which can not I want to be null. And I can't find some trick to map source constants to null values in target (except using custom Mapper)

**Comment by Fundu4ek** [comment]
It would be nice to not trigger errors on such enum conversions, but achieve this result when using nullValueMappingStrategy = NullValueMappingStrategy.RETURN_DEFAULT for example

**Comment by sjaakd** [comment]
ah.. got your point.

**Comment by hyungsul** [comment]
Instead of implicitly mapping to null, can we add special value "null" and annotate the null mapping?
Since null is not a constant value in Java, it is not possible to use ``null`` directly in the annotation attribute value. But, it is possible to use String ``"null"`` and treat it as a special value in processor.
Enum values are in uppercase (by convention), it might be safe to introduce the special value in lowercase, especially for null. 

```java
@Mapper
public interface OrderMapper {

    OrderMapper INSTANCE = Mappers.getMapper( OrderMapper.class );

    OrderDto orderEntityToDto(OrderEntity order);

    @Mappings({
        @Mapping(source = "EXTRA", target = "null"),
        @Mapping(source = "STANDARD", target = "DEFAULT"),
        @Mapping(source = "NORMAL", target = "DEFAULT")
    })
    ExternalOrderType orderTypeToExternalOrderType(OrderType orderType);
}
```

How do you think? It could be done by small changes on [EnumMappingMethod.ftl](https://github.com/mapstruct/mapstruct/blob/master/processor/src/main/resources/org/mapstruct/ap/internal/model/EnumMappingMethod.ftl) and [EnumMappingMethod.java](https://github.com/mapstruct/mapstruct/blob/master/processor/src/main/java/org/mapstruct/ap/internal/model/EnumMappingMethod.java).

**Comment by gunnarmorling** [comment]
That's an interesting idea; As `null` is no valid enum value this seems safe to do for enum mapping methods.

In hindsight I am regretting that we re-used `@Mapping` instead of introducing a separate annotation such as `@EnumMapping`. This would have helped to avoid potential confusions.

**Comment by gunnarmorling** [comment]
@agudian @sjaakd That one should be addressed by now via value mappings, right?

**Comment by gunnarmorling** [comment]
That's doable via `@ValueMapping` now, thus closing it.

**Comment by urswiss** [comment]
this is not working with Mapstruct 1.4.2:
`    @ValueMapping(source = "COMPANY", target = "null")
    GenderEnum map(GenderCompany genderCompany);
`
So what would be `doable` @gunnarmorling ?

**Comment by filiphr** [comment]
@urswiss your syntax is incorrect. Have a look at the [Mapping Values](https://mapstruct.org/documentation/stable/reference/html/#_mapping_enum_to_enum_types) section of our documentation. 
You need to use `@ValueMapping(source = "COMPANY", target = MappingConstants.NULL)`
