### ISSUE TITLE
Support field access if visibility rules permit

### ISSUE THREAD

**Issue by gunnarmorling** [mapstruct/mapstruct#557]
If e.g. the target object is a plain "struct" with public fields, it should supported to write to these using direct field access. This should only be supported if the visibility rules permit that access, i.e. no reflection-based work-around otherwise.

**Comment by GilraenBurland** [comment]
+1 for this.

**Comment by cardosso** [comment]
Is this being considered?

For me this is the current deal breaker with MapStruct and the only reason I'm still using Orika. I don't want to fill my Hibernate domain objects with unnecessary getters and setters just to be able to use a mapping framework. It's a pitty this feature is missing because otherwise this is a great library.

This should only be done on public accessible fields and could even be made configurable (ie disabled by default).

**Comment by gunnarmorling** [comment]
Hey @cardosso, yes, it is considered for sure. We just did not yet find the time to implement it. If you are interested in helping out, let me know and I can help you to get started with hacking on MapStruct.

I will schedule this for the 1.1 release.

**Comment by cardosso** [comment]
That's great news thanks.
I never looked into the MapStruct source code, I guess I could check it out and see if I could be of some help implementing it if you could give me some quick guidelines. Not sure if I will have much free time during the next days though.

**Comment by gunnarmorling** [comment]
Hi, any help would be more than welcome. If you are interested, you may check out the resources given [here](http://mapstruct.org/contributing/#section-03) for getting started. The change would have to include adaptions the logic for identifying mappable properties as well as the templates for generating code working with properties.

**Comment by xiemeilong** [comment]
+1

**Comment by filiphr** [comment]
@gunnarmorling I had a look at this issue. And I think I can start working on it. I had a deeper look at the code and the inner workings. I think that in order to do this, we would need to add our own `Accessor` class which would wrap the `ExecutableElemement`(s) and the `VariableElements`. In our own `Accessor` we would add the methods which we need and get them from the underlying `Element`. 
The `Type` methods `getPropertyPresenceCheckers`, `getPropertyReadAccessors` and `getPropertyWriteAccessors` will need to be adjusted to return our wrapper. 

This is only the first step, I will have to investigate a bit more, about how to proceed once we have the fields for mapping. 

What do you think? Am I on the right path?

**Comment by filiphr** [comment]
Another thing, we are using the `AccessorNamingStrategy` with the `ExecutableElement`(s). I guess this is public and should not be modified?

**Comment by gunnarmorling** [comment]
> What do you think? Am I on the right path?

Yes, I think building such common abstraction would the right way to go.

> we are using the AccessorNamingStrategy with the ExecutableElement(s)

Good question, I reckon that it doesn't need to be changed. A field named "foo" really can only represent a property named "foo" and it cannot be a "presence checker" or any of the other method types.

**Comment by filiphr** [comment]
Official support for direct field mappings in MapStruct is possible since #928. You can try it out with the latest SNAPSHOT version. Once the documentation PR #982 is merged the ticket will be closed.

**Comment by filiphr** [comment]
With the merged documentation from #982 this new feature is completely implemented

**Comment by cpoissonnier** [comment]
Can't wait this feature to be available in the next version (I need this to use Mapstruct in my Playframework projects). Do you have any idea when 1.2.0 will be released?

**Comment by gunnarmorling** [comment]
1.2.0.Beta1 is planned for today :)

**Comment by cpoissonnier** [comment]
Amazing timing, thanks !
