### ISSUE TITLE
ambigious packages generated

### ISSUE THREAD

**Issue by lukaszostaniewicz** [mapstruct/mapstruct#581]
```
@Mapper
public interface A2AMapper {
    result.A[] asResult(List<source.A> source);
    result.A asResult(source.A source);
}
```
leads to
```
import result.A;
import source.A;
```
and
```
A2AMapperImpl.java:7: error: result.A is already defined in a single-type import
import source.A;
```

**Comment by vgt-tomek** [comment]
I was able to reproduce this issue in test case scenario and I did find out, why is this happening.
Method TypeFactory:isImported() is used to decide, if class should be imported in generated file, or fully qualified name should be used. It's doing it by collecting all imports in hashMap with class simple name as key. This bug is happening, when two different simple names leads to the same import: Car and Car[]
Easiest solution, that seems to work here is just removing suffix in this method, when array is provided as simple name, as can be seen here: https://github.com/vgt-tomek/mapstruct/commit/3fdfa13891f47d999ddba2dbffdd8cbb902a4a4d
@agudian, is something like that, an acceptable solution, or should it be handled differently?

**Comment by agudian** [comment]
That's kind of what I would have done myself. Just make sure that you remove all array dimensions and not just the first one :wink:

**Comment by gunnarmorling** [comment]
+1 Seems reasonable. Thanks for taking this over, @vgt-tomek!

**Comment by vgt-tomek** [comment]
Ok, then I should be able to finalize it and create pull request later today.

**Comment by gunnarmorling** [comment]
Done.
