### ISSUE TITLE
How come there are no generated *Impl classes?

### ISSUE THREAD

**Issue by reylibutan** [mapstruct/mapstruct#595]
I am following the Maven installation described in the documentation.

My project builds successfully but the moment I use the mapper, it throws a `ClassNotFoundException`. It is looking for the `*Impl.java` class.

I checked target/generated-sources, and no classes there.

P.S. I am using Spring Boot and I have rebuilt the project mutiple times (in STS and via mvn also)

**Comment by gunnarmorling** [comment]
Hard to say anything without knowing more details. How do the relevant parts of your POM look like?

**Comment by reylibutan** [comment]
At first, the `<pluginManagement>` wrapper is not there. But the moment I added the MapStruct plugin, I had the Maven error. I fixed it by adding `<pluginManagement>` wrapper as per this [SO answer](http://stackoverflow.com/questions/6352208/how-to-solve-plugin-execution-not-covered-by-lifecycle-configuration-for-sprin#answer-13733232).

No matter what I put in `<defaultOutputDirectory>` it is not being generated so I am assuming the task is not executed at all.

```
Plugin execution not covered by lifecycle configuration: org.bsc.maven:maven-processor-plugin:2.2.3:process (execution: process, phase: generate-sources)
```

```xml
	<build>
		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-maven-plugin</artifactId>
				</plugin>
				<!-- MapStruct: for DTO <-> Entity conversion -->
				<plugin>
		            <groupId>org.bsc.maven</groupId>
		            <artifactId>maven-processor-plugin</artifactId>
		            <version>2.2.3</version>
		            <configuration>
		                <defaultOutputDirectory>
		                    ${project.build.directory}/generated-sources
		                </defaultOutputDirectory>
		                <processors>
		                    <processor>org.mapstruct.ap.MappingProcessor</processor>
		                </processors>
		            </configuration>
		            <executions>
		                <execution>
		                    <id>process</id>
		                    <phase>generate-sources</phase>
		                    <goals>
		                        <goal>process</goal>
		                    </goals>
		                </execution>
		            </executions>
		            <dependencies>
		                <dependency>
		                    <groupId>org.mapstruct</groupId>
		                    <artifactId>mapstruct-processor</artifactId>
		                    <version>${org.mapstruct.version}</version>
		                </dependency>
		            </dependencies>
		        </plugin>
			</plugins>
		</pluginManagement>
	</build>
```

**Comment by gunnarmorling** [comment]
Seems like these are two different issues really.

*  it throws a ClassNotFoundException

Where/when is that raised? Can you show the exact stack trace?

* Plugin execution not covered by lifecycle configuration: org.bsc.maven:maven-processor-plugin:2.2.3:process (execution: process, phase: generate-sources)

This is raised by M2E (Maven support in Eclipse). Not sure why you get it, because M2E definitely supports the maven-processor-plugin. You may find [this post](https://developer.jboss.org/en/tools/blog/2012/05/20/annotation-processing-support-in-m2e-or-m2e-apt-100-is-out) helpful. The config should go to `plugins`, not `pluginManagement`.

You may also try to add the mapstruct dependency as a dependency to the compiler plug-in (as shown in that linked post) or add it as plain project dependency (which will work for sure).

**Comment by reylibutan** [comment]
Hi. I am now able to generate the source codes, thank you very much!

What I did was to remove `<pluginManagement>` as you suggested and just ignore the error in Eclipse (done by hovering the error message, and choose "Permanently mark goal process in pom.xml as ignored in Eclipse build").

Although by doing so, I need to manually do `mvn clean install` in the terminal.
