### ISSUE TITLE
Is there any option with mapstruct-processor to skip generate existed Impl Class ?

### ISSUE THREAD

**Issue by namvu80ap** [mapstruct/mapstruct#606]
After declared @Mapper Interface, I'd like to set the defaultOutputDirectory directly to my java package ( src/main/java ).
But eveytime i want to regenerate new implement class, I have to clean all existed impl classes. ( or comment out the header @Mapper of the existed interface ).

There is any option in the plugin mapstruct-processor to skip generate the existed impl class? ( ex : re-generate-sources )

**Comment by agudian** [comment]
Hi,

Usually, mixing manually created and generated stuff in the same source folder creates all kinds of trouble and you should avoid it. The MapStruct annotation-processor is meant to run on each compilation of your sources, so that you can be sure the generated classes reflect the current state of your bean classes. 
An incremental compiler (eg the one in Eclipse) can decide when to compile only parts of the code and thus call the annotation-processors only for some types - and such compilers can usually deal with existing generated sources that are overwritten. But it's up to the compiler at that point. An annotation processor has no say in it.

But again: just leave the generated sources in an extra directory, just as maven, eclipse and all other tools suggests. Even if you do the generation only on-demand and not automatically with each build.

Please let us know more if you think that this really doesn't fit your use case.

**Comment by namvu80ap** [comment]
Hi,

Thank you for your advice, I let it generate as maven do and remove the defaultOutputDirectory  setting. Then set mapstruct.defaultComponentModel and all the map interface's componentModel to spring. 

It work good now.

Thank again.
