### ISSUE TITLE
Mapping Iterable<?> object to an object instead of collection

### ISSUE THREAD

**Issue by maurofran** [mapstruct/mapstruct#607]
Mapping an java.lang.Iterable object (e.g. org.springframework.data.domain.Page) to an object it's not possible because the target object must implement the Iterable interface.
If the target object implement the Iterable interface, other fields are not mapped.

**Comment by agudian** [comment]
Could you give us an example of what you have and what you would expect to be generated?

**Comment by maurofranceschini** [comment]
The example is the following (using a standard spring data class):

```java
import org.springframework.data.domain.Page;

@Mapper
public interface CustomerMapper {
    List<CustomerDTO> mapCustomerListToDTO(List<Customer> customers);
    
    PageDTO<CustomerDTO> mapCustomerPageToDTO(Page<Customer> customers);
}
```
where `PageDTO` is something like this:

```java
public class PageDTO<T> {
    private List<T> content;
    private long number;
    private long size;
    private long totalElements;
    private long totalPages;

    // Getters and setters...
}
```
and `Page` is:

```java
public interface Slice<T> extends Iterable<T> {
    int getNumber();
    int getSize();
    List<T> getContent();
    
    // Other properties...
}

public interface Page<T> extends Slice<T> {
    int getTotalPages();
    int getTotalElements();
}
```

and the expected code should be 

```java
public class CustomerMapperImpl implements CustomerMapper {
    @Override
    public List<CustomerDTO> mapCustomerListToDTO(List<Customer> customers) {
        // Standard implementation of method
    }
    
    @Override
    public PageDTO<CustomerDTO> mapCustomerPageToDTO(Page<Customer> customers) {
        if (customers == null) {
            return null;
        }

        PageDTO<CustomerDTO> pageDTO = new PageDTO<>();

        pageDTO.setSize(customers.getSize());
        pageDTO.setNumber(customers.getNumber());
        pageDTO.setTotalElements(customers.getTotalElements());
        pageDTO.setTotalPages(customers.getTotalPages());
        pageDTO.setContent(mapCustomerListToDTO(customers.getContent());

        return pageDTO;
    }
}
```

The problem is that `Page<T>` extends `Iterable<T>` and the framework tries to handle as a collection, complaining me that the result is not a collection type.

**Comment by eXamadeus** [comment]
I also am running into this issue.  Maybe there would be a way to build an `@IgnoreIterable` annotation that could be placed on the mapping method?  Or `@MapAsObject`...

``` java
import org.springframework.data.domain.Page;

@Mapper
public interface CustomerMapper {
    List<CustomerDTO> mapCustomerListToDTO(List<Customer> customers);

    @IgnoreIterable
    PageDTO<CustomerDTO> mapCustomerPageToDTO(Page<Customer> customers);
}
```

**Comment by filiphr** [comment]
Maybe we can reuse the already present `@BeanMapping` annotation for this. And if it is there then the check will not occur, i.e. it will be allowed to map non-iterable to iterable and vice-versa.

Also there is a workaround for this (I think due to a bug 😄). The check is only done between the first source parameter and the result type. You will need a wrapper type though, in order to be able to use `@Mapping` and multiple parameters. Which means that the following will work:

```java
public class Wrapper<T> {
    private T value;
    //getters and setters
}

public interface MyMapper {

    @Mapping(source = "customers", target = "value")
    Wrapper<PageDTO<CustomerDTO>> map(Integer dummy, Page<Customer> customers);

}
```

The check will be done between `Integer` and `Wrapper` and it'll be allowed. In order not to expose the dummy you can do something like:

```java
public abstract class MyMapper {

    public PageDTO<CustomerDTO> map(Page<Customer> customers) {
        return map(1, customers).getValue(); //Maybe do null checks as well
    }

    @Mapping(source = "customers", target = "value")
    protected Wrapper<PageDTO<CustomerDTO>> map(Integer dummy, Page<Customer> customers);

}
```

**Comment by heese** [comment]
Why do you need `PageDTO`? I think Springs' `Page` works quite well as DTO object (e.g., easily serialisable to JSON).  Although MapStruct  does not support the mapping of `Page` directly a custom mapping is quickly written.

```
@Mapper
public interface CustomerFileMapper {
  CustomerDTO toRest(Customer entity);

  default Page<CustomerDTO> toRest(Page<Customer> page) {
    return page.map(this::toRest);
  }
}
```

**Comment by fabriciolemos** [comment]
One issue serializing `Page` would be, if the client is a Java application, Jackson will need a concrete class to deserialize it, since `Page` is an interface. `PageImpl`, the implementing class, does not have a default constructor and Jackson would have a problem with it.
Even though there's a workaround for this, it would be nice if MapStruct  could support this use case of `Iterable` mapping.

**Comment by lludwa** [comment]
+1

**Comment by rtisma** [comment]
+1

**Comment by filiphr** [comment]
There is no need to post comments with +1. 

There is more than one workaround for this issue. I think the easiest is the one proposed in https://github.com/mapstruct/mapstruct/issues/607#issuecomment-331772835. Serializing Spring Page is not an issue, since that interface is build for that. For deserializing you can still use your own `PageDto`.

Therefore, this issue is not high on our priorities. However, if someone is interested in providing support for this we are more than happy to help out. Good proposals were already given in https://github.com/mapstruct/mapstruct/issues/607#issuecomment-309512495, there is also the option to reuse `@BeanMapping` as I mentioned in https://github.com/mapstruct/mapstruct/issues/607#issuecomment-309547739

**Comment by sahebpreet** [comment]
Hi @filiphr ,

Can I pick this up?

For `@BeanMapping` approach, I think we can check [here](https://github.com/mapstruct/mapstruct/blob/8b22654abdfb005381124800ebc155af2de3c312/processor/src/main/java/org/mapstruct/ap/internal/processor/MethodRetrievalProcessor.java#L488) and the condition after it, for the presence of the `@BeanMapping`, which can be retrieved from [here](https://github.com/mapstruct/mapstruct/blob/8b22654abdfb005381124800ebc155af2de3c312/processor/src/main/java/org/mapstruct/ap/internal/processor/MethodRetrievalProcessor.java#L268), before calling validation method. Is it the correct approach?

Thanks,
Saheb Preet Singh.

**Comment by filiphr** [comment]
Hey @sahebpreet,

Yes you can pick this up. 

I think that your approach is good. This means that we would allow mapping from `Iterable` into some bean by marking the method with `@BeanMapping`. I think that `@BeanMapping` cannot be empty though. Perhaps we can just allow mapping between those types as is, without requiring anything special.

In any case feel free to do a PR where we can see how it will be used via some tests and the implementation.

If you have any questions feel free to ask them here or in our [Gitter room](https://gitter.im/mapstruct/mapstruct-users).

**Comment by xak2000** [comment]
> There is more than one workaround for this issue.

@filiphr [your workaround](https://github.com/mapstruct/mapstruct/issues/607#issuecomment-309547739) doesn't work for me as the generated `map(Integer dummy, Page<Customer> customers)` method tries to call `map(Page<Customer> customers)` to map `Page<Customer>` to `PageDto<CustomerDto>`. So this leads to recursion and `StackOverflowError`.

I also tried to create another `void map(Page<Customer> page, @MappingTarget PageDto<CustomerDto> pageDto)` method (with custom implementation to map `Page<T>` to `PageDto<D>`) in hope that MapStruct will prefer this method instead of 1-param variant, but no luck.

The generated code looks like this:

```java
    @Override
    public Wrapper<CustomerPage> map(Integer dummy, Page<CustomerEntity> page) {
        if ( dummy == null && page == null ) {
            return null;
        }

        Wrapper<CustomerPage> wrapper = new Wrapper<CustomerPage>();

        if ( page != null ) {
            wrapper.setValue( map( page ) );
        }

        return wrapper;
    }
```

I spent many hours trying to figure out how to create a base mapper for `Page<T>` to `PageDto<D>` and still no luck. :(

> Serializing Spring Page is not an issue, since that interface is build for that.

The point that `org.springframework.data.domain.Page` can be returned as DTO is not really good. This is a **domain** class, not DTO. The creator of spring-data also [said this](https://jira.spring.io/browse/DATACMNS-1244). So the other workaround also doesn't work, because it assumes that `Page` will be serialized to JSON, that is wrong approach (real fact from the history: 2 years ago, when people updated their spring-boot version to 2.0, the representation of this `Page` class is changed, because it was not intended to be used as DTO a serialized to JSON, so many projects were broken, because they were trying to use `Page` from spring-data as DTO).

Moreover, the other workaround doesn't work at all for me, because my `PageDto<D>` will be extended for each different item type. E.g. `CustomerPage extends PageDto<Customer>` and will contain additional meta-fields related to `Customer`.

So I want to have a base mapper (e.g. `PageMapper<T, D, P extends PageDto<D>>`), that is able to map `Page<T>` to `PageDto<D>` (with all fields of `PageDto`) and will be called automatically before more specific mapping method of `CustomerMapper` will try to map other fields of `CustomerPage`.

I tried to use `@InheritConfiguration` also with no luck. I think that is because MapStruct doesn't try to use inherited mappers of `Page` to `PageDto`, even if they are implemented manually, because it sees this objects as iterables and not as beans.

So, to be honest, I didn't found **any** workaround for this issue. One doesn't work, other doesn't satisfy the requirements (I don't want to return Spring's `Page` from controller, I want my custom `Page` with inheritance and additional meta-fields).

It will be very good to have a way to say to MapStruct: "Don't try to view this parameter as `Iterable`. Even if it implements `Iterable`, this doesn't mean you can just map it's elements. It has much more fields that iterable elements."

**Comment by kaliatech** [comment]
@xak2000 - Agreed that returning `Page` as DTO is not a good idea. However, per @filiphr's later comment, you can use a custom DTO with the approach given in [this comment](https://github.com/mapstruct/mapstruct/issues/607#issuecomment-331772835). 

Something like this (I did not run this through a compiler):

```
public class PageMapper<T> {

    public PageDto<T> toDto(Page<T> pageOfDtos) {

        PageDto<T> pageDto = new PageDto<>();
        pageDto.setContent(pageOfDtos.getContent());
        pageDto.setTotalElements(pageOfDtos.getTotalElements());
        pageDto.setTotalPages(pageOfDtos.getTotalPages());
        pageDto.setLast(pageOfDtos.isLast());
        pageDto.setNumber(pageOfDtos.getNumber());
        pageDto.setSize(pageOfDtos.getSize());

        return pageDto;
    }
}
```

Mapper:
```
@Mapper
public abstract class CustomerMapper {
    private PageMapper<CustomerDto> pageMapper = new PageMapper<>();

    public abstract CustomerDto toDto(Customer customer);

    public PageDto<CustomerDto> toDto(Page<Customer> page) {
        Page<CustomerDto> customerDtos = page.map(this::toDto)
        return pageMapper.toDto(customerDtos );
    }
}

```

**Comment by xak2000** [comment]
@kaliatech This should work, but you just implemented all page-mappings in custom code. :) What is the point to use MapStruct then?

My intention is to write base `PageMapper`, that will map `Page<T>` to `PageDto<D>` (together with page's elements, using abstract `D toDto(T domain)` mapper, that will be implemented or defined (through `@Mapping` anootations) in child mappers).

like this:

```
interface PageMapper<T, D, P extends PageDto<D>> {
  D toDto(T domain);
  P toDto(Page<T> page); // I can implement it here, but then MapStruct will not call it to map parent types
}
```

At the same time child mappers will need to map not just `Page<T>` to `PageDto<D>`, but `CustomerPage extends Page<T>` to `CustomerPageDto extends PageDto<D>`. And I want to avoid copy-paste of annotations/code for mapping base classes (`Page` to `PageDto`). So my `CustomerPage` to `CustomerPageDto` mapper should call base ` P toDto(Page<T> page)` mapper before mapping some additional fields of `CustomerPage` (like, I don't know... e.g. `averageCustomerAge`).

Like this class (and similar `CustomerPageDto`):

```
class CustomerPage extends Page<Customer> {
  private int averageCustomerAge;
}
```

And this mapper:

```
interface CustomerMapper extends PageMapper<Customer, CustomerDto, CustomerPageDto> {

  @Mapping(...)
  @Override
  CustomerDto toDto(Customer domain);

  // Unable to use @Mapping here because there is no way to say:
  // first, create CustomerPageDto instance, then call super.toDto(customerPageDto) then use @Mappings from this declaration
  // @InheritConfiguration also doesn't help here (I think because of Iterable).
  @Mapping(target = "avgAge", source = "averageCustomerAge") // will not work also because of Iterable
  @Override
  CustomerPageDto toDto(CustomerPage page);

}
```

Because I can't force MapStruct to consider `Page` as non-iterable, I unable to write **non-manual** mapping code from `Page<T>` to `PageDto<D>` in base `PageMapper<T, D>` (I mean this method: `P toDto(Page<T> page)`). But if I implement this method manually, then I unable to force MapStruct to use this method as base mapping method for ` CustomerPageDto toDto(CustomerPage page)` method (that overrides base `P toDto(Page<T> page)` method). The fact that `CustomerPage` implements `Iterable` also prevents to do it.

I only can write both methods (base  `P toDto(Page<T> page)` and overridden `CustomerPageDto toDto(CustomerPage page)`) manually, something like you suggested.

This manual approach also forces me to implement overridden `CustomerPageDto toDto(CustomerPage page)` method in each child mapper even when child mapper doesn't need to map any additional fields (like `averageCustomerAge`). This is because parent mapper can't create a new instance of child DTO, because it is written manually and it don't know the class of child DTO beforehand. The base method `P toDto(Page<T> page)` actually will look more like this `P toDto(Page<T> page, P target)` and I must instantiate that `target` manually in each child mapper.

Actually, the only workaround I found is to use decorators (together with `@DecoratedWith`). This almost work. Requires too many boilerplate for each child mapper, but works. But with decorators I found another problem: MapStruct ignores method implementation, if it is implemented in super-class of decorator. This leads that MapStruct generates it's own method, that calls the `delegate`, and my method from decorator doesn't have a chance to be called (the workaround is to override super method in each decorator class and just call super-implementation from it). But this is a different story and is not related to this issue.

**Comment by sahebpreet** [comment]
Hi @filiphr,

Sorry for the late reply, I got a bit busy lately.

I have pushed the initial version of code for this issue and raised a PR [here](https://github.com/mapstruct/mapstruct/pull/2210/files) Please have a look :) , and suggest any changes required.

Thanks,
Saheb Preet Singh.

**Comment by marceloverdijk** [comment]
Hi, any chance to have this backported to 1.4.x?

I'm having the same use case I would like to map a `org.springframework.data.domain.Page` to a custom object which is not an `Iterable`.

So I want to map Spring's `Page<Customer` to a custom `CustomerPage` where the latter looks like:

```
class CustomerPage {

    private List<Customer> items;
    private Boolean hasNextPage;
    private Boolean hasPreviousPage;
    private long totalCount;
    .. getters / setters ..
}
```

In my case the target (`CustomerPage`) is a "dedicated" page class, so not something like `PageDto<T>`.
I have many of these `CustomerPage` classes (like `ProductPage`, `InvoicePage`, etc.) as it is generated code and this cannot be changed. So the target in each of my mapper classes is different.

What would be the smartest way to do it until 1.5 is released?

**Comment by bilak** [comment]
> Why do you need `PageDTO`? I think Springs' `Page` works quite well as DTO object (e.g., easily serialisable to JSON). Although MapStruct does not support the mapping of `Page` directly a custom mapping is quickly written.
> 
> ```
> @Mapper
> public interface CustomerFileMapper {
>   CustomerDTO toRest(Customer entity);
> 
>   default Page<CustomerDTO> toRest(Page<Customer> page) {
>     return page.map(this::toRest);
>   }
> }
> ```

There is an problem if you use some generator like `openapi-generator-maven-plugin` which generates results based on what you have in definition. In that case the result `Page` is something different than spring's one (for example `CustomerPagedResult`). It would be really helpful to get all properties of given `Page` but collection and then re-map the collection by something like in your example `CustomerDTO toRest(Customer entity)`.
