### ISSUE TITLE
Configure different null value mapping strategies for bean and collection mapping methods through @Mapper/@MapperConfig.

### ISSUE THREAD

**Issue by sjaakd** [mapstruct/mapstruct#647]
@gunnarmorling : do you mean 'differentiate' between bean- and collection mapping strategy? Then we perhaps should do it before 1.0, right (breach of contract)?

so: 

``` java
public @interface Mapper {
    NullValueMappingStrategy beanNullValueMappingStrategy() default NullValueMappingStrategy.RETURN_NULL;
    NullValueMappingStrategy iterableNullValueMappingStrategy() default NullValueMappingStrategy.RETURN_NULL;
    NullValueMappingStrategy mapValueMappingStrategy() default NullValueMappingStrategy.RETURN_NULL;

```

?

(follow up of #640)

**Comment by gunnarmorling** [comment]
Hi, thanks for opening this one. I had in mind just adding `collectionNullValueMappingStrategy()`, leaving the current `nullValueMappingStrategy()` as is.

If only the latter was given, its setting would apply to all methods. The former would apply to collection methods (iterables, maps), overriding the former in case both are given. I don't think it's neccessary to differentiate between iterables and maps, as it's a good practice to return an empty collection regardless of their specific type.

That we we could do it in 1.1, adding a new member to the annotation is no problem.

WDYT?

**Comment by MrJohule** [comment]
Hi, i'm using version 1.1.0.Beta1.
How can i configure my mapper to map my POJO with this behaviours :
- NullValueMappingStrategy.RETURN_DEFAULT for collections (iterable and map)
- NullValueMappingStrategy.RETURN_NULL for beans

thx !

**Comment by sjaakd** [comment]
* `NullValueMappingStrategy` for beans, lists, maps: on config, mapper, bean level
* `NullValuePropertyMappingStrategy` for properties: on config, mapper, bean, mapping level (intended for update methods only)
* `NullValueCheckStrategy` for properties: on config, mapper, bean, mapping level

**Comment by laffuste** [comment]
I'm looking for the same behaviour @MrJohule mentioned. The answer is it's not possible: it's an all or nothing. Correct?

**Comment by maespinoza** [comment]
Same here, looking for the same behavior than @MrJohule. Configure a Mapper such that all the List -> List conversions follow a RETURN_DEFAULT strategy and all the rest follows RETURN _NULL, this is not possible right now.

**Comment by chris922** [comment]
Hum.. The null value (property) mapping strategies are planned to be redesigned for 2.0 as we encountered a few more possible issues and high complexity with the current design.

Nevertheless I thought that there will be a `nullValueMappingStrategy` field available on `@Mapping` level, so that you can configure these exceptions on your own. But it is not available. In case this would be available you would be able to define the `RETURN_DEFAULT` only for your collection/map mappings. Still a bit cumbersome and one strategy that just return defaults for collections/maps would be easier, but I think that we will not put such an effort in these strategies until the redesign.

@sjaakd WDYT? Should we add `nullValueMappingStrategy` to `@Mapping` as a kind of quick-win?

**Comment by foal** [comment]
Same here, looking for the same behavior than @MrJohule.
