### ISSUE TITLE
Unable to get desired response where my source object attribute have recursive reference to source

### ISSUE THREAD

**Issue by sgbalakumar** [mapstruct/mapstruct#659]
My Source Object
	
	public class Source {
              private SourceDetails sourceDetails;
              private Source parent;
              private List<Source> children = null;
        }
	
My Target Object
	
	public class Target {
             private TargetDetails sourceDetails;
             private Target parent;
             private List<Target> children = null;
       }
	
Please note my source object attribute have recursive reference to source object itself (i.e List<Source> is of Source type).
I try to have my source object mapped to target using map struct, due it's recursive call, at certain point in execution it assign null instead of actual value. At time, i also get stack overflow exception for different set of data.

**Comment by sjaakd** [comment]
@sgbalakumar, @agudian  is this a duplicate of #469?

**Comment by agudian** [comment]
@sjaakd, that was my thought as well.

@sgbalakumar, handling cyclic structures is not supported out-of-the box, yet. 
In your case, I'd like to point out that the problem is not be that the type itself allows cycles - as you observed, if you hand in an instance _without_ cycles, you end up with with something that has `null` as parent. If you have an instance that _contains_ cycles, you end up with the stack-overflow exception, as we don't yet support what's described in #469.
When in doubt, just check the generated code to find out what happens with your input... :)

**Comment by agudian** [comment]
If it's ok with you, I'd like to close this issue. @sgbalakumar, please re-open if you see something here is not related to #469 and requires something else.
