### ISSUE TITLE
Add blueprint as a component model option.

### ISSUE THREAD

**Issue by samwright** [mapstruct/mapstruct#664]
Blueprint xml files can be generated from JSR330 annotations using the blueprint-maven-plugin, but it requires that each mapper class is annotated with `@Singleton` (the `@Named` annotation is still valid, but only as an additional qualifier for selecting the bean to inject). Currently the `jsr330` component model only annotates them with `@Named`.

Possible solutions:
1. Annotate mapper classes with `@Singleton` (in addition to `@Named`) when `jsr330` is used as the component model.
2. Add a new component model option `blueprint` which acts like `jsr330` does currently, but also adds the `@Singleton` annotation.
3. Allow for the mapper class implementation to be annotated arbitrarily, for example by annotating the mapper interface with something like `@AnnotateWith(MyCustomAnnotation.class)`.

Solution 1 is the simplest, and I can't think of any problems arising from it, so that's my preference. If people see this as a good idea, I'd be happy to implement it.

**Comment by agudian** [comment]
Well, I like options 1 and 3, with a tendency towards the latter.

Adding `@Singleton` is super simple and apperently works for your case, but to be honest I don't have that much experience with JSR 330 in the wild, so I can't really assess the impact of this.

Allowing to add a custom annotation to the generated types is something that would be useful for other stuff aswell, not only in JSR 330, but also for CDI and Spring. But going that way would also mean that we'd need an idea how to configure that the annotation is to be added instead of those we currently add or in addition to, or to add the annotations with arguments (I could imagine that'd be on the wishlist pretty soon).

In any case - let's keep an eye on this for our release after the upcoming 1.0.

**Comment by samwright** [comment]
I've implemented option 1 (see pull request) and yes, it is super simple. From my limited understanding, adding `@Singleton` is the correct way to do JSR330, though some DI frameworks assume that a class annotated with `@Named` is a singleton. As such I'd see option 1 as a simple fix for an eclectic bug.

Option 3 would then be a new feature which I have no need for (once option 1 is implemented) so I wouldn't want to spend effort implementing it without a clear user story justifying it.

If you agree with all that, I'll write some tests for the commit with a view to merge it after 1.0 and after someone with more experience of JSR330 than I confirms that this approach is sensible.

**Comment by samwright** [comment]
Updated pull request

**Comment by agudian** [comment]
PR applied. Thanks, Sam!
