### ISSUE TITLE
Support of numberFormat for Number to String mapping

### ISSUE THREAD

**Issue by gbrehmer** [mapstruct/mapstruct#679]
like dateFormat support, especially needed for decimal value to string conversion.

**Comment by gunnarmorling** [comment]
Ah, yes, good point. Would you be interested in helping out with implementing this?

**Comment by cliedeman** [comment]
Hello

I started work on implementing this and had a question:

To add numberFormat to the mapping annotation I had to touch over 10 files - and this would need to be done if ever another format parameter is added. Is there any reason we can't rename dateFormat to format - deprecating dateFormat for one release...

**Comment by gunnarmorling** [comment]
Hey @cliedeman, cool, thanks for working on this! When creating it, I preferred the explicitness of the name `dateFormat` but I can see that `format` offers some more flexibility. Are there any other format parameters you can see right now?

If not I'd say let's add `numberFormat` and remove them both in favor of `format` in MapStruct 2.0 (whenever that'll be).

**Comment by cliedeman** [comment]
@gunnarmorling I thought as much and started in that style.

I have created a first draft pull [request](https://github.com/mapstruct/mapstruct/pull/714) just to check if I am on the right track.

I have only handled a few conversions and the code can definitely be made more clean. Finding a good way to share the formatter code across all the conversions is a bit tricky.

I am also getting a failure with the eclipse compiler but I think this may be due to a different locale being used. 

Errors:
NumberFormatConversionTest.shouldApplyReverseStringConversions:86 expected:<345[346.456756]> but was:<345[.0]>
  NumberFormatConversionTest.shouldApplyStringConversions:52 expected:<'1[.]00'> but was:<'1[,]00'>

Ciaran

**Comment by sjaakd** [comment]
The examples current contain an example for rounding and extending BigDecimals using qualifiers. Could this PR be extended in such a fashion that it uses numberFormat icw built in method to achieve the same? So, only use a built in method for this purpose when a numberFormat is specified?

**Comment by cliedeman** [comment]
@sjaakd Where are these examples? I can't seem to find them

**Comment by sjaakd** [comment]
Checkout Mapstruct/examples. There are 4 currently which should be accompanied with more and a blog 👍

**Comment by sjaakd** [comment]
Closed with #811
