### ISSUE TITLE
Auto generated Joda LocalDate to XMLGregorianCalendar mapper produces runtime errors

### ISSUE THREAD

**Issue by gbrehmer** [mapstruct/mapstruct#689]
I don't know whether this is offically supported because this conversion is not mentioned in the documentation.
Nevertheless the generated code generates runtime errors, because the formated string can not be parsed by gregorian calendar.

Example generated method:
```
stringToXmlGregorianCalendar( DateTimeFormat.forPattern( DateTimeFormat.patternForStyle( "L-", Locale.getDefault() ) ).print( obj.getLocalDate() ).trim() , null ) 
```

String Output before conversion to XMLGregorianCalendar e.g.: "1. Januar 2015"
Exception during conversion: java.lang.IllegalArgumentException: For input string: "1. Ja"

Joda 2.9

**Comment by gbrehmer** [comment]
The strange thing here is, that in another case (other mapper / output model) with same input & output type, it generates another (correct) mapping method:

```
dateToXmlGregorianCalendar( obj.getLocalDate().toDate() )
```

**Comment by gunnarmorling** [comment]
I don't think it is supported. Would you be interested in helping out with that one?

**Comment by agudian** [comment]
I guess what we need is are specific LocalDate<->XmlGregorianCalendar built-in mapping methods to avoid the funny choosing of two-step conversions here (which might be influenced by what built-ins were added for other properties to the same mapper before).

**Comment by sjaakd** [comment]
I'm not sure whether the conversion makes sense from `LocalDate` to `XmlGregorianCalendar`. The latter one contains date and time. The first one only a date. So, in essence you have to choose what time part to generate in `XmlGregorianCalendar`. I'm not in favor of MapStruct making that choice. Especially considering time-zones.

I reckon the following conversions make sense:
 DateTime <> XmlGregorianCalendar

And doubtful about l:
XmlGregorianCalendar > `LocalDate` 
XmlGregorianCalendar > `LocalTime`
XmlGregorianCalendar <> `LocalDateTime`

The latter ones immediately raise the question: "Which `LocalDate`  and which `LocalTime`. According to the Joda Javadoc, these do not contain time zone information. And their name suggest that they should represent the date and time locally (at the locale). 

This means that MapStruct would:
 
1. have to calculate the time somehow (or use java classes to do so), given de timezone information present in the XmlGregorianCalendar, taking into account things like DST and the likes.. 

2. Or, alternatively leave time zone information out.

Anyway.. both choices are user choices, that we cannot make.

**Comment by sjaakd** [comment]
I wrote some small tests. The current conversion (see above) from 
`XmlGregorianCalendar` <> `DateTime` runs in two steps: via `java.util.Date`.
1) the first part from /to `XmlGregorianCalendar` to `java.util.Date` is a built in method
2) and the latter from/to `DateTime` a conversion.

TimeZone information (and representation) is lost due to the fact it runs via `java.util.Date` which is in essence the epoch and carries no timezone information. Ideally the mapping from `DateTime` to `XMLGregorianCalendar` would like: 
```java
        DateTime dt = new DateTime(2010, 1, 1, 1, 1, 1, 100, DateTimeZone.forOffsetHours( -1 ) );
        XMLGregorianCalendar gcal = DatatypeFactory.newInstance().newXMLGregorianCalendar(
            dt.getYear(),
            dt.getMonthOfYear(),
            dt.getDayOfMonth(),
            dt.getHourOfDay(),
            dt.getMinuteOfHour(),
            dt.getSecondOfMinute(),
            dt.getMillisOfSecond(),
            dt.getZone().getOffset( null ) / 60000 );
```
Conserving time zone information.

Concluding:
1) that should be a builtin method..

2) This makes you think.. Should we trust MapStruct to make 2 steps conversions / builtin method concerning date types? Perhaps we should mark somehow in a conversion / builtin what is allowed in two steps an which not.

**Comment by sjaakd** [comment]
Specific built-in methods added. @gbrehmer .. can you verify?
