### ISSUE TITLE
Get access to mapper instance

### ISSUE THREAD

**Issue by sjaakd** [mapstruct/mapstruct#751]
I keep on finding cases were I need access to a used mapper instance (abstract class).

Cases I came up with so far: 
1. Inserting sequence numbers.
2. Reuse of common base mapper (were you need an instance variable on the mapper distinguising between behaviors).

The only way to do this  (in the standard component model) is `ThreadLocals`. 

For scenario 1. It woudl be nice if the generated mapper generates standard getters on its instance variables when a getter is present in the `@Mapper` interface / abstract class with a used mapper as return type.

For scenario 2. It could help if a used mapper is constructed by factory as well (not only target objects).

See also http://g00glen00b.be/mapstruct/

**Comment by afdia** [comment]
I also needed this feature some time ago where I had a state mapper which is used by several other mappers.
The state mapper maps state objects but also fills in missing fields based on a state-cache it holds (so if only iso3 is available it fills in name and vice versa)

The problem is that the state-cache is expensive to initialize and should be reused as a singleton, but the application doesnt use jsr330 or spring.

If I wouldn't use MapStruct I could pass arguments in the constructor and had full control over the objects it uses. e.g.:
```
StateCache stateCache // passed via constructor to this class and already initialized
OtherMapper otherMapper = new OtherMapper(new StateMapper(stateCache));
```

In MapStruct we cannot pass constructor arguments, so I tried to use a setter to set the cache after the initialization of OtherMapper, but I do not get the reference to StateMapper (because it's a private field within ConcreteMapperImpl)

If I understand your issue description correctly, after your change it should be possible to add the following method to OtherMapper
```
abstract StateMapper getStateMapper();
```
and it would create an implementation which returns the private StateMapper instance?

**Comment by sjaakd** [comment]
@afdia , thanks for your response. The PR which is now out there is going to be replaced. My current ideas:
1. Generate constructors with overloaded arguments whenever you use an abstract class as `Mapper` definition. I've got a working solution for that.
2. Generate a factory implementation as well. The user would have to define the factory methods in an interface or abstract class which would be available via the `Mappers` : so `Mappers.getFactory(<factory-interface>) interface similar like a mapper would be. 
3. For the solution of nested mappers, I would like to propose to add the possibility to appoint a hand written factory (perhaps via the already existing 'uses' mechanism). 
4. The user could write such hand-written factory and delegate to the proper overloaded constructor via the user defined interface and obtained generated factory.

 I still need to study how this would work with the other component models. 

WDYT?

**Comment by sjaakd** [comment]
As an addition: the problem with the current implementation is that we advertise a singleton pattern to create a nested mapper. Exposing a getter would imply all kinds of unexpected thread safety issues.

**Comment by afdia** [comment]
Sorry this post is longer than I expected ;)

I will first answer with a general comment about your thread safety concerns:
I guess with "advertise a singleton pattern", you're talking about the suggestion with an INSTANCE field in http://mapstruct.org/documentation/1.1/reference/html/index.html#retrieving-mapper

Using this singleton approach, my example with the StateCache would only work if I made the StateCache to a singleton which is retrieved from the StateMapper using a static getInstance() method which I want to avoid, because the StateMapper should be easy to test and reuse (e.g. I use one testcase with an empty cache and another one with a filled cache)

In general I'm not a fan of objects which enforce their own "singleton-ness" because (to stay with my example) perhaps an application uses the statemapper on two different locations with different state caches, which means the statemapper cannot be a singleton.
Or more general, if a mapper uses an external dependency, there may be usecases where multiple instances of this mapper with difference versions of this external dependency may be needed.

Therefore I think it's OK to pass the responsibility to handle these thread safety issues to the developers, which means they have to make sure that the mapper is instantiated as a whole (including possible setter calls to set the external dependencies) before they make it available for usage.

---

The only way to make sure that an instance of a mapper is threadsafe, which means it either doesn't exist or is fully initialized would be the usage of constructors. In combination with the comment about "not enforcing singleton-ness" it would mean that external dependencies must be passed as arguments to the constructors.

So I guess the best solution would be a constructor-based approach with potential "shortcuts" for the simple usecases (no external dependencies which means singleton mappers should work)

Your suggested step 1 is the correct way, because it offers the developer of an abstract mapper class a way to integrate MapStruct with the object creation, but instead of a factory-based approach I would use constructor injection alone:
```
abstract class StateMapper {
abstract StateMapper(StateCache cache) { this.cache = cache;}
}
abstract class OtherMapper {
abstract OtherMapper(StateMapper stateMapper) {this.stateMapper = stateMapper;}
}
```
The application could then instantiate this class manually as mentioned in my previous post:
```
StateCache stateCache // passed via constructor to this class and already initialized
OtherMapper otherMapper = new OtherMapperImpl(new StateMapperImpl(stateCache));
```

This approach would also have the usual advantages of constructor injection (one place to see all external dependencies, may they be other mappers or a cache), easy to instantiate mappers in junit tests, easy to replace nested mappers in unit tests,...
In case of a component model, the `@Inject` should be moved to the constructor and it will immediately work with DI frameworks.

---

This approach would be quite similar to a componentModel approach which has mappers as private fields which are null until the DI framework instantiates them.
In this case, the constructor would instantiate them (componentModels would simply annotate the constructor which would also fix #571).

So I would say if the current singleton pattern should stay the default componentModel (which is fine because it works perfectly as long as you do not need such enhanced features), I would say this should be a separate componentModel="constructors" (perhaps there is a better name)

You wouldn't need any specific syntax for mapper-factories and the user simply has to decide if he wants the simple model or if he wants to have more control over the mappers with the additional responsibility of constructing them himself.

What do you think? :)

**Comment by sjaakd** [comment]
> I will first answer with a general comment about your thread safety concerns:
> I guess with "advertise a singleton pattern", you're talking about the suggestion with an INSTANCE field in http://mapstruct.org/documentation/1.1/reference/html/index.html#retrieving-mapper

Indeed. And in our examples and test cases. So, we don't want to break with that approach, since many users are already using that kind of singleton approach. A new mechanism would have to be complementary to what's currently out there.


> The application could then instantiate this class manually as mentioned in my previous post:
> `StateCache stateCache // passed via constructor to this class and already initialized OtherMapper otherMapper = new OtherMapperImpl(new StateMapperImpl(stateCache));`

The main problem here is that the implementation classes do not exist prior to kicking of the annotation processor (compilation). So your IDE would initially flag those as compilation failures. Other frameworks (e.g. XJC) do work similarly, hence I personally like to kick them of in a separate maven project and use that as library (not mixing source code with generated code). MapStruct does not have this problem, since it uses self defined interfaces. This is why MapStruct uses this small piece of reflection logic (Mappers.getMapper) to get to a mapper implementation in the default component model (none). 

My solution tries to limit that to a factory. So, the user defines the factory interface, MapStruct does the remainder.

**Comment by afdia** [comment]
I understand that you don't want to break with that practice, but such a manual constructor call would still be possible even if you add the factories, because the generated Impl classes would have to implement the constructor anyways and calling them manually or using the generated factories would be a matter of taste.

Initially I though you would let the user write factory implementations and not only interfaces which would mean the user has the same "external dependency" problem, but your suggestion of letting the user write only factory interfaces instead, it should be doable without temporary compile errors (because Mapstruct can use the Impl classes within the factory implementation.

Am I right that the code for this example would look similar to the following?
```
OtherMapperFactory {
OtherMapper create(StateMapper stateMapper);
}
StateMapperFactory {
StateMapper create(StateCache stateCache);
}
```
Using the factories would look like:
```
OtherMapperFactory otherFac = Mappers.getFactory(OtherMapperFactory.class);
StateMapperFactory stateFac = Mappers.getFactory(StateMapperFactory.class);
OtherMapper = otherFac.create(stateFac.create(stateCache));
```

Is this correct? Mapstruct could generate the implementation for the factory (e.g. by matching the number of arguments with the number of constructor arguments of the class it creates)

I still see one remaining problem: How does MapStruct generate a mapper which has an abstract constructor, if the user calls Mappers.getMapper(StateMapper.class)? I guess it can only throw an exception which tells the user that mappers with constructor arguments can only be instantiated using a factory, right? Or you would have to force the user to always specify a no-arg constructor in addition to any others.

**Comment by sjaakd** [comment]
> I understand that you don't want to break with that practice, but I guess such a manual constructor call would still be possible even if you add the factories, right? Because the generated Impl classes would have to implement the constructor anyways and calling them manually or using the generated factories would be a matter of taste.

Thats true.  Similar as actually is the case now.


> Using the factories would look like:
`OtherMapperFactory otherFac = Mappers.getFactory(OtherMapperFactory.class);
StateMapperFactory stateFac = Mappers.getFactory(StateMapperFactory.class);
 OtherMapper = otherFac.create(stateFac.create(stateCache));`

Almost. There will be 3 steps.

User defines a state full mapper

```java
public abstract StateFullMapper {
   
   private SomeState someState;

   protected StateFullMapper( SomeState someState ){
         this.someState = someState;
   }

   public ADto map( AEntity entity ) {
     //do something with someState in mapping method 
   }
}
```
And a factory (interface)

```java
public interface MapperFactory {

    StateFullMapper  createStateFullMapper(SomeState state);
}
```

MapStruct will generate the `StateFullMapperImpl` and the  `MapperFactoryImpl`. The `StateFullMapperImpl` will delegate to the constructor in `StateFullMapper`. The user can indeed obtain the implementation via:

```java
 MapperFactory stateFac = Mappers.getFactory(MapperFactory);`
```

Now suppose that you would build another mapper that would use mapping methods in the `StateFullMapper`.  You'll have to define  a handwritten factory.

So:

```java
public class HandWrittenFactory {

    private static SomeState someSharedState = new SomeState();
    private static MapperFactory factory = Mappers.getFactory(MapperFactory);`

    public static StateFullMapper createStateFullMapper() {
          return factory.createStateFullMapper( someSharedState );
   }
}
```

```java
@Mapper( uses = HandWrittenFactory.class )
public interface AnotherMapper {

 .......
}
```

> Or you would have to force the user to always specify a no-arg constructor in addition to any others.

I reckon my explanation above explains my ideas.. 

The first steps are clear. Its the latter steps that I still doubt a bit about.

**Comment by afdia** [comment]
Looks good to me, but I see two potential problems with your example (correct me if I'm wrong):

1. what happens if someone calls `Mappers.getMapper(StateFullMapper.class)` or uses `@Mapper(uses = StateFullMapper.class)`?
Without an empty arg constructor on `StateFullMapper.class`, such a call couldn't initialize the class, because it doesn't know what to pass as the `SomeState` argument.

I guess the easiest way to fix this problem is make a rule that there must always exist an empty constructor (either implicitly when a class has no constructor at all or it must be added explicitly when the user specifies another constructor). This is quite common for serialization, JPA, ... so I guess it's ok to impose such a restriction.

2.
```
@Mapper( uses = HandWrittenFactory.class )
public interface AnotherMapper {}
```
will only work if the HandWrittenFactory.class instantiates the shared state itself (as in your example with `someSharedState = new SomeState();`).
If it's an application wide shared state which must also be passed to `AnotherMapper.class`, MapStruct cannot use the factory, because the factory method `createStateFullMapper()` would also need `someSharedState` as its parameter.

Therefore I assumed that factories would always work with the interface-based-approach (which you use to construct instances of `StateFullMapper.class` but not `AnotherMapper.class`).

I will use your example to explain it (and also add another nested mapper `StatelessMapper.class` to show the difference in the generated class).
```
@Mapper( uses = {StatelessMapper.class, StateFullMapper.class} )
public interface AnotherMapper {
	protected AnotherMapper(StateFullMapper stateFullMapper) {
		this.stateFullMapper = stateFullMapper;
	}
}
```
would generate the class:
```
public class AnotherMapperImpl {
	private StatelessMapper statelessMapper = new StatelessMapper(); // same as current MapStruct behavior
	private StateFullMapper stateFullMapper; // do not initialize because the constructor handles it

	protected AnotherMapperImpl(StateFullMapper stateFullMapper) {
		super(stateFullMapper);
	}
}
```
That way StateFullMapper is a dependency for AnotherMapper in the same way as SomeState is a dependency for StateFullMapper.

This would fix the problem with application-wide-shared-state (because you would simply add another factory interface for `AnotherMapper.class`)
```
public interface AnotherMapperFactory {
    AnotherMapper createAnotherMapper(StateFullMapper stateFullMapper);
}
```

and the `uses` argument of `@Mapper` would probably be simpler to understand because it simply specifies which other mappers are used but not how they are constructed.

The instantiation of nested mappers is either via autogenerated `statelessMapper = new StatelessMapper();` or via constructor argument if present.

**Comment by sjaakd** [comment]
> I guess the easiest way to fix this problem is to make a rule that there must always exist an empty constructor (either implicitly when a class has no constructor at all or it must be added explicitly when the user specifies another constructor). This is quite common for serialization, JPA, ... so I guess it's ok to impose such a restriction.

You are right.. Did not think about that one.

**Comment by sjaakd** [comment]
> Alternatively you could throw an exception if a call happens and no fitting constructor can be found.

That does not work...My IDE still wants something there, although throwing a RuntimeException. I reckon that calling the empty super() is the first think you need to do before anything else (including throwing an illegal state). So that will not fix the `Mappers.getMapper(StateFullMapper.class)`

**Comment by sjaakd** [comment]
Now, about step 3. That I did not really think that one through, I realized this morning when biking to my work :smile:. 

Let me come back and update this one with an example..

**Comment by sjaakd** [comment]
@afdia .. I think you have a good idea, ICW this could work for step 3 (took me some time to go through the steps). Now, one tiny remark: interfaces don't have constructors, but I reckon you meant abstract class.

Anyway. I combined your idea's (correct me if I'm wrong) and extended them with some more comments. Lets see if we match up (or if you still see holes). Perhaps @agudian  / @gunnarmorling have some additional ideas / remarks as well. 

Now, to sum it all up.

-----------
Define a StateFull mapper.

```java
@Mapper
public abstract class StatefullMapper {

    private SomeState someState;

    protected StatefullMapper() {
    }

    protected StatefullMapper(SomeState someState) {
        this.someState = someState;
    }

    public abstract BDto map (BEntity entity );

    public ADto map(AEntity entity) {
        //do something with someState in mapping method
        return null;
    }

}
```

MapStruct will generate:
```java
public class StatefullMapperImpl extends StatefullMapper {

    protected StatefullMapperImpl() {
    }

    protected StatefullMapperImpl(SomeState someState) {
        super( someState );
    }

    @Override
    public BDto map(BEntity entity) {
        // generated method;
        return null;
    }

}
```

And generate an error if the empty constructor is somehow missing.

-----------
Then, suppose you have another mapper, using this StateFullMapper

```java
@Mapper
public abstract class AnotherMapper {

    // the StatefullMapper is marked with annotation @Mapper, why not consider it as such
    // and let MapStruct look for mapping methods in this class just if it was a @Mapper( uses = 
    // StateFullMapper.class ). Also its accessible by its implementation because its has  
    // an accessor protected (or public).
    protected StatefullMapper myStatefullMapper;


    protected AnotherMapper( ) {
    }

    protected AnotherMapper( StatefullMapper mapper ) {
        this.myStatefullMapper = mapper;
    }

    public abstract CDto map(CEntity entity);

}
```

Note my comments int his class. MapStruct will generate

```java
public  class AnotherMapperImpl extends AnotherMapper {

    protected AnotherMapperImpl( ) {
        super();
    }

    protected AnotherMapperImpl( StatefullMapper mapper ) {
        super( mapper );
    }

    @Override
    public CDto map(CEntity entity) {
        CDto cDto = new CDto();
        cDto.setBDto( myStatefullMapper.map( entity.getBEntity() ) );
        return cDto;
    }
}

```
-----------
We want to be able to avoid calling non existing code. So, we define a Factory.

```java
public interface MapperFactory {

    StatefullMapper createStatefullMapper();

    StatefullMapper createStatefullMapper( SomeState state );

    AnotherMapper createAnotherMapper();

    AnotherMapper createAnotherMapper( StatefullMapper state );
}
```

MapStruct will generate:

```java
public class MapperFactoryImpl implements MapperFactory {

    @Override
    public StatefullMapper createStatefullMapper() {
        return new StatefullMapperImpl();
    }

    @Override
    public StatefullMapper createStatefullMapper(SomeState state) {
        return new StatefullMapperImpl( state );
    }

    @Override
    public AnotherMapper createAnotherMapper() {
        return new AnotherMapperImpl();
    }

    @Override
    public AnotherMapper createAnotherMapper(StatefullMapper state) {
        return new AnotherMapperImpl(state);
    }

}
```
-----------
Now, putting it together from a user perspective:

```java
        MapperFactory factory = Mappers.getFactory(MapperFactory.class); // or perhaps rather Factories.getFactory(clz)

        SomeState someState  = new SomeState();
        StatefullMapper statefullMapper = factory.createStatefullMapper( someState );
        AnotherMapper anotherMapper = factory.createAnotherMapper( statefullMapper );

        CDto cdto = anotherMapper.map( new CEntity() );
        // voila
```

@afdia : WDYT? Is this what you meant? 

I've part of the solution in place (can issue a PR for that). But I don't have a lot of spare time. Do you see a chance to help out a bit on the implementation?

**Comment by afdia** [comment]
>That does not work...My IDE still wants something there, although throwing a RuntimeException. I reckon that calling the empty super() is the first think you need to do before anything else (including throwing an illegal state). So that will not fix the Mappers.getMapper(StateFullMapper.class)

What I meant is: abstract classes (and their implementation) must not have an empty arg constructor by Java standards (I'm not sure what you mean with your IDE wants something there), but the consequence of not having one is that `Classname.class.newInstance()` calls won't work anymore for this class.
You get a `java.lang.NoSuchMethodException: Classname.<init>()` if you call the method.

That means if the user doesn't specify an empty arg constructor but still calls Mappers.getMapper() on the class, he will get this exception.

Of course you could catch and rethrow a better readable exception message such as "Mappers.getMapper() only works on mapper classes with an empty constructor. Either add one or use a factory for instantiation" (this text can and should be improved ;) )

Or as you suggested:
> MapStruct will simply not continue (and give an error) when you do not specify an empty constructor if you also specify an overloaded constructor.

Both solutions would work.
The first one has the advantage that you do not force the user to specify such a constructor if he knows that he will never call Mappers.getMapper() on this class, but has the disadvantage that if he somehow makes this call, he will only see the error at runtime.
The second solution forces the user to implement a constructor which he will probably never use, but on the other hand it will guarantee that Mappers.getMapper() will work on any mapper class.

I have a minor preference for the first solution, because I imagine in most cases where I have an external dependency for a mapper, it will not work without it, therefore the empty constructor would not be able to generate a "working mapper" anyways and I would never call Mappers.getMapper() for such mappers, but always use the appropriate factory for it.

---
about step 3:

yes I meant an abstract class instead of an interface :)

your example code matches my idea perfectly, so I guess we're on the same page now.

I agree with your minor change to avoid the unnecessary uses-attribute in the `@Mapper` annotation.
If I understand correctly, this could be generalized to "a mapper uses nested mappers if they are declared in the uses-attribute or if there exists a non-private, correctly named mapper field (in this case the developer is responsible for the correct instantiation)"

Unfortunately, at the moment I do not have much spare time either and without any experience in writing annotation processors and the MapStruct codebase I guess I cannot help out in actual coding. Perhaps I can find some time in a few weeks, but I cannot make any promises.

**Comment by sjaakd** [comment]
> What I meant is: abstract classes (and their implementation) must not have an empty arg constructor by Java standards (I'm not sure what you mean with your IDE wants something there),

I meant that one option is still to generate an empty constructor in the implementing class whilst the abstract mapper does not have one. 

```java
public abstract class MyMapper {

    Object someState;

    protected MyMapper(Object someState) {
        this.someState = someState;
    }

}
```

```java
public class MyMapperImpl extends MyMapper {

    public MyMapperImpl() {
        throw new IllegalStateException("empty constructor must be implemented in mapper");
    }

}
```

Not leading to the construction of the class with a clear message. But even that is not allowed according to the JLS (and my IDE).

> I agree with your minor change to avoid the unnecessary uses-attribute in the @Mapper annotation.
> If I understand correctly, this could be generalized to "a mapper uses nested mappers if they are declared in the uses-attribute or if there exists a non-private, correctly named mapper field (in this case the developer is responsible for the correct instantiation)"

Ah.. But the more fundamental change is that MapStruct needs to recognize a property in an abstract class as mapper for the 'OtherMapper' and not for the 'StatefullMapper'. Normally MapStruct generates one itself. This recognition could happen on the basis its protected / public AND the class instantiated had an `@Mapper` annotation. That is what I meant.

**Comment by afdia** [comment]
> Not leading to the construction of the class with a clear message. But even that is not allowed according to the JLS (and my IDE).

Ok now I understand the remark about the IDE, but I wouldn't generate a no-arg constructor in the impl class if it's missing in the abstract class. That way it would compile and only fail during runtime if one calls newInstance().
The readable error could be thrown with a catch-rethrow around the newInstance() call in Mappers.getMapper(), then you wouldn't have to declare an error throwing no-arg constructor in every impl class.

> Ah.. But the more fundamental change is that MapStruct needs to recognize a property in an abstract class as mapper for the 'OtherMapper' and not for the 'StatefullMapper'. Normally MapStruct generates one itself. This recognition could happen on the basis its protected / public AND the class instantiated had an @Mapper annotation. That is what I meant.

You're right, the naming convention wouldn't be necessary, because MapStruct could simply accept all accessible fields which refer to `@Mapper` classes as a nested mapper.

So the nested "mappers collection procedure" can be quite simple:
1. generate and add all mappers listed in the uses-attribute
2. add all accessible `@Mapper` instances in abstract superclasses

**Comment by sjaakd** [comment]
> If I understand correctly, this could be generalized to "a mapper uses nested mappers if they are declared in the uses-attribute or if there exists a non-private, correctly named mapper field (in this case the developer is responsible for the correct instantiation)

To be complete: that's exactly what I meant. And I just realized that I probably should drop the condition that this should be a mapper itself, because that would exclude hw mappers. Perhaps an additional annotation '@usedmapper' on the field would be required.

**Comment by afdia** [comment]
I fully agree, handwritten mappers should be possible and a new annotation for the field would make it an intentional decision of the developer that he wants MapStruct to use this as a mapper. It would also make it visible (a new dev could look up the annotation if he finds it in a mapper and immediately see what it does) instead of using a "hidden" collection logic.

It would also make the error handling simpler, because you can assert that a field which is annotated with `@UsedMapper` must not be private.
I really like it.

So the nested "mappers collection procedure" should be adapted to:
1. generate and add all mappers listed in the uses-attribute
2. add `@UsedMapper` annotated fields in abstract superclasses

**Comment by sjaakd** [comment]
> The readable error could be thrown with a catch-rethrow around the newInstance() call in Mappers.getMapper(), then you wouldn't have to declare an error throwing no-arg constructor in every impl class.

Agreed.

> It would also make the error handling simpler, because you can assert that a field which is annotated with @UsedMapper must not be private.
> I really like it.

me too.. :smile:


> So the nested "mappers collection procedure" should be adapted to:
> 1. generate and add all mappers listed in the uses-attribute
> 2. add @UsedMapper annotated fields in abstract superclasses

Indeed.

> Unfortunately, at the moment I do not have much spare time either and without any experience in writing annotation processors and the MapStruct codebase I guess I cannot help out in actual coding. Perhaps I can find some time in a few weeks, but I cannot make any promises.

I think the discussion above has proven to be already very usefull. Thanks. I'll continue to work on the PR. Thinking out loud, perhaps you find some time to add unit test cases after my initial PR. That would not require full knowlegde of MapStruct and be really helpfull. If not, no worries. For myself, it will also take time. Its a hobby after all.

**Comment by afdia** [comment]
I agree this was really a nice and productive discussion and I guess we have found a good solution to the problem. I'll wait for the PR and help with tests if possible.

**Comment by gunnarmorling** [comment]
Hey, thanks everyone for having this discussion!

@sjaakd, @agudian Any chance you could give me a TL;DR with the gist of it? What's the plan here?

**Comment by sjaakd** [comment]
@gunnarmorling .. Reckon that @agudian also still has to read it..  :smile: 

This is the executive summary (in code):

-----------
Define a StateFull mapper.

```java
@Mapper
public abstract class StatefullMapper {

    private SomeState someState;

    protected StatefullMapper(SomeState someState) {
        this.someState = someState;
    }

    public abstract BDto map (BEntity entity );

    public ADto map(AEntity entity) {
        //do something with someState in mapping method
        return null;
    }

}
```

MapStruct will generate:
```java
public class StatefullMapperImpl extends StatefullMapper {

    protected StatefullMapperImpl(SomeState someState) {
        super( someState );
    }

    @Override
    public BDto map(BEntity entity) {
        // generated method;
        return null;
    }

}
```

-----------
Then, suppose you have another mapper, using this StateFullMapper

```java
@Mapper
public abstract class AnotherMapper {

   @UsedMapper // protected/public + this annotation will trigger MapStruct to look for mapping methods in this class
    protected StatefullMapper myStatefullMapper;

    protected AnotherMapper( StatefullMapper mapper ) {
        this.myStatefullMapper = mapper;
    }

    public abstract CDto map(CEntity entity);

}
```

Note my comments int his class. MapStruct will generate

```java
public  class AnotherMapperImpl extends AnotherMapper {

    protected AnotherMapperImpl( StatefullMapper mapper ) {
        super( mapper );
    }

    @Override
    public CDto map(CEntity entity) {
        CDto cDto = new CDto();
        cDto.setBDto( myStatefullMapper.map( entity.getBEntity() ) );
        return cDto;
    }
}

```
-----------
We want to be able to avoid calling non existing code. So, we define a Factory.

```java
public interface MapperFactory {

    StatefullMapper createStatefullMapper( SomeState state );

    AnotherMapper createAnotherMapper( StatefullMapper state );
}
```

MapStruct will generate:

```java
public class MapperFactoryImpl implements MapperFactory {

    @Override
    public StatefullMapper createStatefullMapper(SomeState state) {
        return new StatefullMapperImpl( state );
    }

    @Override
    public AnotherMapper createAnotherMapper(StatefullMapper state) {
        return new AnotherMapperImpl(state);
    }

}
```
-----------
Now, putting it together from a user perspective:

```java
        MapperFactory factory = Mappers.getFactory(MapperFactory.class); // or perhaps rather Factories.getFactory(clz)

        SomeState someState  = new SomeState();
        StatefullMapper statefullMapper = factory.createStatefullMapper( someState );
        AnotherMapper anotherMapper = factory.createAnotherMapper( statefullMapper );

        CDto cdto = anotherMapper.map( new CEntity() );
        // voila
```

Additionally, the `Mappers.getMappers()` has to check for absence of empty constructors and give a meaningful error.

On the work. I have a solution for the constructors. Shortly I'll continue on the generation of the factory work. Then last the `@UsedMapper` annotation (but I reckon most ingredients are already in place for that one). @afdia (note: also Andreas) will help a bit out on the unit test if he's got time available.

**Comment by gunnarmorling** [comment]
IIRC, we discussed in the last Hangout the option of passing "state" via specifically designated parameters of mapping methods. Did you pursue that idea any further, @sjaakd? I feel it may actually resolve some of the issues we discussed. WDYT?

**Comment by sjaakd** [comment]
> Did you pursue that idea any further, @sjaakd? I feel it may actually resolve some of the issues we discussed. WDYT?

No. I spent quite some time on the current solution 😭.  I'm personally not in favor of 'dragging' a parameter through many method calls (e.g. in an object graph) to the spot where you need it, especially if this parameter 'defines' the behavior of en entire mapper, like the examples provided.

Also, you mentioned the singleton pattern that we advocate. However, we do sin ourselves :smile: in the code we generate, were we call `Mapperers.getMapper`.. 

If we (really) can't find an agreement on how to continue on this one, we should investigate if there are salvageable parts. E.g. the introduced mapper factory concept.

**Comment by sjaakd** [comment]
Will be obsolete by means of  #1006

**Comment by transaction814** [comment]
Take in this https://lnkr.fun/88cd5ce important note
