### ISSUE TITLE
problem on map lazy fields

### ISSUE THREAD

**Issue by alireza-hanifi** [mapstruct/mapstruct#778]
i don't want to fetch the lazy fields on mapping process.
i have added a field to Mapping Annotation titled as "hiberanteLazy".
when it is true, the framework checks whether  the field is loaded or not. if it is not loaded, the mapper won't fetch it.

if you approve this issue, i could commit the changes.
thank you. 😉

**Comment by agudian** [comment]
To be honest, I don't think that it's going to make it as a generally available feature, as it sounds quite specific.

However, we're here to help :), so I'd like to know a bit more about what you try to achieve. Do you want to exclude properties that are annotated in a way that Hibernate will load them lazy? Or do you want to check during the mapping if a property value in an instance has been loaded already and skip calling the getter in that case?

**Comment by alireza-hanifi** [comment]
yes, i want to skip calling the getter when the lazy field was not loaded.

**Comment by upway** [comment]
This is something "need to have" for people that use MapStruct with hibernate.
Similar functionality is in "jackson" lib with Hibernate4Module.

Is there any workaround for current final version ?

**Comment by alireza-hanifi** [comment]
@upway .yes. i implemented this feature in this repository with version 1.0 Final
https://github.com/alireza-hanifi/mapstruct

**Comment by agudian** [comment]
@alireza-hanifi first of all thanks for your pull-request and your offer to contribute that code.

I'm still not very found of the feature and the use case, though, for the following reasons:
* The feature itself addresses a very specific technology (Hibernate), which we'd like to avoid.
* Plus, leaving out properties based on them being (already) loaded or not should really really be avoided.
Lazy loads can be triggered in Hibernate through various means and by design that is supposed to be transparent for the user. For example working on two instances of the same entity class (in one session) could lead to funny effects if you access a collection on the first instance, triggering a lazy load not only on that instance but also on the other instance (if you use the great batch-fetching feature).
There are just a lot of side effects that can influence the outcome of your mapping. The user of the DTO then can't trust any of the information there, which basically makes the existence of that DTO class obsolte and I'd see that as a flaw in the design of the API / the provided DTOs. That's not something that we should advertise or even explicitlly support.
Instead, what we always recommend in such cases is the usage of specific DTOs, tailored to the needs of the use case at hand. If the user (caller) needs to access a property (e.g. a list of addresses), then it should be part of the DTO and it should always be populated - even if it has to be lazy-loaded. But if the caller doesn't need that information and you find out that the overhead is noticable, then provide an alternative *slim* DTO that doesn't contain the address list property. To the user it is always clear then that there won't be any addresses available in that DTO.

So unless @gunnarmorling or @sjaakd see this differently, I'm pretty sure that we won't add this particular feature.

However, as I wrote in #788, I see that there is demand for handling that kind of problem space (skip mapping of individual properties based on some custom logic), so we should think about making the API more approachable to customize the mapping code by dropping in some custom implementations of SPI's that we provide. Theoretically, it's already possible today to add another jar to the processor classpath and enhance the code using our existing APIs, but it requires some in-deph knowledge and it's harder than necessary because lots of our internal model is immutable - and thus harder to customize/decorate. That's something we should definitely work on. It would allow you to do your thing without us having to like it or having us to understand your reasons (which I'm sure you have)... :grinning:

Is that something you feel could work for you?

**Comment by sjaakd** [comment]
> So unless @gunnarmorling or @sjaakd see this differently, I'm pretty sure that we won't add this particular feature.

Nope. 

There is a PR on providing a hook to provide you're own (customized) templates somewhere however. Perhaps that's usable for this case as well. WDYT?

**Comment by gunnarmorling** [comment]
Hi all, first off, many thanks for your effort, @alireza-hanifi, it's great to see this kind of contribution although I agree with Andreas and Sjaak in that it does not appear to be a good candidate for being baked into the core of MapStruct as it is just too specific for a general purpose tool.

I'm not sure how far an SPI would get us here, @agudian, as this decision (map or not map a property) can only be done at runtime using the `Hibernate` class. So I indeed think we'll need into providing ways of customizing the templates for the generate code.

@alireza-hanifi, would you be interested in investigating such alternative path? Currently, it's hard coded which template to use for which class of the mapper model, so this would have to be made configurable on the user's side. If you are interested, we can discuss the details to help you finding the right starting point. WDYT?

**Comment by alireza-hanifi** [comment]
thank you for your consideration. I do agree that the method isn't that useful and I'd like to work on the generality problem
it would be my pleasure.

**Comment by almothafar** [comment]
Hi, 
Actually I have a use for lazy fields, and this is a feature for me not an issue , I really like it, if its disabled I would suffer with fetching each field with tens of lines more just to handle this case before map it? for me if I don't want to map a specific field, simply I can do `@Mapping(target = "fieldName", ignore = true)` this will do the job to ignore the field that you don't want, actually I have a use for this to even minimize the data that return with response, since I'm using mapstruct to map between Entities and the UI Objects in both ways.

But in any in any cause you want to fix it, I would like to suggest it as an option can be configured in `MapperConfig` , changing current behavior will make a lot of issues.

**Comment by kokorin** [comment]
In 1.2 with BeforeMapping it's possible:
```
@Mapper
public interface HibernateAwareMapper {
    @BeforeMapping
    default <T> Set<T> fixLazyLoadingSet(Collection<?> c, @TargetType Class<?> targetType) {
        if (!Util.wasInitialized(c)) {
            return Collections.emptySet();
        }
        return null;
    }

    @BeforeMapping
    default <T> List<T> fixLazyLoadingList(Collection<?> c, @TargetType Class<?> targetType) {
        if (!Util.wasInitialized(c)) {
            return Collections.emptyList();
        }
        return null;
    }

   class Util {
       static boolean wasInitialized(Object c) {
           if (!(c instanceof PersistentCollection)) {
               return false;
           }

           PersistentCollection pc = (PersistentCollection) c;
           return pc.wasInitialized();
       }
   }
}
```

**Comment by sjaakd** [comment]
@kokorin . thanks for your feedback.. There are actually a number of ways you can do this.. Perhaps the nicest way is including a presence checker on the target entity. See our documentation on presence checking..

Anyway: time to cleanup this issue. I'll mark it as `closing-when-no-response`.

**Comment by nhoughto** [comment]
So for future reference, the only way I found to solve this is to create a custom `AccessorNamingStrategy` and creating a special getter on the entity/hibernate objects that returns null if the real value is lazy / hasn't been initialised. Source presence checking seems like the right answer, but it doesn't work for collections, so is a no-go. With a little work I expect there is a way to have these special getters be generated by Lombok or the like, would make the ergonomics a bit nicer.

```
public class CustomSourcePresenceStrategy extends DefaultAccessorNamingStrategy {

    private static final String GETTER_PREFIX = "_mapstructGet";

    @Override
    public boolean isGetterMethod(ExecutableElement method) {
        String methodName = method.getSimpleName().toString();
        if(methodName.startsWith(GETTER_PREFIX)){
            return true;
        } else {
            return super.isGetterMethod(method);
        }
    }

    @Override
    public String getPropertyName(ExecutableElement getterOrSetterMethod) {
        String methodName = getterOrSetterMethod.getSimpleName().toString();
        if(methodName.startsWith(GETTER_PREFIX)){
            return IntrospectorUtils.decapitalize(methodName.substring(GETTER_PREFIX.length()));
        } else {
            return super.getPropertyName(getterOrSetterMethod);
        }
    }
}
```

and

```
public Set<UserEntity> _mapstructGetUsers() {
        Set<UserEntity> object = getUsers();
        return (object != null && Hibernate.isInitialized(object)) ? object : null;
    }
```

**Comment by rdasilva33** [comment]
After investing quite some time implementing MapStruct mapping I was ready to dump MapStruct because I couldn't find a way to NOT map (Hibernate lazy) collections that were not yet loaded. After all, I don't want my REST interface to give me back collections of entities that I haven't requested. I tried different things including with a custom 'AccessorNamingStrategy', but each time the Hibernate proxy would load the lazy entities before I had a chance to call Hibernate.isInitialized() myself, because the MapStruct mapper would access a method on the proxy, which in turn already loads the collection.

It is not ideal but I now have a solution by using "ignore = true" on the collection (such that MapStruct doesn't map it itself automatically), and doing the mapping myself within an '@AfterMapping'. In this method I can safely call 'Hibernate.isInitialized(entity.getCollection())' and then decide to map the collection entities if this method returns true. Otherwise the REST call now gives a empty collection back which is what I want, because for the call I'm doing I'm not interested in the collection data, and it would be unnecessary to map it.

```
	@AfterMapping
	default void doAfterMapping(final User user,
			@MappingTarget final User userDto,
			@Context final RoleMapper roleMapper) {
		final boolean isInitialized = Hibernate.isInitialized(user.getRoles());
                
		if (isInitialized) {
			// call roleMapper on each role from 'user.getRoles()' call
		} else {
			// set null or empty collection, whichever you need/prefer, or do nothing
		}
        }
```

**Comment by nhoughto** [comment]
Did you try my answer above? It should solve this exact problem. Requires special getters and hibernate config, but does exactly what you want.

**Comment by rdasilva33** [comment]
> Did you try my answer above? It should solve this exact problem. Requires special getters and hibernate config, but does exactly what you want.

I tried exactly that, but before MapStruct calls the custom getter, the Hibernate proxy already loads the collection, such that calling Hibernate.isInitialized() in the getter is always true because the collection is already loaded by Hibernate beforehand.

**Comment by filiphr** [comment]
>After investing quite some time implementing MapStruct mapping I was ready to dump MapStruct because I couldn't find a way to NOT map (Hibernate lazy) collections that were not yet loaded. After all, I don't want my REST interface to give me back collections of entities that I haven't requested. 

What I would suggest instead of using reflection is to explicitly ignore the collections you haven't requested in the mappers. Most probably you know in your REST interface what you need to return back, so calling the appropriate mapper method would be the way to go in my opinion.

**Comment by rinaldodev** [comment]
@filiphr the solution you mentioned works when you return fixed fieds in your rest interface. 
I have a problem that is similar to everyone else's. My client wants to choose the relationships it wants to be returned. And to be fair, it seems like a reasonable thing to ask. 
@kokorin's comment seems to still be the best way to achieve that behavior, although I still feel it could be easier.

**Comment by filiphr** [comment]
@rinaldodev of course it is a reasonable thing to ask. However, MapStruct is reflection free and it generates mapping code during compilation time. It has no knowledge about any runtime information.

Therefore one way to achieve this is to us what @kokorin proposed in https://github.com/mapstruct/mapstruct/issues/778#issuecomment-458135293 or what @sjaakd proposed in https://github.com/mapstruct/mapstruct/issues/778#issuecomment-458240412. 

My personal way of doing it is to add a presence checker in your entity where you can check if the collection was initialised or not.

**Comment by rinaldodev** [comment]
@filiphr Thanks for the reply.
I've been messing around with MapStruct's code to try and get this working. I even took a look at what agudian said would maybe be a way, as I explain in https://github.com/mapstruct/mapstruct/issues/706#issuecomment-583728799.

After trying to achieve that in many ways, I realized that all of the mentioned solutions only work for Collection types (xtoMany relations). I'm trying to figure out a way to make it work for xToOne relations as well, in a more generic way.

I understand presence checker seems suitable for this case, but I feel like a method called hasABC in my entity *should* trigger a lazy initialization. Please correct my if that doesn't seem right. Is there a way right now to tell MapStruct to use a method like `hasAbcInitialized`?

Another thing I thought of is that, if Optional types were supported on the target, we could solve this in pretty much the same way other people suggested here for Collection types. Please correct me if I'm wrong. I see issue #674 already exists as an open issue. Do you know if there's anyone working on that?

I also saw some people talking about something like a pre-check on properties, so we could implement a method that decides if MapStruct should continue the mapping of that property or not. From what I researched, that is not possible right now, right? That would also be a way out.

And finally, after trying many things, the only way I saw possible was to override the existing .ftl with my own code, and hope it doesn't break in a future release of MapStruct. But that seems pretty ugly.

Hope I can help we get this working. :)
