### ISSUE TITLE
"Custom" mapper

### ISSUE THREAD

**Issue by nfrankel** [mapstruct/mapstruct#78]
Hello Gunnar,

As you asked for my point of view, there's an important gap between Dozer and MapStruct in terms of features and it's the usage of custom mappers, referencing a concrete type that follows some interface to handle part of the mapping process.

This is useful when we need to map multiple source attributes to the same target attribute, *e.g.* to aggregate firstName and lastName into displayName.

**Comment by gunnarmorling** [comment]
Going to close this one as I think it has been covered since then. There is support for

* referencing custom mappers
* combining several source props into one target prop (by means of [expressions](http://mapstruct.org/documentation/#section-13), which are inline Java statements atm., we are considering to support a "real" EL as well)
* the qualifier feature I described above.

If needed, we can create follow-up issues for any remaining details. Thanks!
