### ISSUE TITLE
Multiple String object to List<String>

### ISSUE THREAD

**Issue by sureez** [mapstruct/mapstruct#810]
I have a usecase to map 
String primaryEmailAddress;
String secondaryEmailAddress;
to 
List<String> emailAddress

I have used collectionMappingStrategy to add primaryEmailAddress to the emailAddress list but when i create a mapping for secondaryEmailAddress to the emailAddress same list. I am gettting error saying Targetproperty should not be used more than once. 

What is the problem with this approach?
If there is any work-around let me know...

**Comment by sjaakd** [comment]
Hi @sureez,

This is not how this is intended. The CollectionMappingStrategy is intended to map collections to collections. 

Normally, you map source property to target property. 

To solve your problem there are several options:
1. Custom (hand written) mapper. You can refer to it by using a 'uses' relation.
2. However, if the `primaryEmailAddress` and the `secondaryEmailAddress` are just 2 mappings among many, you can use a decorator. Ignoring those to with `ignore`.
3. If that doesn't do the trick, use expressions

Please checkout our [documentation](http://mapstruct.org/documentation/).

Since this is not an issue, I'll close the PR. For questions, please checkout our [mailing list](https://groups.google.com/forum/?fromgroups#!forum/mapstruct-users).
