### ISSUE TITLE
Ignore all and only include specified field

### ISSUE THREAD

**Issue by wenerme** [mapstruct/mapstruct#812]
Something like this 

```
    @Mapping(target = "*", ignore = true)
    @Mapping(target = "id")
    @Mapping(target = "title")
    ArticleInfoDTO brief(ArticleInfoEntity s);
```

This is my workaround

```
    default ArticleInfoDTO brief(ArticleInfoEntity s) {
        return new ArticleInfoDTO().setId(s.getId()).setTitle(s.getTitle());
    }
```

**Comment by agudian** [comment]
Your workaround seems to be exactly what we have in mind for such scenarios. Our approach is not to be able to conveniently generate _all_ of the mapping code, but at least _most_ of it. Favour handling special cases manually instead of hacking too much into annotations... :wink:
Or is your example heavily simplified and I don't get the full impact of it?

**Comment by wenerme** [comment]
This is ok for me in edge case.So, close this now.

**Comment by JoshMcCullough** [comment]
I know this is closed but I was/am also looking for a similar feature where I can ignore all _child_ properties except those specifically mapped. I [https://stackoverflow.com/questions/59756573/ignore-child-object-except-specifically-mapped-properties](posted on SO), but here's a snippet:

```java
@Mapper
interface PersonMapper {
    @Mapping(target = "organization", ignore = true) // ignore organization
    @Mapping(source = "organizationId", target = "organization.id") // except organization.id
    Person toEntity(PersonModel model);
}
```
