### ISSUE TITLE
Target Bean Factory

### ISSUE THREAD

**Issue by JulianH** [mapstruct/mapstruct#824]
It would be great if the target bean could be instantiated using a factory, which could use the source bean. The idea is, that the factory could instaniate the instance based on some existing information of the source. What i have in mind is, that the entity could be instantiated by an hibernate query and the mapping method will then update the mapped fields.

The factory which will instantiate the beans, for example the entity, could look like

``` java
public class EntityFactory {
   public <T> T createEntity(@TargetType Class<T> targetClass, @MappingSource Object source) {
      // return initialized instance of T
   }
}
```

The generated mapper could look like

``` java
public class EmployeeMapperImpl implements EmployeeMapper {


   public Employee convertFromEmployeeDto(EmployeeDto employeeDto) {
      if ( employeeDto== null ) {
         return null;
      }

      Employee employee = this.entityFactory.createEntity(Employee.class, employeeDto);
      ...
   }
}
```

@gunnarmorling if you give me some hints how to implement this feature, i will try to contribute this to mapstruct.

**Comment by agudian** [comment]
Note: Currently we differentiate between factory methods and (custom) mapping methods simply by checking the parameters: if the method has no parameter or only one `@TargetType` parameter, it's a factory method - otherwise it's considred a mapping method that can be invoked for property mappings.
So we would have to come up with something else to distinguish these two cases. Perhaps by using an explicit `@FactoryMethod` annotation or something like that?

**Comment by remmeier** [comment]
+1 such a feature would be extremely useful

**Comment by sjaakd** [comment]
> Note: Currently we differentiate between factory methods and (custom) mapping methods simply by checking the parameters: if the method has no parameter or only one @TargetType parameter, it's a factory method - otherwise it's considred a mapping method that can be invoked for property mappings.

Hmm. wouldn't that be avoid by the suggestion above: so if the mapping method has only a parameter marked with `@MappingSource ` or icm with a parameter marked with `@TargetType ` its still a factory method?

**Comment by agudian** [comment]
Every parameter that is not annotated otherwise is a mapping source, so creating a new annotation `@MappingSource` could be a bit confusing: should one always use that annotation for property mappings as well? Probably not... :wink: 

So IMHO this would call for a more specific annotation on the method for marking it a _factory_. Given the idea of having factories for mappers, calling it `@Factory` would probably a bit too amiguous. `@BeanFactory` a well known term in Spring for methods / classes that would create Spring beans (our mapper instances would be Spring beans in a Spring app), so that might be a bit confusing there as well. Perhaps `@TargetBeanFactory` as method-level annotation for such factory methods?

**Comment by maciejkurowski** [comment]
+1 to usefullness

At the moment we are struggling to use Mapstruct for mapping DTO -> Entities which contain  collections of Entities as an attribute.

eg:
`@Entity
public class Emploee {

@OneToMany(mappedBy = "emploeeId")
protected List<Task> tasks;
}
`
For the successfull update of the Emploee record we need its data in EmploeeDto and list of his task ids in TaskDto objects.

While doing mapping Mapstruct will create brand new instances of Emploee entity and Task entities. 
However task entities will be "incomplete" that is they will contain only id as they were not ment to be persisted.

This breaks Hibernate session as these broken objects objects will be stored in the session.

**Comment by gunnarmorling** [comment]
I side with @agudian, having a method-level annotation seems like the way to go, e.g. `@ObjectFactory`.

@JulianH Your help with implementing this is more than welcome. As a starter, you could check out the [contribution notes](http://mapstruct.org/contributing/#section-02) as well as the subsequent technical documentation section and check out in the code base how factory methods are handled (e.g. see `BeanMappingMethod#getFactoryMethod` as a starting point). You'd have to adapt the FreeMarker template for `BeanMappingMethod` et al. so it passes the source object if present.

One open question is how to deal with the case of mapping methods with several source parameters. Specifically, how would the mapping between those parameters and the parameters of the factory method look like. That'd need some more thinking :)

**Comment by remmeier** [comment]
support for this would really helpful. Is there any progress? Or should I have a look?

**Comment by agudian** [comment]
@remmeier I don't think that anyone has started working on it, yet, so we'd highly appreciate the help! 👍

**Comment by remmeier** [comment]
a "draft" is available, more info in the PR.

**Comment by agudian** [comment]
Merged to master
