### ISSUE TITLE
@Mapper(uses = ObjectFactory.class)

### ISSUE THREAD

**Issue by PFStruct** [mapstruct/mapstruct#997]
I am having trouble mapping fields for jaxb class with   @XmlElementRef. Also adding object factory Service required a bean of type. What am I missing?

  @XmlElementRef(name = "statementGroup", namespace = "", type = JAXBElement.class, required = false),

public JAXBElement<Money> createLoanPrepaidInterest(Money value) {
        return new JAXBElement<Money>(_LoanPrepaidInterest_QNAME, Money.class, Loan.class, value);
    }

**Comment by sjaakd** [comment]
Perhaps this is helpful: checkout our [unit test for JAXB]( https://github.com/mapstruct/mapstruct/tree/master/processor/src/test/java/org/mapstruct/ap/test/selection/jaxb)

You should be able to use an `ObjectFactory` generated by XJC. The element you're after is `@XmlElementDecl`.  Its generated by XJC and you can add an OF as `uses` in the `@Mapper` annotation.

**Comment by sjaakd** [comment]
Oh. and do you really need to generate `JAXBElemt`s? Consider to set your binding to `<jaxb:globalBindings generateElementProperty="false"/>`. AFAIK you need the `JAXBElement` only for optional nillable types. (So cardinality [0,n> and ` xsi:nil="true"` in your XSD).

**Comment by sjaakd** [comment]
I'm thinking a bit further on this.. 

We are introducing `@ObjectFactory` in the 1.2 version of MapStruct. You can mark methods as `@ObjectFactory`. 

However, this is not of any help to you, since your `ObjectFactory` is generated. Perhaps we can introduce next to `@Mapping( uses = )`  `@Mapping ( objectFactories =  )`.  All methods in an object factory would then automatically be marked as `ObjectFactory`. 

Or we can do this very specific for JAXB ObjectFactories and hence extending our JAXBSupport by looking for the `XmlRegistry` annotation.

**Comment by sjaakd** [comment]
at the other hand.. The object factory method with argument and return JAXBElement is already considered as a mapping method.So it should work already with the 1.1 version of MapStruct. @PFStruct : can you provide the complete example?.

**Comment by sjaakd** [comment]
@PFStruct : can you provide a demonstrator? (see my comments above). Otherwise I'll continue to close this issue.
